### ISSUE TITLE
SemVer of the library?

### ISSUE THREAD

**Issue by trivigy** [lestrrat-go/jwx#106]
Would be greatly appreciate if the library was released with a proper sematic release versioning.

**Comment by repenno** [comment]
Agreed, but we should probably finish the cleanup and coverage before that.

Do you have any suggestions on a good semver approach?

**Comment by trivigy** [comment]
https://semver.org/ Just use the standard github prescribed versioning. In terms of waiting for cleanup and coverage, I don't agree. Why wait for tomorrow what can be done today?! Personally, and I assume many others, already depend on the software at the current (unversioned) version.

How about if you could version it now with something like `v0.1.0` or something and when the cleanups/coverage is added push the version to `v0.1.1`. This is just an example.

**Comment by trivigy** [comment]
Also, make sure to read the versioning part for go modules. https://blog.golang.org/using-go-modules. The naming is critical for golang to properly import latest stuff when doing `go get -u ./...`.

**Comment by lestrrat** [comment]
@trivigy This library predates go modules and we didn't have enough users to require much project management and hence the current situation. there's going to be some window of opportunity during the May holidays (in Japan), so we'll hopefully get something done by then.

**Comment by trivigy** [comment]
@lestrrat That would be awesome. Thank you.

**Comment by trivigy** [comment]
@lestrrat any updates? I am happy to help if you need contributors. Anything, if it helps move things along.

**Comment by trivigy** [comment]
@lestrrat Just checking in to see how's the month going. Hopefully holidays are spent well with the family. If you have the time, would greatly appreciate if you could version the repository.

**Comment by lestrrat** [comment]
@trivigy my bad. I completely lost track of the real world for the last couple of weeks. I'm DOING THIS TODAY

**Comment by lestrrat** [comment]
I was thinking of doing everything automated in The Right Way, but I just pushed a tag with Changes file, favoring speed. Apologies for the warnocking.
