### ISSUE TITLE
[v2] Accessing registered claims during verification (keyprovider)

### ISSUE THREAD

**Issue by jaspervl** [lestrrat-go/jwx#1105]
**Abstract**
At the moment, the key provider has access to the following:
1. Context
2. KeySink
3. Signature
4. Message

This is typically fine when one knows which JWKS endpoint belongs to the token being verified. However, in certain cases we want to utilise particular registered claims for deciding the appropriate JWKS endpoint out of a predefined set. Another library ([golang-jwt](https://github.com/golang-jwt/jwt)) provides a function for providing the key which has access to the unsigned token which makes this step trivial. Doing the equivalent using jwx currently involves parsing the token unverified, setting the necessary claims within the context or passing it along in a new key provider and subsequently using the jws.Verify. 

**Proposed solution/change**
Looking at the code, it seems that signature validation is done earlier then the marshalling of the token so this would require some restructuring. Having a parse option to delay the verification after the token so it can be made available would be nice. 

Or if there already exists something to accommodate this workflow I would also be happy to hear that.

**Comment by lestrrat** [comment]
I don't understand what exactly you are looking for. Please show code? I don't use golang-jwt.

The following is me guessing what you want.

> Doing the equivalent using jwx currently involves parsing the token unverified, setting the necessary claims within the context or passing it along in a new key provider and subsequently using the jws.Verify.

That's what the KeyProvider is for, no ([example](https://github.com/lestrrat-go/jwx/blob/develop/v2/examples/jwt_parse_with_key_provider_example_test.go))?
So you receive jws.Message. Use the payload, parse it and decide on the key you want to use. To me his sounds like what you are asking for.

```go
tok, err := jwt.Parse(signed, jwt.WithKeyProvider(jws.KeyProviderFunc(func(_ context.Context, sink jws.KeySink, sig *jws.Signature, msg *jws.Message) error {
    unverified, err := jwt.Parse(msg.Payload(), jwt.WithVerify(false))
    // do what you will
    if unverified.Issuer() == "me" {
       sink.Key(alg, key)
       return
     }
  })
```

**Comment by lestrrat** [comment]
> I wanted to prevent parsing the token twice and preferably do the verification separately

@jaspervl okay, that's a bit more concrete. I don't think that's possible right now, but I can see if I can make a specific KeyProvider for JWTs

**Comment by lestrrat** [comment]
@jaspervl after looking through the code again, I don't think we can really change anything. I think the most "efficient" way would be to slightly tweak my prior example:

```go
tok, err := jwt.Parse(signed, jwt.WithKeyProvider(jws.KeyProviderFunc(func(_ context.Context, sink jws.KeySink, sig *jws.Signature, msg *jws.Message) error {
  var probe struct {
      Issuer `json:"iss"`
  }
  // this is faster than calling jwt.Parse
  if err := json.Unmarshal(msg.Payload(), &probe); err != nil {
      return ...
  } 
   // do what you will with probe
    if probe.Issuer == "me" {
       sink.Key(alg, key)
       return nil
     }
  })
```

Alternatively, if you care more about efficiency than needing more boilerplate code...

```go
_, payload, _, err := jws.SplitCompact(jwtSource)
token, _ := jwt.Parse(payload, jwt.WithVerify(false))

// Note that we're calling jws.Verify, not jwt.Parse
_, err := jws.Verify(jwtSource, jws.WithKeyProvider( ..... {
   if token.Issuer() == "me" {
      ....
   }
   ...
})

if err != nil {
   // verification failed
}

// use token
```


I'm going to close this issue for now, but please feel free to open if you have anything else to add

**Comment by lestrrat** [comment]
@jaspervl  I think I forgot to post-process the result of SplieCompact. actual example code coming shortly...
