### ISSUE TITLE
Support for custom key usage types in JWKs

### ISSUE THREAD

**Issue by ljmsc** [lestrrat-go/jwx#1115]
Hey,
I just noticed that only the two key usage types which are mentioned in the [RFC](https://datatracker.ietf.org/doc/html/rfc7517#section-4.2) are supported in a JWKs ("enc" and "sig"). The RFC also says that other values MAY be used. Could you add support for custom key usage types in JWKs?

**Comment by lestrrat** [comment]
While I think I know what you are asking for, I'd rather you be more specific before I jump into conclusions.

If you are asking for new functionality, please read the [contribution guideline](https://github.com/lestrrat-go/jwx/blob/develop/v2/.github/CONTRIBUTING.md) and include code. It helps even if it's pseudocode.

**Comment by lestrrat** [comment]
FWIW I think you are encountering a problem when decoding a JWK, because it's failing at `Accept`.
Either way, I think it would be great if we can have some code.

**Comment by ljmsc** [comment]
hey, thanks for the quick reply. I just found the issue in my code. sry for bothering.
