### ISSUE TITLE
Unable to get expiration date

### ISSUE THREAD

**Issue by tobiasbp** [lestrrat-go/jwx#1136]
I'm parsing a token as seen below. I'm unable to get the correct value of _exp_ in the token header. When I inspect my token with other tools (like https://jwt.io/#debugger-io) , I see this header for the token:

````
{
  "ver": 2,
  "kid": "*****",
  "exp": 1716447235,
  "alg": "RS256",
  "jku": "**********"
}
````

Here is my demo code:
`````
t, _ := jwt.ParseHeader(
    r.Header,
    "x-jws-signature",
    jwt.WithVerify(false),
)

fmt.Printf("%s\n", t.Expiration())
`````

I get the following output:
````
0001-01-01 00:00:00 +0000 UTC
````

**Comment by lestrrat** [comment]
Without the actual token, it's hard to say. But here's what I can cob together as a minimal test case, and I can't reproduce it.

```go
func TestGH1136(t *testing.T) {
	const src = `{
		"ver": 2,
		"kid": "*****",
		"exp": 1716447235,
		"alg": "RS256",
		"jku": "**********"
	}`

	token := jwt.New()
	require.NoError(t, json.Unmarshal([]byte(src), token), `json.Unmarshal should succeed`)

	require.NotEqual(t, token.Expiration(), time.Time{}, `token.Expiration should not be zero`)

	t.Logf("%#v", token.Expiration())
}
```

The above test produces this result

```
$ go test -run=GH1136 -v
=== RUN   TestGH1136
    jwt_test.go:1870: time.Date(2024, time.May, 23, 6, 53, 55, 0, time.UTC)
--- PASS: TestGH1136 (0.00s)
PASS
ok      github.com/lestrrat-go/jwx/v2/jwt       0.003s
```

I could be off, but with the test results I'm inclined to think that the token that is producing a zero time.Time is _NOT_ the same as the token you pasted on jwt.io. I'd need more info if you're sure it's the library that is at fault.

**Comment by tobiasbp** [comment]
I have realized, that the problem is that my token, has the _exp_ in the header, not in the payload (like everyone else in the world).

Sorry for the noise, and thank you for this package.

**Comment by lestrrat** [comment]
no prob. thanks for getting back
