### ISSUE TITLE
"jwx jwk parse" is no longer used

### ISSUE THREAD

**Issue by kg0r0** [lestrrat-go/jwx#1172]
As per the [document](https://github.com/lestrrat-go/jwx/tree/develop/v2/cmd/jwx#usage-parse-pem), we can use ``jwx jwk parse`` command to parse PEM encoded key.
But, it seems that the ``jwx jwk parse`` command is no longer used. so I think we need to use ``jwx jwk format `` instead to do it.
```
$  jwx jwk parse --input-format pem ec.pem
No help topic for 'parse'

$ jwx jwk --help
NAME:
   jwx jwk - Work with JWK and JWK sets

USAGE:
   jwx jwk command [command options] [arguments...]

COMMANDS:
   generate, gen  Generate a new JWK private key
   format, fmt    Format JWK
   help, h        Shows a list of commands or help for one command

OPTIONS:
   --help, -h  show help

$ jwx jwk format --input-format pem --output-format json ec.pem
{
  "crv": "P-256",
   ...
}
```
How about I think the document needs to be fixed as above?

**Comment by lestrrat** [comment]
Thanks. PRs welcome :)

**Comment by kg0r0** [comment]
I will close this Issue as the PR has been merged. Thanks for the quick handling!
