### ISSUE TITLE
Leaky go routines when using jwk.Cache

### ISSUE THREAD

**Issue by sanchit-CRL** [lestrrat-go/jwx#1173]
**Describe the bug**
Initialising the jwk Cache creates multiple goroutines due to the underlying library https://github.com/lestrrat-go/httprc

Please attach the output of `go version`
go version go1.23.0 darwin/arm64

**To Reproduce / Expected behavior**
```
// GoroutineLeakChecker is a utility to check for goroutine leaks.
type GoroutineLeakChecker struct {
	initialGoroutines int
}

// NewGoroutineLeakChecker initializes a new GoroutineLeakChecker.
func NewGoroutineLeakChecker() *GoroutineLeakChecker {
	return &GoroutineLeakChecker{
		initialGoroutines: runtime.NumGoroutine(),
	}
}

// Check checks for goroutine leaks and returns an error if any are found.
func (glc *GoroutineLeakChecker) Check() error {
	time.Sleep(1 * time.Second) // Give some time for goroutines to settle
	finalGoroutines := runtime.NumGoroutine()
	if finalGoroutines > glc.initialGoroutines {
		return fmt.Errorf("goroutine leak detected: initial=%d, final=%d", glc.initialGoroutines, finalGoroutines)
	}
	return nil
}

func main() {
	glc := NewGoroutineLeakChecker()

	// initializing the cache creates leaky goroutines
	jwk.NewCache(context.Background())

	// Check for leaks
	if err := glc.Check(); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("No goroutine leaks detected")
	}
}
```

**Comment by lestrrat** [comment]
I think using SetGlobalFetcher did the job

* https://github.com/lestrrat-go/jwx/issues/928
* https://github.com/lestrrat-go/jwx/blob/4c5a198ff68252ed88e3c340b7a1f3f379caac2e/jwk/jwk_test.go#L2166-L2210
* https://github.com/lestrrat-go/jwx/blob/4c5a198ff68252ed88e3c340b7a1f3f379caac2e/jwk/fetch.go#L62-L81

For most cases the above should just work.

If you encounter [this](https://github.com/lestrrat-go/jwx/issues/1047) when you are trying to do whatever it is that you want with the `SetGlobalFetcher`, you're going to have to bite the bullet and either live with the goroutines hanging around, or use v3.

**Comment by sanchit-CRL** [comment]
Thanks for the update, do we know when will v3 be released ?

**Comment by lestrrat** [comment]
@sanchit-CRL It's honestly mostly done, but I haven't found a compelling reason for users to migrate over to v3 (i.e., there's no single "killer" feature), and it's really just a collection of QoL improvements that also break API. I would love to move on to v3, but I also don't think anybody would at this point, so that's why it's been sitting in develop/v3 for some time now.
