### ISSUE TITLE
Cleanup Date Processing

### ISSUE THREAD

**Issue by repenno** [lestrrat-go/jwx#118]
In jwt_test.go we use NumericDate as string in all tests.

Source: `{"` + jwt.IssuedAtKey + `":` + aLongLongTimeAgoString + `}`,   

There are no tests for NumericDate as a number, actually there is no coverage for:

func (n *NumericDate) UnmarshalJSON(b []byte) error {}

The RFC does not seem to allow NumbericDate as string, only JSON numeric value.

NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.

**Comment by lestrrat** [comment]
No, it's being tested as you described. Here's what you would've seen if you added `t.Logf` in the test

```
--- PASS: TestUnmarshal (0.00s)
    --- PASS: TestUnmarshal/single_aud (0.00s)
        jwt_test.go:194: Source: {"aud":"foo"}
    --- PASS: TestUnmarshal/multiple_aud's (0.00s)
        jwt_test.go:194: Source: {"aud":["foo","bar"]}
    --- PASS: TestUnmarshal/issuedAt (0.00s)
        jwt_test.go:194: Source: {"iat":233431200}
```

As you can see, the JSON being tested is accepting a numeric value, not a string.

**Comment by repenno** [comment]
Sorry, I believe you are wrong. NumericDate is this project is time.time, not a unit64. I believe that to be a bug in itself. 

I removed the function, run all tests, all green. Please remove the function and run all tests. You will see Unmarshal is never used.

**Comment by lestrrat** [comment]
I don't understand. I thought that "we were using JSON strings as input" was your gripe.

> In jwt_test.go we use NumericDate as string in all tests.

Your original issue does not state anything about time.Time being the problem. Clarify please?

**Comment by repenno** [comment]
Apologize, I am all over the place thoroughly testing and modifying the library. As far as the date related claims goes I see the following:

1 - I thought we accepted date claims as strings, you are right, we do not. But we accept them as json.Number by using token.Set(). You recently added a test to cover this possibility. I am not sure we should accept it, but it is minor issue.

2 - NumericDate is a time.time.  I believe NumericDate should be a timestamp (as far as RFC goes), not a time struct. Another option is to not call it NumericDate in the code. 

3 - We never use (NumericDate) Unmarshal function since JSON will never come with time.time as a value.

**Comment by lestrrat** [comment]
@repenno I'm going to reply here for the sake of discussion, but if you have more to say, please file a separate issue.

> re: json.Number

it stays :)

> NumericDate as timestamp

When you request change like this you should show what your intended usage is.
What is it that you are trying to achieve? API changes should be made to fit the
programming style, not to appease the RFC.

The point of this NumericDate is, for example, if you want to know when a token was issued, you could do

```
log.Printf("%s", token.IssuedAt())
// or other date arithmetic, handling, etc
```

instead of

```
log.Printf("%s", time.Unix(token.IssuedAt(), 0))
// or other date arithmetic, handling, etc
```

Now, you could argue that the one would use the integer representation more than the time.Time representation, and in which case, I'm game to being persuaded given proof, but event then, the initial reaction should be to afford a different API, and not to change its guts. We should only change the guts when it actually hurts the API consumers. Currently I don't see a clear reason to do so.

> re: Unmarshal function

I think this is just a case of missing test. There can certainly be improvements in the details, and I don't  deny I need to do a better job there.

**Comment by repenno** [comment]
> On Apr 25, 2019, at 9:37 PM, lestrrat <notifications@github.com> wrote:
> 
> @repenno I'm going to reply here for the sake of discussion, but if you have more to say, please file a separate issue.
> 
> re: json.Number
> 
> it stays :)
> 
> NumericDate as timestamp
> 
> When you request change like this you should show what your intended usage is.
> What is it that you are trying to achieve?
> 
> API changes should be made to fit the
> programming style, not to appease the RFC.
> 
> The point of this NumericDate is, for example, if you want to know when a token was issued, you could do
> 
> log.Printf("%s", token.IssuedAt())
> // or other date arithmetic, handling, etc
> instead of
> 
> log.Printf("%s", time.Unix(token.IssuedAt(), 0))
> // or other date arithmetic, handling, etc
> Now, you could argue that the one would use the integer representation more than the time.Time representation, and in which case, I'm game to being persuaded given proof, but event then, the initial reaction should be to afford a different API, and not to change its guts. We should only change the guts when it actually hurts the API consumers.
> 

It certainly caused me confusion 😬

NumericDate bound to time.time is confusing since it has a specific meaning in the RFC, but It is to late too change.
> Currently I don't see a clear reason to do so.
> 
I agree, but I pursue these things due to my compulsive nature for detail. I try to avoid API usage and interop problems.  I will see what I can do in my copy of the repo

> re: Unmarshal function
> 
> I think this is just a case of missing test. There can certainly be improvements in the details, and I don't deny I need to do a better job there.
> 

I do not think the issue here is more test coverage. It is a dangling function that has no use. Creating a test will provide coverage just for the sake of numbers since the function itself has no use in the current architecture. All unmarshal today is made to maps and is custom. I could create a function foo() , create a test but that does not mean it belongs.

**Comment by lestrrat** [comment]
ah I think I see it re NumericDate.Unmarshal. will work on it later

**Comment by lestrrat** [comment]
I re-checked, and yes, `json.Unmarshal(..., jwt.Token)` doesn't invoke `jwt.NumericDate.UnmarshalJSON`, but taking UnmarshalJSON out should be done only when NumericDate has been obscured from the exported API. If an object is part of serialized object (`jwt.Token`) and is exported, you should expect the users to somehow abuse it by serializing `jwt.NumericDate` by itself, so I wouldn't just rip the UnmarshalJSON.

However, this looks doable if just move NumericDate to an internal package.
So the answer to if we should remove UnmarshalJSON is, yes, but not by just ripping it out.
