### ISSUE TITLE
JWT aud field is slice of string and is not possible to use as string

### ISSUE THREAD

**Issue by andreadragotta** [lestrrat-go/jwx#1187]
Hi,

as i already write in the title the aud field in claims is slice of string but for example in Google Wallet API JWT Sign is necessary to pass a string value. 

Is possible to avoid this library constraint. 

The JWT rfc https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3 allow the single string value in special case. 

Thanks

**Comment by lestrrat** [comment]
https://github.com/lestrrat-go/jwx/blob/develop/v2/docs/01-jwt.md#serialize-the-aud-field-as-a-single-string
