### ISSUE TITLE
Comment contains incorrect code example.

### ISSUE THREAD

**Issue by coryschwartz** [lestrrat-go/jwx#1233]
This comment [here](https://github.com/lestrrat-go/jwx/blob/develop/v3/jwt/serialize.go#L43)

gives an example for encrypting a JWT toekn in a JWE container, and the example tells us to do this:

```
//	   Encrypt(jwa.RSA_OAEP, key.PublicKey).
```

But I think this might be wrong. Encrypt() wants an `EncryptionOption` which is not implemented
by the algorithm or the the key. Instead, I think this what is intended.

```
// publicKey := recipientPublicKeyFromSomewhereMaybeFromCache()
...
// Encrypt(jwt.WithEncryptOption(jwe.WithKey(jwa.RSA_OAEP(), publicKey)))

```

**Comment by lestrrat** [comment]
That's probably an artifact from v1. Thanks.
