### ISSUE TITLE
Couple of issues...

### ISSUE THREAD

**Issue by kmansoft** [lestrrat-go/jwx#128]
Hi,

Filing two issues at once - I was just checking out your library hoping to use it, but hit two blockers.

1

jwk.Fetch("https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration")

Returns err = "nil is invalid kty", but when looking at that page (document), all the key types there are specified as "rsa", so the error message (and the failure itself) don't make sense.

2

The readme at the repository level (main example) starts out with `jwk.New()` but `New` now takes a parameter. I figured it was the signing method but then hit  another inconsistency and couldn't get past that.

**Comment by kmansoft** [comment]
The exact error for Microsoft keys is:

`failed to construct key from keys: unsupported kty type <nil>`

**Comment by lestrrat** [comment]
That URL points to an [OpenID Provider Configuration](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest), but `jwk.Fetch()` fetches a [JSON Web Key](https://tools.ietf.org/html/rfc7517). Those two are completely different things.

wrt README, I don't get. the README clearly has a parameter being passed to it.

![image](https://user-images.githubusercontent.com/49281/61526616-ae9d5780-aa55-11e9-8a18-029055ec8018.png)


I'm going to close this for ow, but feel free to reopen if you think I'm overlooking something on your issue.
