### ISSUE TITLE
Protected header

### ISSUE THREAD

**Issue by hfogelberg** [lestrrat-go/jwx#129]
I need to communicate with a service, which requires the kid to be set to a specific value and can't figure out how to do it. The sample code supplied by the service suggests the following in Python:

````   
 protected_header = {
        "alg": ""RSA-OAEP",
        "enc": "A256CBC-HS512",
        "typ": "JWE",
        "kid": "MY_KEY_ID",
    }
    jwetoken = jwe.JWE(payload_bytes, recipient=public_key, protected=protected_header)
    return jwetoken.serialize(compact=True)
````

Sorry about being new to jwx! I am grateful for any suggestions you could give.

**Comment by lestrrat** [comment]
Sorry, I completely missed this issue. It's been a while so details escape me, but IIRC the RFC specified protected headers to be constructed out of the original message, not necessarily specified the end user, and hence the current set up where `jwe.Encrypt` doesn't take in user-specified headers.

**Comment by lestrrat** [comment]
This issue has been left unanswered for a while, so I will be closing it. Please open a new issue if this is still a problem
