### ISSUE TITLE
Password protected pem && Headers?

### ISSUE THREAD

**Issue by paulm17** [lestrrat-go/jwx#131]
I'm trying to duplicate functionality with PHP.

```
  $signer = new Sha256();

  // Set path of private_key.pem. Overwrite the default file as sample.
  $privateKeyString = new Key(
      "file:///box/" . $this->config['private_key_file'], $this->config['passphrase']
  );

  $assertion = (new Builder())
      ->setHeader('kid', $this->config['public_key_id'])
      ->setIssuer($this->config['au_client_id'])
      ->setSubject($id)
      ->set('box_sub_type', $type)
      ->setAudience($this->audience_url)
      ->setId(uniqid('ABC'))
      ->setIssuedAt(time())
      ->setExpiration(time() + $this->config['expiration'])
      ->sign($signer,  $privateKeyString)
      ->getToken();
```

Which outputs the following:

```
  ^ Lcobucci\JWT\Token^ {#985
    -headers: array:3 [
      "typ" => "JWT"
      "alg" => "RS256"
      "kid" => Lcobucci\JWT\Claim\Basic^ {#976
        -name: "kid"
        -value: "38u7xxxx"
      }
    ]
    -claims: array:7 [
      "iss" => Lcobucci\JWT\Claim\EqualsTo^ {#977
        -name: "iss"
        -value: "hd2meuymeq5erwineh2lt1vghxxx0000"
      }
      "sub" => Lcobucci\JWT\Claim\EqualsTo^ {#978
        -name: "sub"
        -value: "248410000"
      }
      "box_sub_type" => Lcobucci\JWT\Claim\Basic^ {#979
        -name: "box_sub_type"
        -value: "enterprise"
      }
      "aud" => Lcobucci\JWT\Claim\EqualsTo^ {#980
        -name: "aud"
        -value: "https://api.box.com/oauth2/token"
      }
      "jti" => Lcobucci\JWT\Claim\EqualsTo^ {#981
        -name: "jti"
        -value: "ABC5e0b3370a6458"
      }
      "iat" => Lcobucci\JWT\Claim\LesserOrEqualsTo^ {#982
        -name: "iat"
        -value: 1577792368
      }
      "exp" => Lcobucci\JWT\Claim\GreaterOrEqualsTo^ {#983
        -name: "exp"
        -value: 1577792428
      }
    ]
    -signature: Lcobucci\JWT\Signature^ {#984
    }
    -payload: array:3 [
      0 => "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjM4dTdwamxwIn0"
      1 => "eyJpc3MiOiJoZDJtZXV5bWVxNWVyd2luZWgybHQxdmdoY21rNDEwNCIsInN1YiI6IjI0ODQxOTQ2MCIsImJveF9zdWJfdHlwZSI6ImVudGVycHJpc2UiLCJhdWQiOiJodHRwczpcL1wvYXBpLmJveC5jb21cL29hdXRoMlwvdG9rZW4iLCJqdGkiOiJBQkM1ZTBiMzM3MGE2NDU4IiwiaWF0IjoxNTc3NzkyMzY4LCJleHAiOjE1Nzc3OTI0Mjh9"
      2 => "JUZqTydnL7UT4aksNAqXJpAYDqelvOXimc85p2qnrvCfr1ZV-DBQLt98GagwbHt2Wn0V5a6oYFgUwo5tfyHA5ElYBPYS7AeF96zTyDEJlCFe8IjzObRWP4tdTePsRiXlYGDt7CbWIQ_5mVLV5zrNF0o1ZBfwEenx0PBB1jbnGZ068rO7B5ejHIC7vy7sSmAb7Yn6xZFK5YLeZxBZUUmoch8bM59wFirAAyG8pkBZqUdHSExzt-Q7QisgeoqdLdc9QcklwROiBvDgOkWtCwgee77bsgc8V_m9BAltgu-zXnuIf2ztQRhlNFi-dp6GuNL15sxtz84uh13UroCM9A1hRw"
    ]
  }
```

With go, I have achieved the following result:

```
  {
    "aud": "https://api.box.com/oauth2/token",
    "exp": 1577792181,
    "iat": 1577792121,
    "iss": "hd2meuymeq5erwineh2lt1vghxxxxxxx",
    "jti": "ABC5e0b327973b533.11640101",
    "sub": "248000000",
    "alg": "RS256",
    "box_sub_type": "enterprise",
    "kid": "38u7xxxx",
    "typ": "JWT"
  }
```

The problem is that I'm getting from the service I wish to authenticate to:

```
{"error":"invalid_grant","error_description":"Algorithm not allowed"}
```

I'm not sure whether it's because I'm missing headers or that there's no password support for the pem?

Many thanks!

**Comment by lestrrat** [comment]
Sorry, I had missed this issue. TBH there's not much we can do without seeing the Go code

**Comment by paulm17** [comment]
@lestrrat No worries, thanks for your time in advance.

Here is the complete [code](https://gist.github.com/paulm17/08ecbde60d9a678bd8ae7e4a843d19af).
Here is the pem [file](https://gist.github.com/paulm17/8c505b407db249c37f339a0f2958ee1c).

Let me know if you need anything else.

**Comment by lestrrat** [comment]
Your code has a few weird spots:

1) [line 38](https://gist.github.com/paulm17/08ecbde60d9a678bd8ae7e4a843d19af#file-gistfile1-txt-L38) says `RS256`, and yet you are signing using `HS256` at [line 56](https://gist.github.com/paulm17/08ecbde60d9a678bd8ae7e4a843d19af#file-gistfile1-txt-L56). BTW, IIRC you don't even need to set that header when you call the `Sign()` method, because it does it for you

2) I highly doubt that using `ioutil.ReadFile` does what you want, because it's just loading the text of your pem file. You probably need to parse the contents using `encoding/pem` and get a `Block` object, and use its `Bytes` element.

**Comment by paulm17** [comment]
Thanks for the clarifications, let me adjust the code and get back to you.

**Comment by paulm17** [comment]
I have updated the [code](https://gist.github.com/paulm17/5be76f412eef34c951078c93ddd3c311).

I now get: 

    panic: x509: no DEK-Info header in block

I googled and found [this](https://stackoverflow.com/a/44681542)

Unfortunately JWT and encryption is definitely not something I know, so any help appreciated.  Thanks.

**Comment by lestrrat** [comment]
The error says x509, so perhaps what you are looking for is `crypto/x509`. 

Since this has now deviated from an issue about `jwx` module, I'll close this issue. If you find a problem with `jwt`, please let us know separately.

**Comment by paulm17** [comment]
I finally got back to this issue and solved it.  Following up incase anyone has a similar issue:

I had to decrypt the encrypted pkcs8 key.   See [here](https://stackoverflow.com/a/55541848/439750).
