### ISSUE TITLE
No method to return all claims.

### ISSUE THREAD

**Issue by ShramikGajlekar** [lestrrat-go/jwx#132]
For refreshing token, we use all the claims from previous tokens and modify the `iat` and `exp` claims. If we have several claims, it's painful to extract all claims from the token and sign a new one.

**Comment by lestrrat** [comment]
PR #135 implements `Claims()` to return an iterator, `Walk()` to examine each pair from the iterator,  and `AsMap()` to generate a `map[string]interface{}`. If you could check it, that would be great. And this works for you, I will merge it.

**Comment by lestrrat** [comment]
I botched this PR thinking I was in a different branch. Need to redo the PR :/

**Comment by lestrrat** [comment]
Whew, I salvaged it from my git history. #138 should do it.


@ShramikGajlekar FYI I'm going to merge this when I wake up tomorrow, which is about 12 hours from now

**Comment by ShramikGajlekar** [comment]
I think this would resolve the issue. Thanks for the resolution.  Most of the applications requires to copy all claims to sign a new one from the older token, this would help us all a lot :)

**Comment by lestrrat** [comment]
@ShramikGajlekar just FYI, after fooling around with `jws` and `jwe` packages I needed to change the iterator pattern in `jwt`. You still have `AsMap`, but if you are using the iterators, their usage will change slightly in the near future.
