### ISSUE TITLE
Fetch AWS Cognito JWK got the error message

### ISSUE THREAD

**Issue by ShawnOY** [lestrrat-go/jwx#136]
Hello,
I try to get JWK from AWS Cognito, but I got the error message and I have no idea why return illegal base64 data.

Code

```
package main

import(
  "log"
  "github.com/lestrrat-go/jwx/jwk"
)

func main() {
  set, err := jwk.FetchHTTP("https://cognito-identity.amazonaws.com/.well-known/jwks_uri")
    if err != nil {
      log.Printf("failed to parse JWK: %s", err)
      return
    }

    log.Println(set)
}
```

Result:
`2020/02/24 19:01:58 failed to parse JWK: failed to extract from map: failed to construct key from map: failed to extract key from map: failed to get required key n: failed to base64 decode key n: illegal base64 data at input byte 64`

**Comment by lestrrat** [comment]
@ShawnOY Can you please check PR #137.

**Comment by ShawnOY** [comment]
@lestrrat It's work! Thank you!

**Comment by lestrrat** [comment]
thanks for checking!
