### ISSUE TITLE
jws.VerifyWithJKU Passes on invalid signature

### ISSUE THREAD

**Issue by akhi4u** [lestrrat-go/jwx#140]
I was using v0.9.0,  `jws.VerifyWithJKU()` validation worked fine. But once I updated to the newer version v0.9.1, it no longer validates the signature, returns no error. This is a serious issue. Could I get any help regarding this? 

Thank you.

**Comment by leandrorondon** [comment]
I'm facing the same problem. The issue is in the `VerifyWithJWKSet` function - `err` variable is redeclared within `for` loop and end up returning a `nil` err.

**Comment by lestrrat** [comment]
Sorry for warnocking this, but could you kindly provide with a reproducible test case?

**Comment by lestrrat** [comment]
Hi, @akhi4u @leandrorondon 

It would be most helpful if you could kindly test PR #145, and again, sorry for the late response here

**Comment by lestrrat** [comment]
I added tests, and I'm pretty certain I plugged the whole, so will merge #145 and close this issue.
