### ISSUE TITLE
field names are horrendous

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#149]
Well, it's been a while since I first looked at the actual implementation of the code here, and I think I really need to refactor `jws`. I have plans, but the API may change.

**Comment by lestrrat** [comment]
Also, `jwe`

**Comment by reinkrul** [comment]
I didn't come across anything that triggered me in particular, just that in the `jws` package `StandardHeaders`' (jws/headers.go) field names are all prefixed with 'JWS' (`JWSalgorithm`, `JWSkeyID`), which seems a bit superfluous to me.

**Comment by lestrrat** [comment]
Yes, and while I don't quite remember how I came to that implementation, I'm pretty sure it has to do with how to Marshal/Unmarshal to/from JSON. This has been fixed in #154
