### ISSUE TITLE
refactor jwk

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#158]
Wondering if I should apply smething similar to #154 #156 on `jwk` (hide `*stdHeaders` behind `Headers` interface, add iterators, etc)

@sonatard you are probably my most recent and active user of this package. thoughts? （日本語でいいですよー）

**Comment by sonatard** [comment]
jwx生み出して頂きありがとうございます！
JWTライブラリの中で一番良いインターフェースをしていてすごく勉強になりました。

ご相談頂いた内容ですが、Goらしさという観点だと、パッケージ利用者が利用する構造体の値はprivate filedでGetやSetで操作するのではなくPublic FieldになっているのがGo wayっぽいかなと思います
サンプル
https://golang.org/src/crypto/x509/x509.go?s=21657:25704#L652

ただこの場合はSetterで値が正しいことを保証できていないので、構造体作成直後や重要な処理をする前validationが必要になります。
https://github.com/golang/go/blob/2a029b3f26169be7c89cb2cdcc3db4b5d097a8b8/src/crypto/tls/handshake_client.go#L815

そうなるとmapを経由せずに直接jsonの文字列をjson.UnmarshalでStandardHeaders構造体に代入できる点はいいと思いました。

インターフェースについては複数の実装がないと思うのでinterfaceではなく実体でいいのかなとも思いました。

今までの背景を理解していないので、ご参考程度にお願いしますー

**Comment by lestrrat** [comment]
Public fieldは僕は完全に反対派で、例えば `struct { A (required), B (optional), C (optional) }`みたいな状態を保証できないのが完全に無し、だと考えてます。`Verify`すればいい、もわかるのですが僕がは「そもそもユーザーがその値を直に操作できると思ってしまう」のはいけてないAPIだと思うので隠蔽したい派です

`interface`も上記と同じ理由で、 `var s HogeHeaders` (初期化してない）を許可しないためです。`interface`にして`h := jwhogehoge.NewHeaders()` と初期化を強制するためですね。

PRの残りの部分についてはjws/jwt/jwk/jweで全く同じAPIのIteratorとかが入るとかあたりがポイントです。

**Comment by sonatard** [comment]
正しい使い方をユーザに強制するために、InterfaceとPrivate fieldを利用する方針理解しました

jwkもheaderをWalkしているところがあるので、同じ仕組みを導入するのはいいと思います！

**Comment by lestrrat** [comment]
確認ありがとうございます。ちょっと実際にそれでいけるのかは実装をしながら考えますが、多分 jws/jwt/jwk/jweで大統一ヘッダーAPIになると思います
