### ISSUE TITLE
Sign JSON with a p12 certificate

### ISSUE THREAD

**Issue by localhosted** [lestrrat-go/jwx#160]
I'm trying to sign and verify a JSON payload with a certificate. I found a Ruby library that does this: https://github.com/alexmx/jws-signer/blob/master/jws-signer.rb

I want to port it to Go using jwx. I saw the [JWS example ](https://github.com/lestrrat-go/jwx#jws) however it creates a key on the fly. Can I extract the certificate with `golang.org/x/crypto/pkcs12` and pass that as the privakey?

**Comment by lestrrat** [comment]
Yes, that sample is just a contrived example to show how to use a key. Grab the appropriate key from anywhere, and pass that along.
