### ISSUE TITLE
Header setter error handling

### ISSUE THREAD

**Issue by sonatard** [lestrrat-go/jwx#164]
Protocol header setter returns an error, but ignores it in multiple places. I found it by https://github.com/golangci/golangci-lint.

If we should always do error handling, I will create a pull request to add error handling. If error handling need not necessary, please tell me what is the difference between need error handling or not?

**Comment by lestrrat** [comment]
error handling should be tested, yes. Yes, I was being lazy.

**Comment by sonatard** [comment]
Thanks!!

**Comment by sonatard** [comment]
@lestrrat I forgot this issue. I'd like to fix it before release v1.0.0.
Can you wait for the release v1.0.0 to next Tuesday? #171

**Comment by lestrrat** [comment]
Yes, of course.
