### ISSUE TITLE
OpenID Claims Take 2

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#170]
Redo #117

# Basic strategy

Default usage:
```
jwt.Parse(...)
```

We'll add an option to specify the token type

```
openidToken := openid.Token() // we'll create this package in a PR
jwt.Parse(..., jwt.WithToken(openidToken)) // specify the token that will get passed to json.Unmarshal
```
And also, we will add a utility option

```
jwt.Parse(..., jwt.WithOpenIDToken())
```

**Comment by lestrrat** [comment]
still pondering: make `jwt.Token` an interface?

currently `(jwt.Token).privateClaims` can be uninitialized depending on how the token has come to be :/ forcing usage of a constructor removes this corner case

then `openid.NewToken() openid.Token` would probably be the corresponding OpenID claim-aware jwt Token

**Comment by mike-morr** [comment]
@lestrrat Is 1.0 coming soon now that this is complete?

**Comment by lestrrat** [comment]
Yeah, but I was waitingon #177
