### ISSUE TITLE
can't set kty in jwk

### ISSUE THREAD

**Issue by JavadHosseini** [lestrrat-go/jwx#192]
Im new to jwt, I want to set my "kty" to rsa, apparently it can not be done this way:
`set.Set(jwk.KeyTypeKey, "rsa")`
and kty value remains "oct".

**Comment by lestrrat** [comment]
Yes, that's intended, because you presumably instantiated a symmetric key. I couldn't think of a situation off hand where you would want to change the key type on the fly ( I mean, the underlying structures are completely different ). If you thin you have a legitimate use case, please give us some code.

**Comment by JavadHosseini** [comment]
yes, I thought this would be the reason for not changing the kty. but I'm using a asymmetric key. Also  I converted my public key in two online pem to jwk converters and kty was rsa in both of them. but the results is different with jwx.

**Comment by lestrrat** [comment]
I'm confused. Please show me your code? psuedocode is fine, I just don't understand why you would need to set the kty

**Comment by JavadHosseini** [comment]
I understood your reason for not changing the kty and I don't have argue with that. The real problem now is that I'm using rsa and even I used an online pem to jwk converter to ensure. when I convert my public key to jwk in that the kty is rsa. but when I convert this public key with jwx package the kty shows "oct".

**Comment by lestrrat** [comment]
Ah, so there's a conversion error? again, I need code, and possibly the keys that you are using.

I know it's hard to disclose keys, but for starters, if you could give me the code and the keys in JSON but with the confidential parts removed (e.g. for RSA keys, the d/dp/dq/p/q/qi fields), that would be a start. 

It may very well be a bug in my code, but  I'm going to stress this once again: _we need code_

**Comment by JavadHosseini** [comment]
here's the code: (I already have a key pair)
`pubKey, err := ioutil.ReadFile("keys/" + pubKeyPath)
	if err != nil {
		log.Printf("key not found", err)
		return err
	}
set, err := jwk.New(pubKey)
	if err != nil {
		log.Printf("failed to convert to JWK: %s", err)
		return err
	}
	err = jwk.AssignKeyID(set)
	if err != nil {
		log.Printf("failed to convert to JWK: %s", err)
		return err
	}
	set.Set(jwk.AlgorithmKey, "RS256")
	set.Set(jwk.KeyUsageKey, "sig")
`
and the public key:
`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5r2fasfZFc8ZtkBePlQx
IvcG+7hG2r6z4sBfh/J62BTIlkBCYIUOXCDBGHYy/N8VXnBOpPBw+nQShCaJtDDG
aXMSPK/HAVOGqnq24IH5tE4qEuf0sNz/glx2q9qLopYjw/aFCrAF6TdXAkcc9djU
a3Cl8++QQfyMkYwdayt4wWeA1L6A9w5TYEPKaLPe/doUx/5rcHPCDlEsuYoCsYvV
VTZpfNXiz79W0qLYyMMx8tM6/tvugr3Wu9Qub/rXtNsdYD+PWqIoyTMJ783Yho8V
HIl4dzkIR5Z5dI6ILvtP0BIIh/lyANLeudzifzmazLr7Zmbs0zNY751t6j+IIvDz
jQIDAQAB
-----END PUBLIC KEY-----
`
private key in json:
`    "message": {
        "kty": "oct",
        "alg": "RS256",
        "kid": "7xkgTEoFmPpKqZDk3ewd1VuvIxyZqA3IwxQyHLokaoM",
        "use": "sig",
        "k": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBNXIyZmFzZlpGYzhadGtCZVBsUXhJdmNHKzdoRzJyNno0c0JmaC9KNjJCVElsa0JDCllJVU9YQ0RCR0hZeS9OOFZYbkJPcFBCdytuUVNoQ2FKdERER2FYTVNQSy9IQVZPR3FucTI0SUg1dEU0cUV1ZjAKc056L2dseDJxOXFMb3BZancvYUZDckFGNlRkWEFrY2M5ZGpVYTNDbDgrK1FRZnlNa1l3ZGF5dDR3V2VBMUw2QQo5dzVUWUVQS2FMUGUvZG9VeC81cmNIUENEbEVzdVlvQ3NZdlZWVFpwZk5YaXo3OVcwcUxZeU1NeDh0TTYvdHZ1CmdyM1d1OVF1Yi9yWHROc2RZRCtQV3FJb3lUTUo3ODNZaG84VkhJbDRkemtJUjVaNWRJNklMdnRQMEJJSWgvbHkKQU5MZXVkemlmem1hekxyN1ptYnMwek5ZNzUxdDZqK0lJdkR6alFJREFRQUJBb0lCQUJlQy92bU1mNnhmUEFsOApLWjVFU2ZWOEluUUg1UUJwS2o5U3h1azlaaE1hbXcza1lsOGZiOFVuZVVXYTFiczZxQnpGYU40WnVnbHJSbSs4CjFZOU00UXJodE53R05Vc0hUZE9WU1lrNjlVelFJaTFuQVdIOFF2VHZveEFENXZLY1JleXo4LzZRelNsa2dETTEKTjlnOVRmZmN0S3hVbnVoNmFZQnpQSlF0QzlMNUhYaHNETGpKSDFCUXFVUkU0TUZBcGNmQW4rSDJUYUNOa1Y2VgprUFJ2d0p6MmtPTk5SaklYN1Q2aEtvR2tpTGNYeXM3Z09PM2dxM0kzUyszVDVRS2Q2YmJEZnZRN2F1RHJuSzhYCkRYOFZOZFlnMlo3eGJKbWpXWGtqdFVDSlU3T2Nacm5GRmp5WmlHVkcwbkJ5TllOYXQxNlRkZy9PUHp2bVl2bEcKejFvbkdHa0NnWUVBOWxyVTVsREpHS2pJL3h0Qm8rYnJ0TXFUWjBlOWwyQ3lpWkZXOVRSU0Jsa09kTkNHRzlvSApFNjFyQXpJZ0d2eENmK2NoSFNoV01HMm8vOEw2NE5pTlJGNG5idzBiVkVDWnlGRXZraE54dkFkdjBHSTVFdVJKClcyTUxCTUdjaDlIcWphMm4yS2UzbU9GbXNxK0NkMElOYmhpNktYMTZ4NG1IV0MzVk5jTWdYSDhDZ1lFQTc4WkwKUE1ZWUpNK09EZVNPZTVCU2QwZzdheHFZNVFlQjQ2RmcxNWNjOE1UVkFVQ0NBOXdiZjRvdElqb2lNYnd6UmpqMwpBczBlT2R4Sko1UStDTnU3WlYxSTVoNzVWUVRjZ3NNTDQreUlSRlNPYngvWXpFQ1NZbHpDRDVIcllsNlp5QTEyCjc5ZnRUejZ4TzdrbVQ3aGRRRWNNcHY3RUIwK2krR0pwMW5CdldmTUNnWUJMRUZnb3FWcnM4WmowNmxndzJjN2UKTW8rQmU4R1FHMzJySHlidzVmVk1TOXgweVlqamVhYUlYMkhwQWwvMytQOUdPNlhDWGFVTmNveDVDZThwamJKVgpyNTZ5WHJzQ0RBRVBvWFV1UEZCK2E0R3RiQkJaNmtkVDJqVGtTUjRwNEZOb3dnNFBuT0w3YVVyQ2pXbmliclRxCjVBdnRVbmVUenhyM1NsZlozcy9BZndLQmdGTm0yZ3pOcXVCREFkcDdRY1JoTXc0aXBlaGZYQWR1VVJQb3NsTEwKVVZtK1hZa044eXQ4aUdRWW9CSmp2amttaVg5SG1VUDBMU3RiSUdjUC9YUC9Xbk9ydXd1d2duRzhPeWVReUxZRApOSEx3Sm9zb3ZMUnZVWHU5WUJNaVlvblk5Z3pNQWk3eklLeUwxZ0k4S01OYUViV21BUlNsVVhKcGxQcG80UCtpCkpGbFpBb0dCQU1QQnFsSk9kQVlpajJnY25lVzFlcEZYMzVZMWQ3a2l0cU1sdlJmcFAzbEs2eVl0NnBveHZIS0oKNUY0b0JaY3gySVl4WGp6em81RURqN3ZLMUZWODNUeEoxTG1uMURXay9UcEpzWlJoSHI5U0hTSjJDT1h6TURHcgpIWVlibFR1Q3lvUjJDU3FaYWk5VzVUMXpQQ2xteTlJTVp4dWhoYmM2TXZtczBuZ2F3Zmg1Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg"
    }`

**Comment by lestrrat** [comment]
Ahh.

You haven't pem-decoded your input. The result of `ioutil.ReadFile` is `[]byte`, and that is interpreted by `jwk.New` as a symmetric key. If you had passed an `"crypto/rsa".PrivateKey` or `"crypto/rsa".PublicKey` to `jwk.New`, it would have created a proper RSA-backed jwk Key.

What you need to do is to take the result of `ioutil.ReadFile`, decode it through `encoding/pem`, and, then use one of `rsa.ParseXXXX` methods to instantiate the proper key. Something like [this](https://gist.github.com/jshap70/259a87a7146393aab5819873a193b88c)

I think that should solve your problem, so I will close this issue. If you think this is still a jwx problem, please re-open. Thanks!

**Comment by JavadHosseini** [comment]
Aaah. It worked. Thanks man!
