### ISSUE TITLE
Allow JWKS-style sources of keys to verify JWT

### ISSUE THREAD

**Issue by imirkin** [lestrrat-go/jwx#196]
The list of keys used to sign JWT may vary over time for a particular identity provider. They provide these at some URL which you're supposed to refresh "every so often", and supply some number of keys, identified by a "kid". This kid is also part of the JWT's header, and you're supposed to verify the JWT signature using the corresponding key. This is all implemented already in jwk.Set.

The rub is that you don't know which key to verify with prior to parsing the header of the JWT.

It's possible to use the Parse function directly as-is, and then separately perform a verify step, but this can be a bit more error prone. Perhaps it'd be possible to define a new WithVerify type of thing which integrates with a jwk.Set.

**Comment by lestrrat** [comment]
Pseudocode / Test code would be most helpful (even if they don't compile) as a way to align our expectations and to start out the design

**Comment by imirkin** [comment]
So ... this isn't optimal, but this is the code I ended up with given the current API's/etc:

	m, err := jws.Parse(strings.NewReader(tokenData))
	if err != nil {
		return err
	}

	headers := m.Signatures()[0].ProtectedHeaders()
	kid := headers.KeyID()
	keys := keySet.LookupKeyID(kid)
	if len(keys) == 0 {
		return fmt.Errorf("kid %s not found", kid)
	}
	key := keys[0]
	var rawKey interface{}
	if err = key.Raw(&rawKey); err != nil {
		return fmt.Errorf("failed to materialize jwk.Key: %v", err)
	}

	_, err = jws.Verify([]byte(tokenData), headers.Algorithm(), rawKey)
	if err != nil {
		return err
	}
	token, err := jwt.ParseString(tokenData)
	if err != nil {
		return err
	}

So it ends up parsing the same token 3x. Something like

    jwt.Parse(data, jwt.WithVerifySet(keySet))

whereby it parses the header, grabs the kid to pick the right key out of the set, and alg from the header (not the key as `jws.VerifyWithJWK` attempts to do) would definitely do the trick. But one could also imagine something more generic. For example https://github.com/dgrijalva/jwt-go provides a callback which receives a parsed header and allows it to return a key to use for verification. With that library, my code looks something like

	token, err := jwt.Parse(tokenData, func (t *jwt.Token) (interface{}, error) {
		kid, ok := t.Header["kid"].(string)
		if !ok {
			return nil, fmt.Errorf("missing kid")
		}
		return keySet.GetSigningKey(kid)
	})

**Comment by lestrrat** [comment]
Thank you! Let me ponder about this for a bit.

**Comment by lestrrat** [comment]
@imirkin Want to take #197 for a spin? I admittedly have committed only a very minimal set of tests, though.

The method you want to use is this:

```
var set *jwk.Set
...
token, err := jwt.Parse(src, jwt.WithKeySet(set))
```

**Comment by imirkin** [comment]
Thanks for this. I will be able to try it out over the next few days.

**Comment by imirkin** [comment]
I was able to test this out, and it seems to work well.

One issue that occurs to me is that with this scheme there's no way to enforce that a non-"none" algorithm is used for the signature (similar theme as issue #189). Otherwise a token could be passed into the service with alg=none and all the key verification stuff goes out the door without the code being aware of it. Ideally you would not allow it by default, and have an option which enables it for the few people that want it?

Perhaps this is only an issue with the keyset, since otherwise an explicit algorithm/key are supplied for verification -- so this would only be applied as part of the new logic that you added? In that case, you can probably just always require it -- doesn't make sense to be passing in a key set and have alg=none tokens.

**Comment by lestrrat** [comment]
That makes sense. I can see a veeeeeery rare case where alg=none is desired for key set verification, so let me think of an API that defaults to disallowing alg=none, while optionally allowing it if explicitly specified.

**Comment by lestrrat** [comment]
meh, actually, you know what. I tested, and currently `jws.Verify` returns an error if `alg: none` is specified, so ... as long as you ask `jwt.Parse()` to verify the token, `alg: none` is disallowed. I'd have to actually create a way to *allow* `alg: none` to even add this functionality :)

So I think it might just be more prudent to leave it as is, unless you have a specific case where `jwt.Parse` (the new version) did not report an error when `alg: none `was specified.

**Comment by lestrrat** [comment]
@imirkin [I added a test that show a mangled header section in the JWT does not actually pass verification](https://github.com/lestrrat-go/jwx/pull/197/files#diff-e6fa89f4cc7abf9b1ed338c3967bfc7fR155) in #197. Please check if we're on the same wavelength there?

**Comment by imirkin** [comment]
Aha, I had thought that verify would just let it through without actually reading the code. You're right - as long as you attempt to verify the signature, it will make sure that alg != none. When/if the use-case for alg=none "verification" presents itself, you can worry about it then.

Thanks so much for this!

**Comment by lestrrat** [comment]
fixed and merged. thank you @imirkin
