### ISSUE TITLE
jwks fetch error in long running process: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full

### ISSUE THREAD

**Issue by ashishs** [lestrrat-go/jwx#200]
**Describe the bug**
We use jwx for fetching jwks from a URL and the validating tokens against the jwks. We refresh the jwks every 600 seconds. 
After running for a few hours and refreshing the token close to 80 times, we get the error below:

`failed to fetch remote JWK: Get \"https://ashishs.us.auth0.com/.well-known/jwks.json\": dial tcp 3.132.73.216:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.","errorVerbose":"Get \"https://ashishs.us.auth0.com/.well-known/jwks.json\": dial tcp 3.132.73.216:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.\nfailed to fetch remote JWK\ngithub.com/lestrrat-go/jwx/jwk.FetchHTTPWithContext\n\td:/a/1/s/gopath/pkg/mod/github.com/lestrrat-go/jwx@v1.0.3/jwk/jwk.go:179\ngithub.com/lestrrat-go/jwx/jwk.FetchHTTP\n\td:/a/1/s/gopath/pkg/mod/github.com/lestrrat-go/jwx@v1.0.3/jwk/jwk.go:159\ngithub.com/lestrrat-go/jwx/jwk.Fetch\n\td:/a/1/s/gopath/pkg/mod/github.com/lestrrat-go/jwx@v1.0.3/jwk/jwk.go`

**To Reproduce / Expected behavior**
The code below gets called every 600 seconds in a goroutine and reloads the jwks.
```
fetchJwks := func() (*jwk.Set, error) {
		jwks, err := jwk.Fetch(config.jwks_uri, jwk.WithHTTPClient(client))

		if err != nil {
			return nil, err
		}
		return jwks, nil
	}
```

goroutine:

```
go func() {
		for {
			time.Sleep(time.Duration(config.jwksRefreshInternal) * time.Second)
			jwks, err := fetchJwks()

			if err == nil {
				authenticator.jwks = jwks
				authenticator.lastRefreshedOn = time.Now()
			} else {
				logger.Errorw("jwks-refresh-failure", "error", err, "url", config.jwks_uri, "lastRefreshedOn", authenticator.lastRefreshedOn)
			}
		}
	}()
```

**Additional context**
The jwks is available at `https://ashishs.us.auth0.com/.well-known/jwks.json`
**Sponsors**
No, not as of now.

**Comment by lestrrat** [comment]
I ran this 200 times and did not encounter any problems.

```go
func TestGHIssue200(t *testing.T) {
  const src = `https://ashishs.us.auth0.com/.well-known/jwks.json`
  var client http.Client
  for i := 0; i < 200; i++ {
    t.Logf("%d", i)
    //    time.Sleep(1 * time.Second)
    _, err := jwk.Fetch(src, jwk.WithHTTPClient(&client))
    if !assert.NoError(t, err, `jwk.Fetch should succeed`) {
      return
    }
  }
}
```

If this was really jwx problem, the most likely culprit would have been not closing `"http.Request.Body()"` after use, but it looks like this has been taken care of.

I'm willing to accept that this could be a jwx problem, but I think you need to diagnose the problem a bit further. Right now I'm suspecting you are staring new goroutines without waiting for the previous ones to close, or some such. If you think jwx is the problem, you really should create an isolated reproducible test case first.

**Comment by imirkin** [comment]
Sounds like the issue is running out of sockets. This is a Windows error message based on some searching. Could try checking that on Linux by reducing the number of file handles allowed to e.g. 100 (ulimit -n 100) and re-running the same test to see if something is forgetting to close something -- could even be library methods.

Probably worth mentioning the version of Go being used.

**Comment by chanced** [comment]
Is `client` a pointer?

```go
	httpcl := http.DefaultClient
	for _, option := range options {
		switch option.Name() {
		case optkeyHTTPClient:
			httpcl = option.Value().(*http.Client)
		}
	}
```

I'm still new to go but that seems like it be the potential cause. If they are passing in a client by value and it is being cast as a pointer then perhaps their initial client isn't being closed?

**Comment by lestrrat** [comment]
No, you can't pass a variable by value and perform type assertion to a pointer.
[Example](https://play.golang.org/p/PaBCym-TZQd)

**Comment by ashishs** [comment]
I can confirm that this was an issue with free sockets running out. 
No further action is necessary.
