### ISSUE TITLE
jwt.ParseBytes(buf, jwt.WithOpenIDClaims()) not work

### ISSUE THREAD

**Issue by westwin** [lestrrat-go/jwx#201]
jwt.ParseBytes, WithOpenIDClaims not work,  the returned token is not openid.Token type.

as you can find in jwt.go, the Parse() just ignores WithOpenIDClaims option
`func Parse(src io.Reader, options ...Option) (Token, error) {
	var params VerifyParameters
	var keyset *jwk.Set
	for _, o := range options {
		switch o.Name() {
		case optkeyVerify:
			params = o.Value().(VerifyParameters)
		case optkeyKeySet:
			keyset = o.Value().(*jwk.Set)
		}
	}
`

**Comment by lestrrat** [comment]
Sounds like a bug! If you could submit a quick test as a PR, it would be immensely helpful

**Comment by lestrrat** [comment]
hmm, looks like I made a bad merge somewhere along the way, because I don't see a test that I thought I wrote. checking...

**Comment by lestrrat** [comment]
@westwin should be fixed in master. Please give it a whirl, so I can cut a release.

**Comment by westwin** [comment]
> @westwin should be fixed in master. Please give it a whirl, so I can cut a release.

I tested as a pass. Please go release it. 

BTW, thanks for your great library.

**Comment by westwin** [comment]
> @westwin should be fixed in master. Please give it a whirl, so I can cut a release.

I tested as a pass. Please go release it. 

BTW, thanks for your great library.

> Sounds like a bug! If you could submit a quick test as a PR, it would be immensely helpful

I will do later, sorry can't for now.

**Comment by lestrrat** [comment]
nah, I added the tests myself, so no need. thanks for checking
