### ISSUE TITLE
There should be jwt.ParseOption and jwt.VerifyOption

### ISSUE THREAD

**Issue by wxdao** [lestrrat-go/jwx#203]
I find it really hard for me at first to understand `jwt.Parse()` only accepts `jwt.WithVerify` & `jwt.WithKeySet` and the rest like `jwt.WithAudience` are all for `token.Verify()`. How am I supposed to know what in those `jwt.Option`s  to be used? Furthermore, naming of `token.Verify()` and `jwt.WithVerify` is a bit confusing. I failed to use them correctly until I jumped into the definitions to actually read the code. Maybe something like `jwt.WithSingleKey` and `token.CheckStandardClaims` could be better?

**Comment by lestrrat** [comment]
Let me break down your comment:

1. How am I supposed to know what in those jwt.Options to be used ....

Documentation. But yes, I can see they could use a lot of improvement. If you have concrete suggestions, please let me know (especially if you expected the definitions to be at one place and couldn't find them there)

2. Naming of token.Verify() and jwt.WithVerify is a bit confusing...

I don't have an opinion there, so if you have a concrete proposal, I can certainly consider it. Please create a pseudocode test case that shows how one would use (or not use) your options.

**Comment by wxdao** [comment]
Thanks for your reply. I will file some MRs soon to better represent my ideas. However I'm not sure how much api change could still happen here since it's already into 1.0 version.

**Comment by lestrrat** [comment]
Adding options should be doable. Changing existing calling conventions not so much. However, it's a proposal so you shouldn't haven to worry too much about backward compat (yet :)
