### ISSUE TITLE
Add support for 'dir' encryption

### ISSUE THREAD

**Issue by anatol** [lestrrat-go/jwx#210]
`clevis` tool uses `dir` encryption mode for some of its use-cases. `jwx` should probably support `dir` as well. The API would look like this:

`msg.Decrypt(jwa.DIRECT, cek)`

**Comment by anatol** [comment]
Following patch seem does the trick. I can decode message encrypted with `jose` dir mode using this patch https://github.com/anatol/jwx/commit/d06d17561d407ea8bcaf9570b34bc43138ed8e28

**Comment by lestrrat** [comment]
note: as of this writing (because of rebasing) above commit ID has changed to 23d7e1c1c028b7ac7c6631af3dbc58e923f59ac9

**Comment by lestrrat** [comment]
fixed by #213
