### ISSUE TITLE
Add integration tests with use of `jose` tool

### ISSUE THREAD

**Issue by anatol** [lestrrat-go/jwx#211]
One thing that would help keeping `jwx` feature-full and compatible with other implementation is to have integration tests that utilize those implementation. The idea here is to generate a key using tools like `jose`, then encrypt a message (again using `jose`) and then try to decrypt it with `jwx`. At the end the plaintext should be exactly the same as input to `jose`.

The test should also verify data flow other way - encrypt a text with `jwx` and then it decrypt using `jose` tool. The end result should match input to `jwx`.

**Comment by lestrrat** [comment]
just letting you know that this hasn't been warnocked. been taking time off for the last week. Will get back when I sort out $day_job :)

**Comment by anatol** [comment]
No worries.

Just a bit more info about this request. We want to run some operation with existing tools like `jose` and then check the result using `jwx`. e.g

```
jose jwk gen -i '{"alg":"A128GCM"}' -o key.jwk
jose jwk thp -i key.jwk
jose jwe enc -I msg.txt -k key.jwk -o msg.jwe
```

generates a key, generates a thumbprint and then encrypts a message. `jwx` should read the key, parse it, check that thumbprint matches, decrypt the message.

We want different types of keys here and check different operations (encrypt/decrypt/sign/verify/..)

And on top of that we want to test the functionality the other way - generate a key and encrypt a message using `jwx` and then decrypt it with `jose`. It will give a pretty good compliance coverage for `jwx`.

**Comment by lestrrat** [comment]
@anatol So I added some basic testing for `jose` tools in #216 

Maybe you can suggest some tests that you want me to include in there?

**Comment by lestrrat** [comment]
closing this as at least some tests have been added.
