### ISSUE TITLE
How do I take a Base64 string JWT token containing 4 parts (3 periods '.') and pass it as a RS256 public key.

### ISSUE THREAD

**Issue by codeliger** [lestrrat-go/jwx#215]
`verified, err := jws.Verify(buf, jwa.RS256, &privkey.PublicKey)`

In the sample code provided a generic interface is required containing a public key.

How do I take a Base64 string JWT token containing 4 parts (3 periods '.') and pass it as a RS256 public key?

There doesn't seem to be a clear way to create a public key struct for RS256.

**Comment by lestrrat** [comment]
This questions is more about how JWT/JWK work, and not necessarily this particular library. 

Usually the public key is provided as a separate entity

For example, Google:

https://developers.google.com/identity/protocols/oauth2/openid-connect#validatinganidtoken

> The tokeninfo endpoint is useful for debugging but for production purposes, retrieve Google's public keys from the keys endpoint and perform the validation locally. You should retrieve the keys URI from the Discovery document using the jwks_uri metadata value. Requests to the debugging endpoint may be throttled or otherwise subject to intermittent errors.

The keys will be available as JWK keys in the url pointed by above jwks_uri (see original doc for the actual link), which you can parse and create a key for using my library.
