### ISSUE TITLE
Verifying JWT

### ISSUE THREAD

**Issue by dtrinh100** [lestrrat-go/jwx#218]
I don't see any examples for verifying a JWT in the examples (besides the signing algorithm and secret), but I see the function in the documentation. Is this the correct way of using it? 

Code to generate token:

```
    t := jwt.New()
    t.Set(jwt.ExpirationKey, time.Now().Add(time.Minute*15).Unix())
```

Code to parse and verify token:

```
    t, _ := jwt.Parse(bytes.NewReader(token))
    _ = jwt.Verify(t)
```

I assume using the `Verify` function here will check to make sure that the token hasn't expired and if it has expired, return an error, is that correct?

**Comment by lestrrat** [comment]
oh oops, I thought I hit the Comment button yesterday, and I apparently didn't.

Yeah, so are/should be correct. `jwt.Parse` and its verify verifies the integrity of the possibly signed payload, but does not verify its contents.
The documentation does not properly reflect the current state of things, and needs to be fixed.

**Comment by lestrrat** [comment]
@dtrinh100 in hindsight, `jwt.Verify` should have been `jwt.Valid()` or something. I may deprecate jwt.Verify and add jwt.Valid

**Comment by lestrrat** [comment]
@dtrinh100 would you say #220 makes a bit more sense than the current state?

**Comment by dtrinh100** [comment]
@lestrrat Yes, that seems good to me. Thanks!

**Comment by lestrrat** [comment]
Thanks. #220 has been merged
