### ISSUE TITLE
Parsing compact jwx and json jwx gives different messages

### ISSUE THREAD

**Issue by anatol** [lestrrat-go/jwx#230]
I am using messages produced/parsed by `jose` tool and compatibility with this tool is needed for me.

One compatibility issue I found is the way how these tools parse compact messages vs json message. See a testcase below that shows the problem.

```go
package tests

import (
	"bytes"
	"os/exec"
	"reflect"
	"strings"
	"testing"

	"github.com/lestrrat-go/jwx/jwe"
)

func TestJwxParse(t *testing.T) {
	data := "eyJhbGciOiJFQ0RILUVTIiwiY2xldmlzIjp7InBpbiI6InRhbmciLCJ0YW5nIjp7ImFkdiI6eyJrZXlzIjpbeyJhbGciOiJFQ01SIiwiY3J2IjoiUC01MjEiLCJrZXlfb3BzIjpbImRlcml2ZUtleSJdLCJrdHkiOiJFQyIsIngiOiJBZm5tR2xHRTFHRUZ5NEpUT2tGWmo5ZEhEUmdpVE5IeFBST3hpZDZLdm0xVGRFQkZ3bElsSVB6TG5lTjlnb3h6OUVGYmJLM3BoN0tWZS05aVF4MmxhOVNFIiwieSI6IkFmZGFaTVYzVzk1NE14elQxeXF3MWVaRU9xTFFZZnBXSGczMlJvekhyQjBEYmoxWWV3OVFvTDg1M2Y2aUw2REIyRC1nbEcxSFFsb3czdGRNdFhjN1pSY0IifSx7ImFsZyI6IkVTNTEyIiwiY3J2IjoiUC01MjEiLCJrZXlfb3BzIjpbInZlcmlmeSJdLCJrdHkiOiJFQyIsIngiOiJBR0drcXRPZzZqel9pZnhmVnVWQ01CalVySFhCTGtfS2hIb3lKRkU5NmJucTZKZVVHNFNMZnRrZ2FIYk5WT0U4Q3Mwd0JqR0ZkSWxDbnBmak94RGJfbFBoIiwieSI6IkFLU0laT0JYY1Jfa3RkWjZ6T3F3TGI5SEJzai0yYmRMUmw5dFZVbnVlV2N3aXg5X3NiekliSWx0SE9YUGhBTW9yaUlYMWVyNzc4Unh6Vkg5d0FtaUhGa1kifV19LCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjM5NDIxIn19LCJlbmMiOiJBMjU2R0NNIiwiZXBrIjp7ImNydiI6IlAtNTIxIiwia3R5IjoiRUMiLCJ4IjoiQUJMUm9sQWotZFdVdzZLSjg2T3J6d1F6RjlGT09URFZBZnNWNkh0OU0zREhyQ045Q0N6dVJ1b3cwbWp6M3BjZnVCaFpYREpfN0dkdzE0LXdneV9fTFNrYyIsInkiOiJBT3NRMzlKZmFQVGhjc2FZTjhSMVBHXzIwYXZxRU1NRl9fM2RHQmI3c1BqNmktNEJORDVMdkZ3cVpJT1l4SS1kVWlvNzkyOWY1YnE0eEdJY0lGWWtlbllxIn0sImtpZCI6ImhlZmVpNzVqMkp4Sko3REZnSDAxUWlOVmlGayJ9..GH3-8v7wfxEsRnki.wns--EIYTRjM3Tb0HyA.EGn2Gq7PnSVvPaMN0oRi5A"

	compactMsg, err := jwe.ParseString(data)
	if err != nil {
		t.Fatal(err)
	}

	var outbuf bytes.Buffer
	// jose jwe fmt -i- -c <<< $data
	cmd := exec.Command("jose", "jwe", "fmt", "-i-")
	cmd.Stdin = strings.NewReader(data)
	cmd.Stdout = &outbuf
	if err := cmd.Run(); err != nil {
		t.Fatal(err)
	}

	jsonMsg, err := jwe.Parse(outbuf.Bytes())
	if err != nil {
		t.Fatal(err)
	}

	if !reflect.DeepEqual(compactMsg, jsonMsg) {
		t.Fatal("messages parsed from json and from the compact form are not equal")
	}
}
```

Parsing a compact form message with `jwx` gives a recipient in `msg.Recipients`. But if I convert it to json form using `jose` and then parse it with `jwx` it does *not* have any recipients. Instead that data ends up under `protectedHeaders` structure.

**Comment by anatol** [comment]
And I cannot convert from json to compact form using `jwx`:

```go
data := `{"ciphertext":"wko","encrypted_key":"","iv":"y-wj7nfa-T8XG58z","protected":"eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoidHBtMiIsInRwbTIiOnsiaGFzaCI6InNoYTI1NiIsImp3a19wcml2IjoiQU80QUlCSTFRYjQ2SHZXUmNSRHVxRXdoN2ZWc3hSNE91MVhsOHBRX2hMMTlPeUc3QUJDVG80S2RqWEZYcEFUOWtLeWptVVJPOTVBaXc4U1o4MGZXRmtDMGdEazJLTXEtamJTZU1wcFZFaFJaWEpxQmhWNXVGZ1V0T0J4eUFjRzFZRjhFMW5Ob1dPWk9Eek5EUkRrOE1ZVWZrWVNpS0ZKb2pPZ0UxSjRIZkRoM0lBelY2MFR6V2NWcXJ0QnlwX2EyZ1V2a0JqcGpTeVF2Nmc2amJMSXpEaG10VnZLMmxDazhlMjUzdG1MSDNPQWk0Q0tZcWFZY0tjTTltSTdTRXBpVldlSjZZVFBEdmtORndpa0tNRjE3czVYQUlFUjZpczNNTVBpNkZTOWQ3ZmdMV25hUkpabDVNNUJDMldxN2NsVmYiLCJqd2tfcHViIjoiQUM0QUNBQUxBQUFFMGdBQUFCQUFJREpTSVhRSVVocjVPaDVkNXZWaWVGUDBmZG9pVFd3S1RicXJRRVRhVmx4QyIsImtleSI6ImVjYyJ9fSwiZW5jIjoiQTI1NkdDTSJ9","tag":"lir7v9YbCCZQKf5-yJ0BTQ"}`

msg, err := jwe.Parse(data)
if err != nil {
	return nil, err
}

compact, err := jwe.Compact(msg)
if err != nil {
	return nil, err
}
```

gives me error `wrong number of recipients for compact serialization`. While `jose` works fine here:

```bash
jose jwe fmt -i- -c <<< '{"ciphertext":"wko","encrypted_key":"","iv":"y-wj7nfa-T8XG58z","protected":"eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoidHBtMiIsInRwbTIiOnsiaGFzaCI6InNoYTI1NiIsImp3a19wcml2IjoiQU80QUlCSTFRYjQ2SHZXUmNSRHVxRXdoN2ZWc3hSNE91MVhsOHBRX2hMMTlPeUc3QUJDVG80S2RqWEZYcEFUOWtLeWptVVJPOTVBaXc4U1o4MGZXRmtDMGdEazJLTXEtamJTZU1wcFZFaFJaWEpxQmhWNXVGZ1V0T0J4eUFjRzFZRjhFMW5Ob1dPWk9Eek5EUkRrOE1ZVWZrWVNpS0ZKb2pPZ0UxSjRIZkRoM0lBelY2MFR6V2NWcXJ0QnlwX2EyZ1V2a0JqcGpTeVF2Nmc2amJMSXpEaG10VnZLMmxDazhlMjUzdG1MSDNPQWk0Q0tZcWFZY0tjTTltSTdTRXBpVldlSjZZVFBEdmtORndpa0tNRjE3czVYQUlFUjZpczNNTVBpNkZTOWQ3ZmdMV25hUkpabDVNNUJDMldxN2NsVmYiLCJqd2tfcHViIjoiQUM0QUNBQUxBQUFFMGdBQUFCQUFJREpTSVhRSVVocjVPaDVkNXZWaWVGUDBmZG9pVFd3S1RicXJRRVRhVmx4QyIsImtleSI6ImVjYyJ9fSwiZW5jIjoiQTI1NkdDTSJ9","tag":"lir7v9YbCCZQKf5-yJ0BTQ"}'
```

cc @npmccallum @sergio-correia

**Comment by lestrrat** [comment]
mostly memo for self: Out of my head it looks like a problem with me recently adding a special case for $number_of_recipients == 1.

**Comment by lestrrat** [comment]
@anatol sorry about the wait, I was hoping I could fix ECDH-ES completely before tackling this, but I just ran out of tuits, so decided to punt #234 and work on this instead.

Turns out yeah, it's a special case where len(recipients) == 0 that I needed to handle on both JSON and Compact serialization formats -- it's mostly internal thing, and didn't really manifest itself until you actually go through both JSON and Compact serializations.

I added tests in both jwx_test.go and jwe/jwe_test.go, which addresses each of your code above. Seems to be working now

**Comment by lestrrat** [comment]
@anatol going to merge this for now. Please holler if you encounter any problems

**Comment by anatol** [comment]
Hi sorry for the delay.

I was trying to update my project to the latest `master` branch changes to verify the parsing fix. But I found that you dropped current ECDH implementation. It is something I use (I implement ECMR on top of ECDH). See my code here https://github.com/anatol/clevis.go/blob/main/tang.go#L21

I guess I need to wait for https://github.com/lestrrat-go/jwx/issues/234. Once `jwx` gets ECDH back I'll test the changes.

**Comment by lestrrat** [comment]
Ugh. I guess I need to reopen the hell gates again :)
But so you're saying the previous implementation of ECDH worked, then? I was pretty sure the output for jose didn't match for jwx -- but if you it worked for your previously, then I must've introduced something new.

**Comment by anatol** [comment]
The previous ECDH worked for me (see https://github.com/anatol/clevis.go/blob/main/tang.go#L21)

**Comment by lestrrat** [comment]
Okay, I'll take a diff with the previous version, and see if it matches first, then redo the check against jose.
IIRC my tests kept working then I tried the jose compatibility, which is when all hell broke loose. anyways, thanks for the info.

**Comment by lestrrat** [comment]
@anatol @imirkin kindly patched things up and all tests are clean now. Can you please take things for a whirl?

**Comment by anatol** [comment]
Thank you for the changes. Quick check shows that ECDH and the original issue are fixed and everything looks good now.
