### ISSUE TITLE
KeyLookup hook to dynamically look up a key (by kid) during the verification phase

### ISSUE THREAD

**Issue by westwin** [lestrrat-go/jwx#231]
current jws signature vefication function needs either a static key or keyset. 

But in cases of the key can not be known before we parse/verify the token. I mean I need to lookup a database to load the key by kid.

A KeyLookup hook might be helpful

**Comment by westwin** [comment]
I submitted a PR, please find https://github.com/lestrrat-go/jwx/pull/232

**Comment by lestrrat** [comment]
I understand the use case, but I think it's a bit naive to assume that the key ID is the only thing that people would need. That is, I can see cases where people would depend on extra non-standard hints embedded in the fields in the message or the signed payload (i.e. "how do I make jwt.Parse to load a key dynamically using x-my-awesome-private-field?")

In that sense this is a hard hook to integrate in the jwt parsing mechanism as a generic way to load keys, as we're dealing with multiple levels of data, i.e. the raw []byte data, the jws signed data, and the jwt token itself.

I won't completely rule out an API that allows one to avoid boilerplate code, but I think what you are proposing is not generic enough.

For the time being, I think the correct way to do this would be:

```go
parsed, _ := jws.Parse(bytes.NewReaer(data))
row, _ = db.QueryRow(`SELECT ... FROM keys WHERE kid = ?`, parsed.KeyID()) // assume keys table contains the key data
key := createKeyFromRow(row) // assume key has all the necessary data
payload, _  = jws.Verify(data, alg, key) // assume key is something like rsa.PublicKey

token := jwt.New()
json.Unmarshal(token, payload)

// optional
... = jwt.Validate(token, ... )
```

**Comment by westwin** [comment]
ok. thanks for your response.

let's close the issue.
