### ISSUE TITLE
Support ECDH-ES

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#234]
I've been pondering about ECDH-ES for a bit, and I know I'm doing something wrong but given my limited tuits, I'm going to disable it and merge whatever else I got at this point.

This issue is for anybody looking for ECDH-ES support:  please look for `XXX For ECDH-ES` in the comments, and uncomment the portion(s) to active the current code, and see if you can debug either the tests or the code.

**Comment by imirkin** [comment]
FWIW I played with this a whole bunch. I noticed that the AlgID was being set wrong (supposed to get set to the content encryption alg), fixed that, but still no good. One thing I noticed is that the "z" value's byte length with P-521 varies between 65 and 66 bytes, while with jose it is *always* 66 bytes. Perhaps that's OK, not sure. jose doesn't do anything special with the value though.

**Comment by imirkin** [comment]
Actually that 65 vs 66 thing may be it. We just take the number of bytes from the big.Int (z.Bytes() ). However jose does:

    len = (EC_GROUP_get_degree(grp) + 7) / 8;
    bn_encode_json(prv, len)

Which makes sense -- the key should be the same length no matter what. This might also explain the inconsistent results in the ECDH-ES+A256KW tests. I'll look into this tonight.

**Comment by imirkin** [comment]
Nooope. Fixed the buffer size, which does make ECDH-ES+A256KW work consistently, but ECDH-ES is still no-go.

**Comment by imirkin** [comment]
Finally figured it out. In direct key agreement mode, there (effectively) is no cek -- it's just generated based on the parameters. So all the cek-generation we do at encrypt time has to be thrown out. I have a change to implement this, just waiting for my other PR to "clear" first.

**Comment by lestrrat** [comment]
Sorry, $day_job's been keeping me busy. Going to merge the other one now
