### ISSUE TITLE
Add RFC 8037 (EdDSA) support

### ISSUE THREAD

**Issue by imirkin** [lestrrat-go/jwx#250]
https://tools.ietf.org/html/rfc8037

This adds some additional curves to be used with ECDH-ES, as well as a new EdDSA algorithm which can be used for signatures.

**Comment by imirkin** [comment]
Looks like ed25519 is in the Go 1.13+ standard library.

golang.org/x/crypto (which is already used for PBES2 support) has a curve25519, which has a X25519 helper.

X448 does not appear to have support by default. There are a couple of implementations of the curve here:

https://pkg.go.dev/github.com/cloudflare/circl/dh/x448
https://pkg.go.dev/gitlab.com/yawning/x448.git

but X448 and Ed448 would need to be implemented on top of those basic primitives. Unclear if it's worth adding dependencies on them to this project.

**Comment by lestrrat** [comment]
No objections to adding support. 

wrt adding libraries, if it seems like overkill there's always the build tag route to make certain libraries optional.

**Comment by imirkin** [comment]
IMO starting with the 25519 curve should be sufficient, and 448 can be added when the standard libraries gain support. It seems like mainstream libraries are just starting to gain support for it, so I expect Go will get a proper implementation eventually.

**Comment by imirkin** [comment]
@lestrrat interesting problem ... so there's a ed25519.Public/PrivateKey type. But there is no curve25519 public/private key type. The way X25519() works is, essentially, a hard-to-reverse multiplication. So there's a "base" point, let's call it "x", and the private key is your number, 'a', and the public key is someone else's private key 'b' times the base point 'x'. And the idea is that a * (b * x) == b * (a * x), and given "a * x" it's hard to compute "a". They do it all in terms of byte slices.

The jwx library sort of depends on there being dedicated types for these. Should I just define some which alias []byte (as ed25519.*Key already do)? Where should those live? In jwk or in jwx directly or ... ?

**Comment by lestrrat** [comment]
I was fooling around with the same stuff earlier, and I think the best way to go about it is to define `jwk.OctetKey` as `type OctetKey []byte`? I haven't gotten as far as actually making them computations, so I'm not sure if that will suffice, but from the RFC it sounded like it.

Also, you probably need to define `jwa.OctetKeyPair` as `"OKP"`, and `jwa.Ed25519` + `jwa.X25519`. Former for signatures and latter for key agreement.

**Comment by lestrrat** [comment]
Oh, and probably `jwa.EdDSA` as a SignatureAlgorithm

**Comment by imirkin** [comment]
Yeah, I've done all that. Ed25519 works just fine. This is about X25519.

**Comment by lestrrat** [comment]
Oh oops, sorry. Let me re-read

**Comment by imirkin** [comment]
FWIW this is what I have so far: https://github.com/imirkin/jwx/commits/eddsa

But I was just planning how to deal with the X25519 stuff for jwe encrypt/decrypt.

**Comment by imirkin** [comment]
I don't think a single "OctetKey" type would work -- we need to know if it's X25519, X448, or some other future to-be-defined scheme. We can guess based on the length, but that's unconvincing and not future-proof. And it still wouldn't let us distinguish between public and private.

Basically public and private are just bytes, and the relationship is that public = X25519(private, Basepoint). But to make all the New() and FromRaw type interfaces work, we need dedicated types for each one, I think.

**Comment by lestrrat** [comment]
I see

**Comment by lestrrat** [comment]
Man, I wish they'd just thrown it in one of the `crypto/` packages.

**Comment by imirkin** [comment]
https://pkg.go.dev/golang.org/x/crypto/curve25519 has the X25519 function, but the concept of "public" and "private" keys is a bit artificial. Although I guess that's the case with ed25519 too? Not 100% sure, didn't look into that one since it was all already there and defined :)

**Comment by lestrrat** [comment]
In that case, why don't we introduce a new package under `jwx/* (curve25519?)` to declare dedicated keys in, and put a fat label that it's a placeholder?

**Comment by imirkin** [comment]
OK, will do.

**Comment by lestrrat** [comment]
I'm going to create a separate issue for X448 and close this one
