### ISSUE TITLE
file-rotatelogs archived?

### ISSUE THREAD

**Issue by imirkin** [lestrrat-go/jwx#264]
@lestrrat I know this is the wrong forum, but I don't know of another way to reach you. It appears you've archived the lestrrat-go/file-rotatelogs repository, but without an update to the README which explains why. Was this by accident, or on purpose? If on purpose, what do you recommend for existing users?

**Comment by lestrrat** [comment]
try my gmail account (which you should be able to easily guess from my handle) if you insist on knowing why.

as for replacements, I don't have anything handy. if you are content on using file-rotatelogs, forking it is probably the way to go
