### ISSUE TITLE
RSA private key Set (KeyUsageKey) wrong type assertion

### ISSUE THREAD

**Issue by steevehook** [lestrrat-go/jwx#270]
### The Gotcha

When trying to use  `Set` method of `jwk.Key` in my case I'm trying something as simple as:

```go
key.Set(jwk.KeyUsageKey, jwk.ForSignature)
```

which results in a weird error which kinda explains itself but I believe it could be corrected:

`could not set sig field for jwk key","error":"invalid value for use key: jwk.KeyUsageType"`

I believe this type of assertion prevails in the project which results in unusable library constants, unless doing specific type convertions

### The Error

The error is returned inside [rsa_gen line - 388](https://github.com/lestrrat-go/jwx/blob/master/jwk/rsa_gen.go#L388)

### Solution

Considering this set method accepts anything and the docs don't cover these intricacies, one must really open up the library to understand how to use it.

Assert for constants like `ForSignature` and `ForEncryption` or plain strings

Again huge thanks for the amazing project, I can spare some time for a PR if y'all let me

**Comment by lestrrat** [comment]
Ah, that must be an artifact from when these constants didn't exist before...

**Comment by steevehook** [comment]
> Ah, that must be an artifact from when these constants didn't exist before...

Let me know if this is a thing. Or you just require clients to be aware of type conversion. Thanks ☺️

**Comment by lestrrat** [comment]
I probably just need to generate the appropriate conversions. a failing test case would be nice, if you already have one handy

**Comment by steevehook** [comment]
> I probably just need to generate the appropriate conversions. a failing test case would be nice, if you already have one handy

I believe a helper would be fit. Like check agains a list of consts or a fallback type. If I got it right

**Comment by lestrrat** [comment]
Not sure exactly what you mean, but currently Set() is generated, so that's what I mean by "I need to generate it"
I assume you don't have a test case handy?

**Comment by steevehook** [comment]
> Not sure exactly what you mean, but currently Set() is generated, so that's what I mean by "I need to generate it"
> I assume you don't have a test case handy?

Aha, I see now. Had a look in Makefile. Ermm, no, I don't really have a test case per say

**Comment by lestrrat** [comment]
@steevehook Please check #271, and check if you it works for you

**Comment by lestrrat** [comment]
fixed #271
