### ISSUE TITLE
EssentialClaims Requires JSON array for aud claim

### ISSUE THREAD

**Issue by hopkinsth** [lestrrat-go/jwx#28]
Due to the way that `EssentialClaims` are parsed from JSON, the `aud` claim must always be an array in the source data. 

For example, this sample app will fail the audience check:

```go
package main 

import "github.com/lestrrat/go-jwx/jwt"
import "fmt"
import "encoding/json"

func main() {
    var claimSet jwt.ClaimSet
    err := json.Unmarshal([]byte(`{
      "ver": 1,
      "jti": "AT.yhqxyRwZa5koTnwWQ8G1QV4s2cGYqApe6s22lLjzqJg",
      "iss": "https://my.issuer.domain",
      "aud": "http://my.audience",
      "iat": 1504131487,
      "exp": 1514678399,
      "cid": "1234",
      "uid": "5678",
      "scp": ["users"],
      "sub": "hopkinsth@gmail.com"
    }`), &claimSet)

  if err != nil {
    panic(err)
  }
  // will print "aud not satisfied" assuming the `exp` time hasn't passed
  fmt.Println(claimSet.Verify(jwt.WithAudience("http://my.audience")))
}
```

On this the JWT RFC says, basically, `aud` can be an array or a string: https://tools.ietf.org/html/rfc7519#section-4.1.3

Planning to file a pull request for a fix later... submitting this partly as a reminder.

**Comment by lestrrat** [comment]
> Planning to file a pull request for a fix later... submitting this partly as a reminder.
:+1: :+1: :+1:

**Comment by lestrrat** [comment]
Closing this as it has been ages since last activity
