### ISSUE TITLE
Verifying a JWS with a JWK without alg should attempt to use the alg from the JWS

### ISSUE THREAD

**Issue by joesiltberg** [lestrrat-go/jwx#280]
I tried verifying a JWS with a JWK that didn't have an alg header parameter ("failed to create verifier" in jws.Verify, due to the algorithm being empty).

Since the alg is optional in the JWK, but not for the JWS, I think we should default to using the algorithm specified by the signature if they key doesn't specify an algorithm.

I could try implementing a PR for this if you agree it should work like that.

Thanks!

**Comment by lestrrat** [comment]
I remember not so long ago there was discussion where malicious players would intentionally leave the "alg" field blank to bypass JWS verification. IIRC believe the explicit nature of the current API is a result of that.

Quick googling lists: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/
(However this is definitely not the original article I read a while back, I'm pretty sure there are others with the same argument)

In light of this I'm pretty hesitant to add what you are asking, but if there's a way to fulfill both the need to avoid the security risk while incorporating what you want to do, I'm all ears.

**Comment by joesiltberg** [comment]
That makes sense, thank you!
