### ISSUE TITLE
[NOTICE] Changes for v1.1.0 (BREAKING CHANGES! PLEASE TEST)

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#295]
Tracker issue for v1.1.0, which is planned to introduce breaking changes. Development is being done in https://github.com/lestrrat-go/jwx/tree/develop/v1.1.0

# Planned Breaking Changes

* [x] Remove all `Parse(io.Reader)`, `ParseBytes([]byte)`, and ~~`ParseString(string)`~~ methods (closes #291)
   * [x] Add `Parse([]byte)` and `ParseReader(io.Reader)` methods
   * [x] Remove `jws.ParseVerify`
* [x] Change` jwk.Set` to a an interface (closes #293)
  * [x] Change API to allow mutation. `Add(jwk.Key)`, `Remove(jwk.Key)`, `Clear()`, etc. (note: treat it as a "set"; don't create lookups, because "kid" is not guaranteed to be there)
  * [x] Fix JSON marshaling
  * [x] `(jwk.Set).LookupKeyID(string)` returns the first `jwk.Key` matching the "kid". If multiple kids are available, use `(jwk.Set).Iterate(context.Context)`
* [x] Remove `jwk.PublicKeyOf(rawKey)`
  * [x] Add `jwk.PublicRawKeyOf(rawKey)`
  * [x] Add `jwk.PublicKeyOf(jwk.Key)`
  * [x] Add `jwk.PublicSetOf(jwk.Set)`
  * [x] Change `(jwk.Key).PublicKey()` to return a `jwk.Key`. Implement it in all applicable key types
  * [x] Make `key.PublicKey()` return a key with all fields (except for those explicitly not allowed) copied from the original key.
* [x] Remove `jws.VerifyXXXX`. 
  * [x] Allow `jws.Verify()` to take a raw key or a `jwk.Key`
  * [x] Add `jws.VerifySet([]byte, jwk.Set)`
* [x] Remove `jwk.FetchXXXX` methods. Only `jwk.Fetch()` remains.
  * [x] Reuse `jwk.Fetch()` from `jwk.AutoRefresh`. 
  * [x] Reclassify `WithHTTPClient()` as `FetchOption`
  * [x] Rename `WithRefreshBackoff()` to `WithFetchBackoff()`
* [x] Add `ReadFile()` to all packages, to read from local file system. On go >= 1.16 , io/fs should be supported, so you could even embed your jwk in your compiled program
* [x] Remove `jws.SplitCompact(io.Reader)` (NEW!)
  * [x] Add `jws.SplitCompact([]byte)`
  * [x] Add `jws.SplitCompactReader(io.Reader)`
* [x] Remove `jws.SignLiteral`
* [x] Change options to `jws.SignMulti`
* [x] Change `jwe.WithPrettyJSONFormat` to `jwe.WithPrettyFormat`, and its return type to `jws.SerializerOption`
* [x] Remove buffer.Buffer

# Miscellaneous

* [ ] switch default branch to main
* Optimizations
   * [x] Optimize (jwk.Set).MarshalJSON  (36% reduction in memory allocation)
   * [x] Optimize (jwt.Token).MarshalJSON
   * [x] Optimize (jws.Header).MarshalJSON
   * [x] Optimize (jwe.Header).MarshalJSON

**Comment by lestrrat** [comment]
I went into a frenzy and implemented everything in a day.
So much for [shooting for April](https://github.com/lestrrat-go/jwx/issues/291).

I guess it's time I stop and take some feedback.

I just want to have some fresh eyes, and to that extent I'm just going to call on some people who have recently contributed to this repository in one form or the other.  I will also ask from my Twitter account if anybody is interested.

So...

@sonard @anatol @imirkin @shaunco @gbolo

If any of you have some spare time, will you please check out the proposed changes in this issue, and the changes in #306? You absolutely do no have to feel obligated to do this for me, but if you do take the time to review, thank you very much in advance.

**Comment by sonatard** [comment]
Congrats v1.1.0 🎉 I'll check it!!
(And I'm @sonatard not @sonard 😂

**Comment by lestrrat** [comment]
@sonatard That was a genuine typo :/

**Comment by gbolo** [comment]
@lestrrat that's a tremendous amount of weekend work, Good job ;)

Can you add me as a code reviewer for #306 ? I already tested the changes in jwks api, I can try to make some time later to test other changes as well and review the code changes.

**Comment by lestrrat** [comment]
@gbolo. Thank you! To explicitly assign you as a reviewer, I need to add you as an explicit collaborator. I just sent an invitation. Can you please check?

**Comment by gbolo** [comment]
> @gbolo. Thank you! To explicitly assign you as a reviewer, I need to add you as an explicit collaborator. I just sent an invitation. Can you please check?

Accepted, thanks.

**Comment by lestrrat** [comment]
Cool. Now, Immagonnagotobed.... brain fried for the day.

**Comment by gbolo** [comment]
> Cool. Now, Immagonnagotobed.... brain fried for the day.

well deserved! I'm just starting out my day (I live in Toronto, Canada)

**Comment by anatol** [comment]
I tested the latest master with my projects (that depend a lot on interoperability with `jose` C library) and things look good so far.

@lestrrat thank you for your hard work!

**Comment by lestrrat** [comment]
@anatol Thanks! But unfortunately, the branch I wanted you to review was https://github.com/lestrrat-go/jwx/tree/develop/v1.1.0 :D

Master is basically the same as v1.0.8. The above tree contains a LOT of breaking changes

**Comment by lestrrat** [comment]
repost from the PR

> Okay, I'm done with the API changes.
>
> I deleted all of the gunk that accumulated over the years, standardized the API where I could/should, and I think overall the API reads much easier than before. Yeah, it's still a clutter(bleep) but such is the JWx  specifications...
>
> The list of changes so far can be found in either #295 or the Changes file (as of 6e40439)
>
> I'm going to sit on this until at least February 2021. Meanwhile if there should be any new features for v1.1.0, please let me know

**Comment by anatol** [comment]
D'oh sorry I missed it.

For `clevis.go` project I had to make following changes:

```patch
@@ -173,14 +173,17 @@ func DecryptTpm2(msg *jwe.Message, clevisNode map[string]interface{}) ([]byte, e
                }
        }
 
-       keys, err := jwk.ParseBytes(unsealed)
+       keys, err := jwk.Parse(unsealed)
        if err != nil {
                return nil, err
        }
        if keys.Len() != 1 {
                return nil, fmt.Errorf("clevis.go/tpm2: expected to have 1 key in unsealed data, got %v", keys.Len())
        }
-       key := keys.Keys[0]
+       key, ok := keys.Get(0)
+       if !ok {
+               return nil, fmt.Errorf("clevis.go/tpm2: unable to get a key with index 0")
+       }
        symmKey, ok := key.(jwk.SymmetricKey)
        if !ok {
                return nil, fmt.Errorf("clevis.go/tpm2: unsealed key expected to be a symmetric key")
```

And the tests pass.

**Comment by lestrrat** [comment]
@anatol thanks, I assume those changes weren't that much of a hassle to make. :D

**Comment by anatol** [comment]
Not at all. The changes are straightforward and documented in the `Changes` file.

**Comment by sonatard** [comment]
I was able to compile it with the following changes.

```diff
-func GoogleJWK(ctx context.Context, httpClient *http.Client) (*jwk.Set, error) {
+func GoogleJWK(ctx context.Context, httpClient *http.Client) (jwk.Set, error) {
        const googleJWKSURIV3 = "https://www.googleapis.com/oauth2/v3/certs"

-       key, err := jwk.FetchHTTPWithContext(ctx, googleJWKSURIV3, jwk.WithHTTPClient(httpClient))
+       key, err := jwk.Fetch(ctx, googleJWKSURIV3, jwk.WithHTTPClient(httpClient))
        if err != nil {
                return nil, xerrors.Errorf(": %w", err)
        }
@@ -34,9 +34,9 @@ func GoogleJWK(ctx context.Context, httpClient *http.Client) (*jwk.Set, error) {
        return key, nil
 }

-func VerifyIDToken(keySet *jwk.Set, tokenBytes []byte, audience, email string, now time.Time) error {
+func VerifyIDToken(keySet jwk.Set, tokenBytes []byte, audience, email string, now time.Time) error {
-       jwsPayload, err := jws.VerifyWithJWKSet(tokenBytes, keySet, nil)
+       jwsPayload, err := jws.VerifySet(tokenBytes, keySet)
        if err != nil {
                return xerrors.Errorf(": %w", err)
        }
```

**Comment by lestrrat** [comment]
@sonatard thanks! BTW *if* you are calling that `GoogleJWK()` function multiple times during the lifecycle of your program, this is when `jwk.AutoRefresh` would come in handy :)

**Comment by sonatard** [comment]
That's good!!  know Google library provides jwk cache and refetch. I had a TODO about implementing the cache. But I need no do it thanks to your v1.10!!

Thanks!!

**Comment by shaunco** [comment]
Sorry for the delay. I finally had a chance to look through this and it all looks really good!
