### ISSUE TITLE
package github.com/lestrrat-go/backoff/v2: no Go files

### ISSUE THREAD

**Issue by gsafcik** [lestrrat-go/jwx#315]
**Describe the bug**

In Docker, I can no longer build (as of Mon, Jan 25, 2021) because the package fails to install the `github.com/lestrrat-go/backoff` correctly.

**To Reproduce / Expected behavior**

To reproduce:

I'm using `RUN go get -d -v ./...` to retrieve `github.com/lestrrat-go/jwx` - which should correctly retrieve its dependencies. **NOTE:** I'm using Go 1.15 Alpine as base (`FROM golang:1.15-alpine`).

```bash
[...clipped...]
github.com/lestrrat-go/jwx (download)
github.com/lestrrat-go/backoff (download)
package github.com/lestrrat-go/backoff/v2: no Go files in /go/src/github.com/lestrrat-go/backoff/v2
github.com/lestrrat-go/httpcc (download)
github.com/pkg/errors (download)
github.com/lestrrat-go/iter (download)
[...clipped...]
```

A straight run, just for the `github.com/lestrrat-go/jwx` package, on the CLI produces the same results for me:

```bash
$ go version
go version go1.15.7 darwin/amd64
$ go get -d -v github.com/lestrrat-go/jwx/...                    
github.com/lestrrat-go/jwx (download)
github.com/lestrrat-go/option (download)
github.com/pkg/errors (download)
package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)
github.com/lestrrat-go/backoff (download)
package github.com/lestrrat-go/backoff/v2: no Go files in /Users/<redacted>/go/src/github.com/lestrrat-go/backoff/v2
[...clipped...]
```

**Additional context**

I've also tries using the above commands with the update flag (`-u`) but it accomplishes nothing.

Looking in that dir (locally) I see the following:

```bash
l /Users/<redacted>/go/src/github.com/lestrrat-go/backoff/v2/
total 8
drwxr-xr-x   3 <redacted> 812793394    96B Jan 25 10:45 .
drwxr-xr-x  26 <redacted>  812793394   832B Jan 25 10:45 ..
-rw-r--r--   1 <redacted>  812793394   525B Jan 25 10:45 Makefile
```
_(which matches the [remote repo](https://github.com/lestrrat-go/backoff/tree/main/v2))_

It looks like the "Move files to root" commit (https://github.com/lestrrat-go/backoff/commit/586c83e3028ca6240ecae8e65496e98d7474f9e0) on the Backoff package may be causing this. 

This all was working as of Fri, Jan 24th 2021. ¯\_(ツ)_/¯

**Comment by lestrrat** [comment]
This should Just Work (or so I've been told) if you have a correct go.mod that points to a correct commit / tag. But hmmm.

BTW I intend to "fix" this the best way we can, but the intention is for users to migrate over to v2. Should I have communicated this better? Yes. Did I expect I needed communication? No, because again, I expected it to Just Work, given a proper go.mod. 

Anyway, going to poke in jwx first...

**Comment by lestrrat** [comment]
At first try, I couldn't reproduce, but it may be local caches, etc. Still trying, but meanwhile, FYI my work log:
 
 I'm at
 
 ```
 lestrrat@finch jwx % git show 
commit a559c27e1c5641e51c22762905e3971b808b317f (HEAD -> master, origin/master, origin/HEAD)
Merge: 0db4351 d57279f
Author: lestrrat <49281+lestrrat@users.noreply.github.com>
Date:   Tue Jan 19 07:27:26 2021 +0900

    Merge pull request #307 from lestrrat-go/topic/fix-usage
    
    Fix KeyUsage.Accept

lestrrat@finch jwx % 
```

go.mod

```
lestrrat@finch jwx % cat go.mod
module github.com/lestrrat-go/jwx

go 1.13

require (
	github.com/lestrrat-go/backoff/v2 v2.0.3
	github.com/lestrrat-go/codegen v0.0.0-20210115164254-686308008f83
	github.com/lestrrat-go/httpcc v0.0.0-20210101035852-e7e8fea419e3
	github.com/lestrrat-go/iter v0.0.0-20200422075355-fc1769541911
	github.com/lestrrat-go/option v0.0.0-20210103042652-6f1ecfceda35
	github.com/lestrrat-go/pdebug/v3 v3.0.0-20210111091911-ec4f5c88c087
	github.com/pkg/errors v0.9.1
	github.com/stretchr/testify v1.6.1
	golang.org/x/crypto v0.0.0-20201217014255-9d1352758620
	golang.org/x/mod v0.4.1 // indirect
	golang.org/x/tools v0.0.0-20210114065538-d78b04bdf963
)
```

a casual `go test` without doing anything extra.

```
lestrrat@finch jwx % go test
PASS
ok  	github.com/lestrrat-go/jwx	1.601s
lestrrat@finch jwx % 
```

**Comment by lestrrat** [comment]
`go help clean` shows me this

```
<snip>
The -modcache flag causes clean to remove the entire module
download cache, including unpacked source code of versioned
dependencies.
</snip>
```

Seems promising. Let's try:

```
total 0
drwxr-xr-x  3 lestrrat  staff   96  1 26 10:12 cache
drwxr-xr-x  7 lestrrat  staff  224  1 26 10:12 github.com
drwxr-xr-x  3 lestrrat  staff   96  1 26 10:12 golang.org
drwxr-xr-x  3 lestrrat  staff   96  1 26 10:12 gopkg.in

lestrrat@finch jwx % go clean -modcache -x
rm -rf /Users/lestrrat/dev/pkg/mod
lestrrat@finch jwx % 

lestrrat@finch jwx % ls -l /Users/lestrrat/pkg/mod
ls: /Users/lestrrat/pkg/mod: No such file or directory
lestrrat@finch jwx % 
```

Okay, so everything under pkg/mod should be nuked. Let's try running `go test`, but with `-x` so we can see what it's doing

```
lestrrat@finch jwx % go test -x
<snip>
# get https://proxy.golang.org/github.com/lestrrat-go/backoff/v2/@v/v2.0.3.mod
<snip>
# get https://proxy.golang.org/github.com/lestrrat-go/backoff/v2/@v/v2.0.3.mod: 200 OK (0.254s)
<snip>
go: downloading github.com/lestrrat-go/backoff/v2 v2.0.3
# get https://proxy.golang.org/github.com/lestrrat-go/backoff/v2/@v/v2.0.3.zip
<snip>
# get https://proxy.golang.org/github.com/lestrrat-go/backoff/v2/@v/v2.0.3.zip: 200 OK (0.138s)
$WORK/b001/jwx.test -test.paniconexit0 -test.timeout=10m0s
PASS
<snip>
ok    github.com/lestrrat-go/jwx  1.798s
rm -r $WORK/b001/
```

Okay, so go test is definitely downloading something, and producing the expected results.

@gsafcik I think we may need figure out what's different in our environments. I'm using go1.16beta1, I have not GOPROXY set, I'm running on a M1-chip MBP, and everything is pretty much vanilla.

Also, maybe running the commands with `-x` tell you where things are going wrong?

**Comment by Warashi** [comment]
I reproduced the problem.

put Dockerfile below and do `docker build .`
```
FROM golang:1.15-alpine
RUN apk update && apk add git
RUN go version
RUN go get -d -v github.com/lestrrat-go/jwx/...
```

the cause is that go is running in GOPATH mode

**Comment by lestrrat** [comment]
Unfortunately I don't have a docker environment right now as I'm running on a M1 mac, but am I right in reading that @gsafcik  needs to use go.mod?

i.e., suppose you were doing

```
git clone git@github.com:gsafcik:awesomecode
cd awesomecode # no go.mod
go build ...
```

and instead, (1) set it up once

```
git clone git@github.com:gsafcik:awesomecode
cd awesomecode
go mod init
git add go.mod go.sum
git commit -a
git push ...
```

then (2) build it?

```
git clone git@github.com:gsafcik:awesomecode
cd awesomecode
go build ... # now uses go.mod
```

**Comment by gsafcik** [comment]
@lestrrat Thank you for your quick response. I didn't look before but I guess we are on the opposite side of the world. Also, thank you for creating/maintaining a great lib :)

You and @warashi are correct. We are currently running in GOPATH mode (no `go.mod`). We do have plans to upgrade all our services to use Go modules but it wasn't slated yet as it was deemed a lower priority. Since this affects a multitude of services for us, I can put a request in to make the move to Go modules a more urgent need.

However, if you add the files back to the `v2` directory in `main`, that would allow for the GOPATH mode to work (as @Warashi already suggested). Is that something you're willing to do (make compatibility for GOPATH mode) in the short term?

**Comment by lestrrat** [comment]
> Is that something you're willing to do

I figured it's time for the world to move on, and the duplication was a serious maintenance headache that I've been fighting ever since I started using v2 in my modules. So if I can get away with it, I'd rather not. 

Let me just ask you one more time if you (I guess your organization, rather) if it's possible to workaround things? i.e., add an extra step or two in your build process, such as copying files over or some such? if your bureaucracy doesn't even allow that, I'm going to fallback to adding files back -- but seriously, fielding questions suddenly becomes tough when you have multiple sources of truth in the form of v0/v1 and v2,v3,...VN source codes and combine it with users who don't read the fine print (which is the norm), so I want to avoid it at all costs.

( I meant to suggest a workaround here, but I'm still trying to setup an environment where I can reproduce your problems and it's taking time, so skipping that part for now)

**Comment by lestrrat** [comment]
Meanwhile I'm setting up an environment where I can test things

**Comment by lestrrat** [comment]
Okay, I fired docker on GCP, and tested that the following works on golang:1.15-alpine

```shell
#!/bin/sh

set -e
set -x
BACKOFFPATH=github.com/lestrrat-go/backoff

go get -d $BACKOFFPATH
cp $GOPATH/src/$BACKOFFPATH/*.go $GOPATH/src/$BACKOFFPATH/v2
go get -d github.com/lestrrat-go/jwx/...
```

```
% sh ./workaround.sh
```

Is it possible for you to insert that bit in your workflow?

**Comment by gsafcik** [comment]
@lestrrat 

> Let me just ask you one more time if you (I guess your organization, rather) if it's possible to workaround things? i.e., add an extra step or two in your build process, such as copying files over or some such?

I totally understand what you're saying and appreciate your time! I will try my best to work around it.

> Okay, I fired docker on GCP, and tested that the following works on golang:1.15-alpine

I just saw this come in and will give it a shot!

**Comment by gsafcik** [comment]
@lestrrat Thank you for your help! That worked. Closing issue.

**Comment by lestrrat** [comment]
@gsafcik sorry, I decided to remove the leftover junk (v2/Makefile) in backoff, so you might need to actually call `mkdir v2` before copying files over in that workaround above. FYI.
