### ISSUE TITLE
RSA/RS512 with x5c fails to parse

### ISSUE THREAD

**Issue by AkselsLedins** [lestrrat-go/jwx#316]
Hello and first thanks for your awesome work @lestrrat 

We are successfully using your library to parse a set of JWK. But now we are trying to use another authentication provider with another set and we are encountering an issue.

Here is the JWKS:
```
{
  "keys": [
    {
      "kid": "CAS-VENDOR",
      "kty": "RSA",
      "alg": "RS512",
      "use": "sig",
      "x5c": [
        "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2wXOtiRfl4Y30vo9sgt18hkk0Gtm3regJLBegmR0y795VMvd3+7xBswGG+YSKls68hcBnaGr8elzBkfbsBlMBFjPmmI6UWHAv7gDkEaa20A1VRC6B1/sQP3jbZud6xZSOsucrnXP8CLM9HrcjH81UAR7aQxooWzD5fMgthiO3uDempga19FEJvAKna6xN3qrnQme7DKfbc8s+E0U7TwRdDpLYBiA0/wLDw92svPTG2QuIN+jRdsgApMDKVq0ufEhvlYrhReNnydF61qhzBi97CQ/jJ9DeqUfn9DdtY5IWBy6ecGVvo+6AAdOSfegA3qs93PWxIJKsEYIEuqbN6ODJixP9RTkm3VuODBo2HDeNnfNCURk1BnsH12RFvYkx6bfHBwQ/bmiUBmHV1vD5IXv/3YXAtfmVh3m4mHOkq+065eqMHq5SRDGf6B7xD9SW+hCbPsUvaa/KBKUsR+/vMPo6k5PqF+PhkD26/bsk4CvIxCCEqx+hqXdJNVNN7nn8Fx5gPBs2VW3YSMwe0oWH/98IxfUG+WEic2fhQMrkzXc9Di5ydxDRPnm6cc98FPbu/mv+845w3r/whzPes5/0GyIDXSfHXPukhXehb0KT3foeHCUDBY7JL9usLf9e+8inU2i3zhbvRPPZFjeQlf43jAah+4JpjLXHl6jKG3QGcH/WCMCAwEAAQ=="
      ]
    }
  ]
}
``` 

We tried multiple approaches but here is a code snippet that fails:

```
keyFileName := "./set.json"

r, err := os.Open(fmt.Sprintf("./jwks/%s", keyFileName))
if err != nil {
  o.logger.WithFields(logrus.Fields{"file_name": keyFileName, "error": err}).Error("unable to open file")
  return nil, err
}

set, err := jwk.Parse(r)

if err != nil {
  fmt.Printf("parse failed: %s\n", err.Error())
}
``` 

and here is the output

```
parse failed: failed to unmarshal key #1 (total 1) from multi-key JWK set: failed to unmarshal JSON into key (*jwk.rsaPublicKey): failed to unmarshal rsaPublicKey: failed to parse certificate: asn1: structure error: tags don't match (2 vs {class:0 tag:6 length:9 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @2 
```

We tried using `jwk.Parse` and `jwk.FetchHTTP` resulting in the same issue.
Any help would be really appreciated. 

Thanks a lot!

Edit:
using version v1.0.8 of the library

**Comment by lestrrat** [comment]
Did you generate the x5c content yourself?

The error message says it all, really... the content isn't valid, and can't be parsed via
>     cert, err := x509.ParseCertificate(buf)

**Comment by lestrrat** [comment]
Now, it's entirely possible that I'm missing a particular case where x5c can be something other than a `*x509.Certficiate`, I need to know what that content is supposed to be :)

**Comment by AkselsLedins** [comment]
I did not generate the content myself, let me triple check with the team behind that JWKS and I'll get back to you asap

**Comment by AkselsLedins** [comment]
Thanks for your patience and your reactivity @lestrrat,  
Turns out the team behind the generation of the token is using the public key PEM in the x5c instead of using a certificate containing the key! Sorry :pray:
