### ISSUE TITLE
parsePEMEncodedRawKey should support block type of CERTIFICATE

### ISSUE THREAD

**Issue by shaunco** [lestrrat-go/jwx#350]
**Abstract**
`jwk.parsePEMEncodedRawKey()` should support x509 certificates that use a block type of `CERTIFICATE` via `x509.ParseCertificate()`

**Describe the proposed solution/change**
```go
	case "CERTIFICATE":
		cert, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			return nil, nil, errors.Wrap(err, `failed to parse X509 certificate`)
		}
		return cert.PublicKey, rest, nil
```

**Analysis**
Currently, the caller must do their own `pem.Decode()` and `x509.ParseCertificate()`, then they can pass the `PublicKey` field to `jwk.New()`. Would be nice to have the convenience function.

Would also be nice if this filled in the `kid`, `x5t`, and `x5c` params, as I'm reading a bunch of certs from Hashicorp Vault to generate a JWKS and then using `json.Marshal` to marshal that JWKS to json to serve it via `/.well-known/jwks.json` over http... but I can keep adding these manually.

**Comment by lestrrat** [comment]
This is sort of meta, but does it make sense when you see a code like `jwk.Parse(x509cert, jwk.WithPEM(true))` ? It may just be me, but I kind of never registered a x509 certificate as a "key", so it looks a bit weird to me. I dunno. I admit I'm not an expert dealing with certs. I'm not saying no, but it was just something that felt odd to me.

wrt `kid`, `x5t`, and `x5c` it might be faster if you send me test cases, your code/pseudocode, or a PR?

**Comment by lestrrat** [comment]
So I asked a couple of people and Twitter, certs = key it is then.

**Comment by lestrrat** [comment]
@shaunco So I just jotted your proposed change here https://github.com/lestrrat-go/jwx/tree/topic/issue-350
Would be nice if you could provide testcases and what not.

**Comment by shaunco** [comment]
Sorry for the delay. On the cert = key question, a cert is just the public key with some additional (useful) metadata. From a JWK perspective, a JWKS is a collection of certs where the metadata and public key are in json/der/base64 formats instead of X509 format.

I'll work on some test cases this weekend.

**Comment by lestrrat** [comment]
I went ahead and merged the ability to parse certificates in ASN.1 DER / PEM format.
I'm going to close this ticket for now. For the rest of your issues, please open a new issue!
