### ISSUE TITLE
RFC: Are you depending on github.com/pkg/errors?

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#370]
In a separate library that I maintain, I have been gently prodded to use %w to wrap errors.
I suppose this is fine, but if I do this to jwx, and if there is anybody using `"github.com/pkg/errors".Is` or some such, this will inadvertently cause problems, so I should probably wait until a major release.

Comments?

**Comment by lestrrat** [comment]
So far I think the answer is no. At some point I'm probably going to ditch github.com/pkg/errors in favor of native wrapped errors.

**Comment by yaliv** [comment]
Hi @lestrrat
Do you have a plan to make this library compatible with TinyGo?

I tried to use it with TinyGo, the target is "wasm", but it failed to build.
github.com/pkg/errors depends on Go's runtime: https://github.com/pkg/errors/blob/v0.9.1/stack.go
I got these errors:
```
# github.com/pkg/errors
... /pkg/mod/github.com/pkg/errors@v0.9.1/stack.go:28:16: fn.FileLine undefined (type *runtime.Func has no field or method FileLine)
... /pkg/mod/github.com/pkg/errors@v0.9.1/stack.go:39:16: fn.FileLine undefined (type *runtime.Func has no field or method FileLine)
```

**Comment by lestrrat** [comment]
@yaliv no I didn't. but if you want to setup a Github workflow so tinygo can be tested, I can certainly take a look

also, this issue has nothing todo with tinygo. please refrain from mixing other content

**Comment by lestrrat** [comment]
No comments in the last three months, so whatever next major version will ship with ``fmt.Errorf(`%w`)`` instead of ``errors.Wrap()``
