### ISSUE TITLE
nbf is not checked for the equality

### ISSUE THREAD

**Issue by k-okov-idt** [lestrrat-go/jwx#378]
Hello!
I've noticed that when calling `Validate()` on token and both `nbf` and `time.Now()` have identical value to seconds, validation fails.
All due to the check:
```
// now cannot be before t, so we check for now > t - skew
	if !now.After(ttv.Add(-1 * skew)) 
```
In the closeup of the After():
```
ts := t.sec()
us := u.sec()
return ts > us || ts == us && t.nsec() > u.nsec()
```

Being cut to seconds, `After` would return false and would lead to an error.
But in general, those values appear to be the same and validation should be successful, shouldn't it?
Thanks

**Comment by lestrrat** [comment]
Ah, you mean  if t1 and t2 are the same, `t1.After(t2.Add(0))` (`0` being the result of `skew = 0`, which of course means `t2.Add` is a no-op) returns false? Sounds about right. Can you please create a failing test case?

**Comment by k-okov-idt** [comment]
Yes, Basically when the `nbf` value is equal to the timestamp of `time.Now()`.

For example, if you define a custom clock that would be returning the same value as `nbf`. In such case, it would be expected to pass validation since those are equal when in fact it would fail

**Comment by lestrrat** [comment]
Right, so can you please create a failing test case, and send it as a PR?

**Comment by lestrrat** [comment]
Okay, I just merged what I /believe/ to be your fix. If it doesn't fix your problems, please send in a test case. Thanks!
