### ISSUE TITLE
[jwt] The key's algorithm should be used when WithKeySet() is specified

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#380]
from #375

**Comment by lestrrat** [comment]
fixed in #381

**Comment by konradmalik** [comment]
Hi, @lestrrat  are you sure this is a good approach?
While safer in terms of security, this renders it impossible to validate Microsoft oauth2 tokens for example (or I'm missing some workaround how to use the old behavior?).

Microsoft does not include `alg` in the key's header. See here: 
https://login.microsoftonline.com/common/discovery/v2.0/keys

And it has all the rights to do so, as this key is **optional** as per RFC:
https://datatracker.ietf.org/doc/html/rfc7517#section-4.4

**Comment by blankdots** [comment]
the `alg` key is also `OPTIONAL` in the spec https://datatracker.ietf.org/doc/html/rfc7517#section-4.4 
i get `failed to find matching key for verification: invalid signatre algorithm : invalid jwa.SignatureAlgorithm value` when using `WithKeySet` if `alg` key is missing

**Comment by lestrrat** [comment]
@blankdots Please read the section starting "The rationale for requiring... " https://github.com/lestrrat-go/jwx/issues/395#issuecomment-861061925

Also, "On this note I think that the RFC is flawed" may be of importance.

**Comment by lestrrat** [comment]
Also https://github.com/lestrrat-go/jwx/blob/main/docs/99-faq.md#why-dont-you-automatically-infer-the-algorithm-for-jwsverify-

**Comment by blankdots** [comment]
@lestrrat thx. i read the changelog in the meantime and got the information i needed, but what you provided helped as well. 

I think i might have an idea how to better handle that on my code as well.
