### ISSUE TITLE
Question: How to add additional headers when using jws.Sign

### ISSUE THREAD

**Issue by fvbock** [lestrrat-go/jwx#386]
I am creating a JWS with `buf, err := jws.Sign(data, jwa.HS256, []byte(Secret))` and want to set an additional header `typ`.

`Sign` takes additional options but a naive `opt := option.New(jws.TypeKey, "JWT")` or `opt := option.New("typ", "JWT")` did not do it. 

How would I set the additional header - or would I have to use `jws.NewMessage()...`?

Thanks for the great library!

**Comment by lestrrat** [comment]
Hey there @fvbock :)

Untested for this specific case, but I think this works?

```go
hdrs := jws.NeaHeaders()
hdrs.Set("typ", "JWT")

jws.Sign(token, alg, key, jwt.WithHeaders(hdrs))
```

**Comment by fvbock** [comment]
Hi @lestrrat :) 

Hm nope. No Error but also no `typ` header - just `alg`

**Comment by lestrrat** [comment]
Weird, should work. I'll write up some code, but can you also show me how you verified it?

**Comment by fvbock** [comment]
I just pasted the signature into jwt.io ;)

which decodes the headers as 

```
{
  "alg": "HS256"
}
```

**Comment by lestrrat** [comment]
That's the dump of the JWT itself. `jws.WithHeaders` adds headers to the JWS message.
If you want to add type to JWT, use `token.Set("typ", "JWT")`

**Comment by lestrrat** [comment]
(I kind did a 脊髄反射 but I hope I'm right) Let me know if I'm just being stupid.

**Comment by fvbock** [comment]
not sure i understand ;-P

the signature gets created with the headers from `jws.WithHeaders` 

https://github.com/lestrrat-go/jwx/blob/main/jws/jws.go#L97-L98

and then those should get merged and json marhalled into the header no?

https://github.com/lestrrat-go/jwx/blob/main/jws/message.go#L54-L72

**Comment by lestrrat** [comment]
My assumption is that jwt.io does this:

```
jws encoded message -> verify signature, get JWT out of it -> display JWT
```

So that means that the result you are telling me should be the content of the JWT.

Therefore I'm thinking this should work:

```go
token := jwt.New()
token.Set("typ", "JWT")
signed, _ := jws.Sign(token, alg, key)
// use signed in jwt.io
```

`jws.WithHeaders` adds header values into the JWS protected headers section, IIRC.
a JWS message in compact form has "protected headers", "payload", "signature" components, so it should be added to the "protected headers". I believe jwt.io is displaying the payload section, which is the JWT.

**Comment by fvbock** [comment]
ok. this does what i wanted. setting the public header

```
sig := jws.NewSignature()
sig.SetPublicHeaders(hdrs)
var signer jws.Signer
if signer, err = jws.NewSigner(jwa.HS256); err != nil {
	return
}

if _, signature, err = sig.Sign(data, signer, []byte(Secret)); err != nil {
	return
}
```

am doing something stupid?

**Comment by lestrrat** [comment]
Ah, okay, IIRC, compact format doesn't really support "public" headers. I think we don't even use the `jws.Signature` struct when encoding?

Anyways, there is always I possibility that I have overlooked this detail, so if you find this to be the case, please let me know
