### ISSUE TITLE
Enforce max valid time jwt policy

### ISSUE THREAD

**Issue by bloritsch** [lestrrat-go/jwx#393]
**Abstract**

As an additional protection to ensure the JWTs comply with policies for a set of microservices, I would like to require the existence of expiration and issued at headers, as well as enforcing a maximum difference between the two.  As an example if I have a policy that all JWTs must have an expiration and the delta between "iat" and "exp" must not be more than 10 minutes, I can add additional protections from invalid configurations.

The real protection I want is a "maxValidTime()".  This is the delta between "iat" (or "nbf") and "exp" claims.  The implied validation is that either "iat" or "nbf" must exist and that "exp" exists.

**Describe the proposed solution/change**

Ideally, we would add a "WithMaxValidTime" validation option

```
err = jwt.Validate(token,
	jwt.WithAudience("pmbob"),
	jwt.WithIssuer("hrbob"),
	jwt.WithAcceptableSkew(2 * time.Second),
	jwt.WithMaxValidTime(10 * time.Minute))
if err != nil {
	createError(NotAuthorized{Cause: err}).write(w)
	return
}
```

The calculation would be taking the start time ("iat" or "nbf" claim) from the expiration time "exp".
The implied requirement is that if the following claims do not exist, the validation fails:

* "iat" claim or "nbf" claim.
* "exp" claim

If both "iat" and "nbf" are supplied the greater of the two are used as the start time.  If the duration is larger than specified, fail the validation:

    (expiration - start) <= maxValidTime

(acceptable skew applies to the calculation)

**Analysis**
I can perform this separately in this way:

```
iat, iatOk := token.Get("iat")
exp, expOk := token.Get("exp")

if !iatOk || !expOk || exp.(time.Time).Sub(iat.(time.Time)) > 10 * time.Minute {
	createError(NotAuthorized{
		Cause: errors.New("invalid token spec"),
	}).write(w)
	return
}
```

However, if I can express the same thing in one line, it would be much more convenient.

**Additional context**
While "forever" tokens are convenient for testing, they are a significant security risk.  A forever token is one that has no expiration date, so you can use it forever.  I want to prevent their use within my system.  The current validations do not prevent the use of a forever token.

In my scenario, I tend to have short expirations on a session token (one presented to my microservice), but a longer-term refresh token to provide the appearance of a longer session.  When the session token expires, the Single Page App (SPA) will exchange the refresh token for a new session token.  This allows me to add or revoke privileges within minutes of the actual assignment.

**Comment by bloritsch** [comment]
NOTE: when testing this out, I was surprised that `token.IssuedAt()` returns the epoch if there is no value.  That forced me to edit my workaround logic.  Since `token.IssuedAt()` == `token.Expiration()` == epoch if those values don't exist, I had a false positive until changing to use the `Get()` methods.

**Comment by bloritsch** [comment]
Also, I would also be quite satisfied if there was a way to require "iat" and "exp" to exist.

**Comment by lestrrat** [comment]
I don't have much time this week, so I only briefly read your issue, however, I understand there may be cases where we could default to more security. I would appreciate it if you could provide a PR with failing test cases in `jwt/jwt_test.go`

**Comment by lestrrat** [comment]
So I had some time, and I tried guessing what you wanted.
Without an actual test case I can't be sure if this is what you want, though

```go
jwt.Validate( ...., jwt.WithMinDelta(10*time.Second, jwt.ExpirationKey, jwt.IssuedAtKey))
```

See the code here
https://github.com/lestrrat-go/jwx/pull/399

**Comment by bloritsch** [comment]
That's perfect.  I'm sorry I couldn't contribute directly.  It was in my long list of todos.

**Comment by bloritsch** [comment]
Here is an example of what I want to fail and the failure comments explain a bit as to why: https://github.com/bloritsch/test-jwt/blob/main/tester.go

**Comment by bloritsch** [comment]
I tested the pull request locally, and it looks like it works.  I added this test case which is more in line with what I originally asked for (didn't require changes to what you created):

```
    t.Run("exp - iat < WithMaxDelta(10 secs)", func(t * testing.T) {
		now := time.Now()
        tok := jwt.New()
        tok.Set(jwt.IssuedAtKey, now)
        tok.Set(jwt.ExpirationKey, now.Add(5 * time.Second))
        
        if !assert.Error(t, jwt.Validate(tok, jwt.WithMaxDelta(2*time.Second, jwt.ExpirationKey, jwt.IssuedAtKey)),
          `jwt.Validate should fail`) {
			return
		}
        
        if !assert.NoError(t, jwt.Validate(tok, jwt.WithMaxDelta(10*time.Second, jwt.ExpirationKey, jwt.IssuedAtKey)),
          `jwt.Validate should succeed`) {
			return
		}
    })
```

**Comment by lestrrat** [comment]
Cool! I just wanted to make sure changes were actually fixing the problem, and a test case like this is perfect. Will merge, am not sure when exactly I'll do a release, but usually I wait for a few days before I do to give people a chance to try things out. Ping me if I'm taking way too much time to release the next version

**Comment by bloritsch** [comment]
All good.  I'm moving at a snail's pace in the project I am using this in
mainly because of limited bandwidth in my own time.  I'll simply increase
the version when it's ready.  I have way more to do before I make my own
release anyways.
