### ISSUE TITLE
Provide an example code to allow validate JWT token with public key

### ISSUE THREAD

**Issue by jiwenhuo** [lestrrat-go/jwx#396]
We are working on a web server that support authentication through JWT token.  
The JWT token can be obtained from HTTP request header, and there's a public key file stay somewhere on the server. 
We would like to use jwx library to validate JWT token with the public key. 

This should be a very common use case for JWT token validation, but unfortunately I didn't find any simple example to use jwx library to achieve this goal.   

With dgrijalva/jwt-go, this can be easily done by the following sample code, is it possible to provide similar functionality or example code in jwx? 

```
func verifyToken(token, publicKeyPath string) (bool, error) {
    keyData, err := ioutil.ReadFile(publicKeyPath)
    if err != nil {
        return false, err
    }
    key, err := jwt.ParseRSAPublicKeyFromPEM(keyData)
    if err != nil {
        return false, err
    }

    parts := strings.Split(token, ".")
    err = jwt.SigningMethodRS256.Verify(strings.Join(parts[0:2], "."), parts[2], key)
    if err != nil {
        return false, nil
    }
    return true, nil
}
```

**Comment by lestrrat** [comment]
What exactly are you asking for? How to read a JWK from a PEM file?

https://pkg.go.dev/github.com/lestrrat-go/jwx/jwk#WithPEM
https://github.com/lestrrat-go/jwx/blob/main/jwk/jwk_test.go#L1413

**Comment by jiwenhuo** [comment]
Yes I've read the code in https://github.com/lestrrat-go/jwx/blob/main/jwk/jwk_test.go#L1413

what I'm looking for is, after I got the key from the file with the code below:
`key, err := jwk.ParseKey([]byte(src), jwk.WithPEM(true))`

How can I validate the signature of a JWT token with the key?

**Comment by lestrrat** [comment]
Is this what you are looking for?

https://github.com/lestrrat-go/jwx/blob/main/docs/01-jwt.md#jwt-validation

**Comment by lestrrat** [comment]
Also, we use the following terminology wrt "Verify" and "Validate" https://github.com/lestrrat-go/jwx/blob/main/docs/01-jwt.md#terminology

I don't know which one you are looking for

**Comment by jiwenhuo** [comment]
> Is this what you are looking for?
> 
> https://github.com/lestrrat-go/jwx/blob/main/docs/01-jwt.md#jwt-validation

I guess that's what I'm looking for, I'll give it a try, thank you!

**Comment by lestrrat** [comment]
If "Verify" is what you are looking for, you just need to use `jwt.Parse` with option parameters. In case of single JWK, use `jwk.WithVerify(alg, key)`

https://github.com/lestrrat-go/jwx/blob/main/examples/jwt_example_test.go#L189

**Comment by jiwenhuo** [comment]
I tried some  code, but got the error message:
`failed to verify jws signature: "kid" fields do not match`

Below is my code skeleton, seems something is missing:

```
var tokenStr string = "eyJhbGciOiJSUzI1NiIs...."
var publicKeyFile string = "/home/test/jwtcert.pem"

f, _ := os.Open(publicKeyFile)
buf, _ := ioutil.ReadAll(f)
key, _ := jwk.ParseKey(buf, jwk.WithPEM(true))
decodedToken, err := jwt.Parse([]byte(tokenStr), jwt.WithVerify(jwa.RS256, key))
```

I tried the same token and pem file on https://jwt.io/, and the token is verified successfully.  

The error message comes from the follow code line:
https://github.com/lestrrat-go/jwx/blob/422d30f669696ab0e7470b92855c293176bdc09d/jws/jws.go#L290

Would you please help on why this error happened? Thanks!

**Comment by lestrrat** [comment]
the error message says it all. does the key and the token have a kid?

https://pkg.go.dev/github.com/lestrrat-go/jwx/jwt#WithKeySet

**Comment by lestrrat** [comment]
the ithe way is to use a single key. in case of WithVerify kid is not required. if you have a keyset with a single key you can use WithDefaultKey

**Comment by jiwenhuo** [comment]
The key is obtained by, I think it is a single key, not a key set? where does the `kid` come from
`key, _ := jwk.ParseKey(buf, jwk.WithPEM(true))`

**Comment by lestrrat** [comment]
oh sorry. didnt read the code in full.

hmmm.
it should work. I would need the actual keys and token to debug further

(also am away from my pc now)

**Comment by lestrrat** [comment]
I'm going to close this due to inactivity. Feel free to reopen if you have more information that you can share.

**Comment by msvechla** [comment]
I am experiencing the same error with the code example from above:

```go
var tokenStr string = "eyJhbGciOiJSUzI1NiIs...."
var publicKeyFile string = "/home/test/jwtcert.pem"

f, _ := os.Open(publicKeyFile)
buf, _ := ioutil.ReadAll(f)
key, _ := jwk.ParseKey(buf, jwk.WithPEM(true))
decodedToken, err := jwt.Parse([]byte(tokenStr), jwt.WithVerify(jwa.RS256, key))
```

> failed to verify jws signature: "kid" fields do not match

The `kid` of the key returned from `ParseKey` is nil and the token has a key value set.

I also tried to create a `keySet` with just one key and the following options

```go
	return jwt.Parse(
		[]byte(jwsString),
		jwt.UseDefaultKey(true),
		jwt.WithKeySet(*v.keySet),
		jwt.WithRequiredClaim(ClaimTenantID),
	)

```

Which did not work as well:

> failed to find key with key ID "V4w..." in key set

Even though I set the `jwt.UseDefaultKey(true)` option.
Do you have any other suggestions on how to verify against a single key?

Thanks a lot for your support!

**Comment by lestrrat** [comment]
> The kid of the key returned from ParseKey is nil and the token has a key value set.

The RFC is not really explicit about this, but currently the stance taken by this library is that if the payload requests a `kid`, then the provided key MUST have the same corresponding `kid`. The way I see it is that `kid` is part of the protection of the payload, and should be respected if given., I have yet to see a proper service operate without `kid`s

If you are absolutely sure that the key you are using is legitimate, currently the workaround would be to populate the key with a kid.

```go
key, _ := jwk.ParseKey(buf, jwk.WithPEM(true))
_ = key.Set(jwk.KeyIDKey, `your-kid-goes-here`)
```
---
as an aside... come to think of it, though, does your certificate have some sort of ID in it that matches the key ID in the payload? if that's the case, `ParseKey()` can/should parse it out.

**Comment by msvechla** [comment]
Thanks for the quick reply!

I switched to using a proper JWKS now, as I already assumed that using a specific certificate is rather unusual. That did the trick.

Thanks for your insights nevertheless!
