### ISSUE TITLE
Can't sign JWT with []byte

### ISSUE THREAD

**Issue by andradei** [lestrrat-go/jwx#397]
**Describe the bug**
Can't sign a JWT with a `jwk.symemetricKey`.
I just want to create a JWT that's signed with a "string" (`[]byte`, technically) instead of a cert.

**The Go version**

`go version go1.16.4 darwin/arm64`

**To Reproduce / Expected behavior**

This code

```go
payload := jwt.New()
payload.Set(jwt.SubjectKey, user.ID)
payload.Set(jwt.ExpirationKey, time.Now().Add(time.Hour*24).Unix())

key, err := jwk.New([]byte("secret")) // <-------------- GOAL IS TO SIGN JWT WITH THIS
if err != nil {
	fmt.Errorf("%v", err)
}

signed, err := jwt.Sign(payload, jwa.ES256, key) // <-------------- ERRORS HERE
if err != nil {
	fmt.Errorf("%v", err)
}
```

produces this error:

```
failed to sign payload: failed sign payload: failed to sign payload: failed to retrieve ecdsa.PrivateKey out of *jwk.symmetricKey: failed to produce ecdsa.PrvateKey from *jwk.symmetricKey: argument to AssignIfCompatible() must be compatible with []uint8 (was *ecdsa.PrivateKey)"
```

**Comment by lestrrat** [comment]
Why are you using `jwa.ES256` which is for elliptic curve keys when you want to be signing with a symmetric key?
Use `jwa.HS256` or similar.

**Comment by andradei** [comment]
@lestrrat That was on oversight on my part. Thanks for the suggestion, it works.
