### ISSUE TITLE
jwk.Set Remove removes 2 keys instead of just one.

### ISSUE THREAD

**Issue by jozadev24** [lestrrat-go/jwx#412]
When removing a key from a set 2 keys might be removed. I think the problem is here:

https://github.com/lestrrat-go/jwx/blob/08de34253bc9633a11b019b143a2d212f8ff0ed8/jwk/set.go#L74

I think the first index in append is wrong and should be:

`s.keys = append(s.keys[:i], s.keys[i+1:]...)`

joza

**Comment by lestrrat** [comment]
Ooh, if that's the case, that's bad. I'd appreciate it if you have a test case handy, but anyways... on it.

**Comment by lestrrat** [comment]
@jozadev24 fixed, released v1.2.3

**Comment by jozadev24** [comment]
Thanks a lot!

Sorry for not coming up with a pull request myself! Kind of a busy day :-) 

Thanks for you work!

**Comment by jozadev24** [comment]
Yikes! 

and 
```
			case len(s.keys) - 1:
				s.keys = s.keys[:i-1]

```
should be 

```
			case len(s.keys) - 1:
				s.keys = s.keys[:i]

```
