### ISSUE TITLE
Small correction to doc for WithMinDelta

### ISSUE THREAD

**Issue by daimaou92** [lestrrat-go/jwx#442]
**Describe the bug**
A small issue. The godoc for [WithMinDelta](https://pkg.go.dev/github.com/lestrrat-go/jwx/jwt#WithMinDelta) reads 

> WithMinDelta is almost exactly the same as WithMaxDelta, but force validation to fail if the difference between time claims are **less** than dur.

Shouldn't it be
> **more** than dur.

The example mentioned describes it correctly:
> For example, in order to specify that `exp` - `iat` > 10*time.Second, you would write ...

`go version go1.16.7 darwin/amd64`

**Comment by lestrrat** [comment]
Hmmm, I _think_ it's right. We want to the validation to **fail** if exp - iat is less than 10 secs.
The statement with the inequality should probably be rephrased as

```
// For example, in order to specify that `exp` - `iat` should be greater than 10*time.Second, you would write
//
//    jwt.Validate(token, jwt.WithMinDelta(10*time.Second, jwt.ExpirationKey, jwt.IssuedAtKey))
//
// The validation would fail if the difference is less than 10 seconds.
```

Does that make sense?

**Comment by daimaou92** [comment]
Ah, my bad .. `validation to fail`. I got too caught up in the literature of `WithMaxDetails` and mixed contexts.

This is correct.

**Comment by lestrrat** [comment]
Cool. I have PR queued to rephrase this so hopefully it will be a bit more clearer. Thanks for bringing it up
