### ISSUE TITLE
What is "option.go" for?

### ISSUE THREAD

**Issue by zamicol** [lestrrat-go/jwx#45]

**Comment by zamicol** [comment]
https://github.com/lestrrat-go/jwx/blob/master/internal/option/option.go

Is there a better place to ask these kind of questions? I'm digging through the library.

I'm also wondering, would it be better if I renamed the jwk header stuff?

JWK's don't have headers.  They have parameters.  Headers belong to JWS.  

https://tools.ietf.org/html/rfc7517#section-4

https://github.com/lestrrat-go/jwx/blob/master/jwk/headers.go

**Comment by zamicol** [comment]
Also, why the JWK generator?

**Comment by lestrrat** [comment]
> options

See "Optional Parameters"  here https://medium.com/@lestrrat/wtf-was-wrong-with-my-go-code-part-2-75b1bb7297fe

> generator

Why not? It's a bunch of repetitive code.
