### ISSUE TITLE
x25519 MUST use shared key. like ECDSA.

### ISSUE THREAD

**Issue by uk-taniyama** [lestrrat-go/jwx#462]
https://datatracker.ietf.org/doc/html/rfc8037
jwx/jwe/jwe.go
		switch key := key.(type) {
		case x25519.PublicKey:
			enc, err = keyenc.NewECDHESEncrypt(keyalg, contentalg, keysize, key)
		default:
			var pubkey ecdsa.PublicKey
			if err := keyconv.ECDSAPublicKey(&pubkey, key); err != nil {
				return nil, errors.Wrapf(err, "failed to generate public key from key (%T)", key)
			}
			enc, err = keyenc.NewECDHESEncrypt(keyalg, contentalg, keysize, &pubkey)
		}

**Comment by lestrrat** [comment]
I don't understand. At first it looks like you are just copying the contents of `jwe.go`.
If there is indeed a problem, can you please provide a reproducible test, and reopen the issue.
