### ISSUE TITLE
Helpful error message from jwt.parse being obscured by less helpful message in jwt.ParseRequest

### ISSUE THREAD

**Issue by codyrehm** [lestrrat-go/jwx#467]
When using jwt.ParseRequest with the option jwk.WithKeyset with a set of invalid keys (i.e. attempting to validate a token with a key that was *not* used to sign the token originally) the operation fails as expected.

However the error that is generated in jwt.parse ("failed to verify jws signature") which is helpful
actually appears to end up getting overwritten and obscured by the much less helpful error on line 114 of jwt.ParseRequest
"failed to find token in any location of the request (tried: [header keys: "

Repro steps:
1. Create a token and sign it with some JWK.
2. Create some other JWK.
3. Create an HTTP request and place the token in the auth header.
4. Call jwt.ParseRequest using jwk.WithKeyset and the key from step 2.

(Pretty sweet library by the way)

**Comment by lestrrat** [comment]
What version of jwx is this? 

Please try to be specific in your reports. For example, "line 114" means nothing if you and I are looking at the file at a different commit. Also, actual code is always more helpful than bullet points.

Now, this sounds familiar. Perhaps #458 and #461 are what you are looking for. In which case, you can test it out on master, but it hasn't been released yet.

**Comment by codyrehm** [comment]
Yes #458 looks like it might address this. Thank you.
