### ISSUE TITLE
Use parsed claims to determine keyset to verify signed token

### ISSUE THREAD

**Issue by retzkek** [lestrrat-go/jwx#474]
**Abstract**
Is there an idiomatic way to use information from the token claims (e.g. issuer) to obtain the key[set] used to verify the token? It seems right now that can only be done by parsing the token twice, which is a bit unwieldy, especially when reading the token from an io.Reader or http.Request, etc.

Our use case is that we can accept tokens from multiple issuers, and use [OAuth discovery](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-discovery-07) (generalized OID Connect discovery) to get the JWKS URL and in turn the keyset. So we either get the keysets for all supported issuers and merge them, or use the issuer claim to determine which keyset to use.

**Describe the proposed solution/change**
Add a new `WithKeySetFunc(f func(Token) (jwk.Set, error)` ParseOption that allows the client code to provide a function that is then used to identify the keyset to be used for verification.

Here's a minimal test case, based on the "Parse (w/jwk.Set)" test case:

```go
			pubkey := jwk.NewRSAPublicKey()
			if !assert.NoError(t, pubkey.FromRaw(&key.PublicKey)) {
				return
			}

			pubkey.Set(jwk.AlgorithmKey, alg)
			pubkey.Set(jwk.KeyIDKey, kid)

			set := jwk.NewSet()
			set.Add(pubkey)
            
			t2, err := t1.Clone()
			if !assert.NoError(t, err) {
				return
			}
			if !assert.NoError(t, t2.Set(jwt.IssuerKey,"http://www.example.com")) {
				return
			}
			signed, err := jwt.Sign(t2, alg, key, jwt.WithHeaders(hdrs))
			if !assert.NoError(t, err) {
				return
			}

			t3, err := jwt.Parse(signed, jwt.WithKeySetFunc(func(tok Token) (jwk.Set, error) {
				switch tok.Issuer() {
				case "http://www.example.com":
					return set, nil
				}
				return nil, fmt.Errorf("unknown issuer")
			}))
			if !assert.NoError(t, err, `jwt.Parse with key set func should succeed`) {
				return
			}

			if !assert.True(t, jwt.Equal(t2, t3), `t2 == t3`) {
				return
			}
```

**Analysis**
Merging the keysets for all supported issuers is an option we can use now (some functionality could be added to make this more egonomic), but "throwing an even bigger bundle of keys at it and seeing what sticks" is a bit distasteful, and doesn't scale well with large numbers of supported issuers. There may be implications for jwk.AutoRefresh as well?

Another alterative is to add a new `VerifyWithKeySet(t Token, set jwk.Set)` function to allow verifying after parsing, but that would require storing the raw JWS data with the token, and may have some security implications or corner cases.

**Comment by lestrrat** [comment]
I see. I want to change the proposed solution to NOT use raw functions, though. I have a thing against passing raw functions as arguments in Go.

My proposal below (note: not too much thought has been put on it yet)

```go
type KeySetProvider interface {
  KeySetFrom(Token) (jwk.Set, error)
}

type KeySetProviderFunc func(Token) (jwk.Set, error)

func (fn KeySetProviderFunc) KeySetFrom(t Token) (jwk.Set, error) {
  return fn(t)
}

func WithKeySetProvider(p KeySetProvider) ParseOption {
   ...
}
```

**Comment by lestrrat** [comment]
Take a look at #475, see what you think

**Comment by retzkek** [comment]
I like your idea to use an interface, especially since in production code there could be quite a bit of logic behind that provider. LGTM

Thanks for the fast response!

**Comment by lestrrat** [comment]
Thanks. merged #475

**Comment by retzkek** [comment]
So I'm happy to report that `WithKeySetProvider()` is working well, thanks again, but, and I apologize for not thinking of this earlier, perhaps `KeySetFrom()` should take a context argument? Maybe something for v2?

**Comment by lestrrat** [comment]
What's the use case?

**Comment by retzkek** [comment]
In our case we end up calling `jwk.AutoRefresh.Fetch()`, which takes a context.

**Comment by lestrrat** [comment]
Hmmmmmm... and you want it to be a propagated context.Context, not just a local `ctx, cancel := context.WithTiemout(context.Backgrond(), whatever)`?

**Comment by lestrrat** [comment]
Well, okay, in any case, let's not do this here, as I KNOW I will lose track of it. If you want ctx as a parameter for KeySetFrom, please file a new issue, and please provide a use case, preferably code (can be pseudocode).
