### ISSUE TITLE
Issue with verifying JWT's with ES256

### ISSUE THREAD

**Issue by zamicol** [lestrrat-go/jwx#48]
Verifying with RS256 succeeds while ES256 fails, returning an "empty buffer" error.  

You can copy and paste the below into jwt_test.go.  I haven't gotten to the bottom of the issue yet.  

```
func TestVerifyWithRS(t *testing.T) {
	alg := jwa.RS256
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return
	}

	t1 := jwt.New()
	t1.Set("example", "RS256")
	signed, err := t1.Sign(alg, key)

	_, err = jwt.ParseVerify(bytes.NewReader(signed), alg, &key.PublicKey)
	if !assert.NoError(t, err, `jwt.ParseVerify should succeed`) {
		return
	}
}

func TestVerifyWithES(t *testing.T) {
	alg := jwa.ES256
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return
	}

	t1 := jwt.New()
	t1.Set("example", "ES256")
	signed, err := t1.Sign(alg, key)

	_, err = jwt.ParseVerify(bytes.NewReader(signed), alg, &key.PublicKey)
	if !assert.NoError(t, err, `jwt.ParseVerify should succeed`) {
		return
	}
}
```

**Comment by lestrrat** [comment]
@zamicol there are two problems:

First, you're not checking the result of `t1.Sign`. Had you checked for it, you would have seen that `t1.Sign` for ES256 was failing with `

```
Error:  	Received unexpected error "failed to sign payload: failed to sign payload: invalid key type *rsa.PrivateKey. *ecdsa.PrivateKey is required"
```

And second, which is the root cause of your problem, is that ES256 requires an elliptic curve based key, which you cannot get from using `"crypto/rsa".GenerateKey`. You need to use `"crypto/ecdsa".GenerateKey`

**Comment by zamicol** [comment]
Ah, thank you @lestrrat.  That's a pretty big error on my part.  

Is there a better way to connect with you?  I would like to be more involved if I can.  

I'm still poking around.  You've done a great job on this project.  Thank you for all your hard work.

**Comment by lestrrat** [comment]
Thanks for the feedback. While I sympathize, I really don't have the tuits between all the work and family, so I really want to avoid having a place where I have to keep monitoring, or keep answering questions and what not. 

The bottom line is that the truth lies in the code.

* If you don't understand something, please read the source
* If documentation is lacking, please file an issue, or a file a PR.
* If you don't understand, or don't agree with the intent of the API/code, please create a PR with what you think is the correct way a particular code should work (note: not asking you to implement the whole thing, I just need to know what you think, in terms of code)
