### ISSUE TITLE
Panic when the private key is nil instead of returning an error

### ISSUE THREAD

**Issue by Dmdv** [lestrrat-go/jwx#482]
Go version is 1.16
jwx version is 1.2.7

I pass in function the private key.
The key is an interface and nil check of an interface is not done correctly.

Code is here: https://github.com/lestrrat-go/jwx/blob/4c29e6cfaeb22ae3cbd6a7d3a95424a33dff5079/jws/rsa.go#L75

try using this approach

```go
func isNil(i interface{}) bool {
	return i == nil || reflect.ValueOf(i).IsNil()
}

func isNilFixed(i interface{}) bool {
	if i == nil {
		return true
	}
	switch reflect.TypeOf(i).Kind() {
	case reflect.Ptr, reflect.Map, reflect.Array, reflect.Chan, reflect.Slice:
		return reflect.ValueOf(i).IsNil()
	}
	return false
}
```

But in your case the check can be simplified with type check of string.
The less generic way would be more correct

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/805238/137045684-66085219-7689-4304-9ac2-f07b64f82530.png">

**Comment by lestrrat** [comment]
Thank you for your report. Please provide a testcase, or even better, a PR with a testcase.
