### ISSUE TITLE
GitHub Sponsoring

### ISSUE THREAD

**Issue by wgehring** [lestrrat-go/jwx#483]
Hello Daisuke / @lestrrat 
I am writing to you on behalf of Daimler / Mercedes-Benz AG. We would like to sponsor you, and I would like to send you an email with further info. Could you please send me an email to wolfgang.gehring(at)daimler.com? 
Thank you. :-)

**Comment by lestrrat** [comment]
I already reached out, so am closing this issue. Thanks for the heads up
