### ISSUE TITLE
Valid JWS cannot be verified after v1.0.8

### ISSUE THREAD

**Issue by joesiltberg** [lestrrat-go/jwx#485]
**Describe the bug**
A valid JWS that could be verified with v1.0.7 can no longer be verified (in v1.0.8 or v1.2.7).

Please attach the output of `go version`

```
go version go1.16.3 linux/amd64
```

**To Reproduce / Expected behavior**
```
func reproduce() {
	signed := `
{
"payload": "eyJhIjoiYiJ9",
"signatures": [{"protected": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImNyaXQiOlsiZXhwIl0sImV4cCI6MCwiaXNzIjoiZm9vIiwibmJmIjowLCJpYXQiOjB9", "signature": "qM0CdRcyR4hw03J2ThJDat3Af40U87wVCF3Tp3xsyOg"}]
}
`
	verified, err := jws.Verify([]byte(signed), jwa.HS256, []byte("secret"))
	if err != nil {
		fmt.Printf("Failed: %v\n", err)
	} else {
		fmt.Printf("Verified:\n%s\n", string(verified))
	}
}
```

With v1.0.7, this verifies  correctly and outputs:

```
Verified:
{"a":"b"}
```

However, upgrading to v1.0.8 (or v1.2.7) gives:

```
Failed: could not verify with any of the signatures
```

**Additional context**
I've tried to find the breaking commit with git bisect and believe it to be c7b516811bcaee3f31e235844320c451a90a178d

I think the problem might be that the protected headers are decoded and unmarshalled, but then marshalled to JSON and base64 encoded again before verifying (and in that process not returning to the original).

Hence it might be important for reproducing that the example includes headers and that the JWS is not generated by lesstrat-go/jwx (since then unmarshalling and marshalling would return to the same string I think).

So to generate the example JWS I used the python package python-jose with the following code:

```
signed = jws.sign({'a': 'b'}, 'secret', {"alg": "HS256", "crit": ["exp"], "exp": 0, "iss": "foo", "nbf": 0, "iat": 0}, algorithm='HS256')
```

**Sponsors**
Are you sponsoring the authors? 
```
A little bit yes :-)
```

**Comment by lestrrat** [comment]
This sounds familiar, and I thought I fixed it. Trying out the repro now.

**Comment by lestrrat** [comment]
Okay, this apparently works:

```go
jws.Verify([]byte("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImNyaXQiOlsiZXhwIl0sImV4cCI6MCwiaXNzIjoiZm9vIiwibmJmIjowLCJpYXQiOjB9.eyJhIjoiYiJ9.qM0CdRcyR4hw03J2ThJDat3Af40U87wVCF3Tp3xsyOg"), jwa.HS256, []byte("secret"))
```

So that means the bug is in the JSON-specific verification.

**Comment by joesiltberg** [comment]
@lestrrat looks good to me! I've also tested it with my example JWS from a real application, works fine.

Thank you!
