### ISSUE TITLE
Unable to unmarshal jwk.Set

### ISSUE THREAD

**Issue by benburleson** [lestrrat-go/jwx#49]
Hi, I'm trying to cache my JWKS to avoid an external web request every time I need it, however I am running into this error:
```
json: cannot unmarshal object into Go struct field Set.keys of type jwk.Key
```

It seems to be marshaling fine because I see the object stored in my cache, so I'm not sure what the issue is unmarshaling.

Here are the lines attempting to unmarshal:
```
var keySet jwk.Set
err := json.Unmarshal(cacheValue, &keySet)
```

Thanks,
Ben

**Comment by lestrrat** [comment]
I think the original intention was that I expected users to use `jwk.Parse`. But looking at the code (and meh, I want to redesign the internal workings...), I definitely agree that things should be symmetrical.

So here's #50 , and I will merge when CI passes

**Comment by benburleson** [comment]
Wow, amazing response, thank you!

I actually ended up doing what I think you are recommending, and caching the HTTP response body prior to `jwk.Parse`ing.

Thanks and great work!
