### ISSUE TITLE
Determining an error of parsing JWT

### ISSUE THREAD

**Issue by qioalice** [lestrrat-go/jwx#493]
Hi. According with the following code
```go
_, err := jwt.Parse(..., jwt.WithVerify(..., ...))
```
How can I determine what kind of error just happened? I mean, I want to recognize whether a token was malformed or a verification (signature) has not been passed.
Moreover if I pass also `jwt.WithValidate(true)` how can I figure out whether it was an error with token validation?

I checked jws, jwt, jwa packages but I didn't find neither exposed `Err...` started variables I can use for something like
```go
errors.Is(err, ErrSignatureInvalid)
```
nor some err checkers like 
```go
func IsSignatureInvalid(err error) {...}
```

So, how can I determine what kind of error happened?

Or maybe there's some different "long" way of token parsing, verification, validation passing through I can check each of these steps whether it has been completed correctly or failed?

**Comment by lestrrat** [comment]
Currently there is no such distinction. I personally don't see much benefit in being able to differentiate the two programmatically (the process failed, the error message does tell you why, and it's not like you can programmatically recover from it). Of course, I could be wrong, but that's my feeling atm.

If you need this, the best approach would be for you to provide me with testcases and detailed usecases so I can consider how to or if I should implement it.

**Comment by lestrrat** [comment]
BTW, for validation errors, you can separate the `jwt.Parse` call to `jwt.Parse` and `jwt.Validate`

**Comment by qioalice** [comment]
Thanks for your fast reply. The reason is simple. The project I'm working on has a different API error codes for different cases.
Thus, a totally incorrect token and a signature verification of token leads to different error codes.
I personally agree with you that this is redundantly but it's a legacy I must support. An other jwt library was used before that had such distinction but since we need a JWK/S supporting I migrating the project's library to your one.

**Comment by lestrrat** [comment]
well, if you want to see it implemented please provide testcases using malformed jwts et al with a hypothetical new error object or API and we'll start from there.

Meanwhile if you want to workaround it for the time beong you will have to compare the stringified errors.

**Comment by qioalice** [comment]
Hi, I will provide a test cases later if I won't forget it. For now it looks like I convinced my work team to migrate to a new API w/o splitting these errors. Despite of that I think it would be great if your package would have such distinction and that feature. Ofc not with highest priority to implement. 

I will close this issue for now since I read you don't like an opened dangling issues.

**Comment by lestrrat** [comment]
@qioalice Thanks! For the record, I might take this up myself one of these days, but in that case I would be guessing how you want to use the API, and it may not be what you wanted... who knows. So it's always better for the end-users like you to provide with a testcase.  Thanks for the report, and feel free to open the issue again if/when you get them testcases or find more serious problems regarding this behavior
