### ISSUE TITLE
Invalid OpenID standard claims since 1.2.8

### ISSUE THREAD

**Issue by alfrunes** [lestrrat-go/jwx#494]
**Describe the bug**
OpenID connect standard claims in sub-package `jwt/openid` changed from snake case to camel case in [v1.2.8](https://github.com/lestrrat-go/jwx/compare/v1.2.7..v1.2.8#diff-6a8b235941d38a6175bb29d207b6f268f1a79230cde01bf292cd575cfe901069).

**Additional context**
[OpenID connect standard claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) use snake case.

**Comment by lestrrat** [comment]
@alfrunes quite possible, because I made some underlying changes. This also means that we're not testing them, can you please send me the list that you found so we can test them?
