### ISSUE TITLE
Expose Static Error Variables instead of calling errors.New

### ISSUE THREAD

**Issue by ddouglas** [lestrrat-go/jwx#498]
**Abstract**
Please describe concisely what you want to accomplish, including prerequisite information. Please remember that if _you_ cannot articulate the problem, we cannot guess what you are thinking.

This is directly related to #493. 

I'd like to propose the use of Public Error vars over calling errors.New() when an error occurs inside the lib.

**Describe the proposed solution/change**

Starting with the Parse and Validate functions (since these are probably to most popular), replace the use of `errors.New` with a declared, publicly exposed variable whose name starts with `Err` and whose type is of `error`. For example: 

```
var ErrTokenExp = errors.New('exp not satisfied') // I typed that from memory, actual error currently in use maybe different maybe different
```

and then in the validate function https://github.com/lestrrat-go/jwx/blob/v1.2.10/jwt/validate.go#L189-L200

you would replace:
```
		if !now.Before(ttv.Add(skew)) {
			return errors.New(`exp not satisfied`)
		}
```
with:
```
		if !now.Before(ttv.Add(skew)) {
			return ErrTokenExp
		}
```

This would allow us as the consumer to compare the error we receive from the `jwt.Validate` call like so:
```
if err != nil &&  !errors.Is(err, jwt.ErrTokenExp) {
	return nil, fmt.Errorf("failed to validate token: %w", err)
}
```

This is helpful to me in particular because our users create an account us first and then login to an SSO provided by a popular MMORPG that our tool is built on top of. On the callback we associate that user with the token that we get back from SSO. We then use your lib to validate the token and store it in a DB. On subsequent calls to the API for additional data, we again validate the token and verify that the token has not expired, amongst other checks. This FR would allow us to ignore expired token errors and then later on use the Refresh Token we have to fetch a new token and update on data store with the new token before calling the API.

I can start working on this, but I wanted to confirm with you that you would accept something like this since in #493, you expressed that you didn't think these type of errors were necessary [here](https://github.com/lestrrat-go/jwx/issues/493#issuecomment-958264893)

If it's a behavior change, please include a failing (or would-be failing) test case.  If it's a structural or an API change, we understand that you cannot create a complete compiling code, but please do your best to produce a a near-valid code that shows exactly what you want

// I can do this once I get confirmation that you would accept something like this if done properly.

**Comment by lestrrat** [comment]
This is just my initial reaction without thinking too much about it, but is your requirement to *ignore certain kinds of validations*, or is your requirement to *detect certain types of errors*? I'm getting the feeling that it's the former, in which case it may be better to create a way to selectively apply validations?

**Comment by ddouglas** [comment]
Definitely want to detect so that I can programmatically determine what the next steps are.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by lestrrat** [comment]
Got it. In principle I'm not against it. 

One minor detail: When given the choice, please choose  explicit and descriptive names over short names. i.e. I'm not a big fan of `jwt.ErrTokenExp`. `jwt.ErrTokenExpired` would probably be better.

**Comment by lestrrat** [comment]
This issue was closed due to inactivity, but I'm re-opening. However, please be advised that the API design may not necessarily match what you expected since you provided no actual code for me to base my design on.
