### ISSUE TITLE
JWT Constructor could take variable slice of Options to build token with

### ISSUE THREAD

**Issue by ddouglas** [lestrrat-go/jwx#500]
**Abstract**
This is possible a refactor of `jwt.New()`, I haven't really dug into what is does yet, but the idea is that like `jwt.Parse` and `jwt.Validate`, `jwt.New` could take a slice of options that allow the user to set various claims on the jwt before the jwt is returned.

**Describe the proposed solution/change**
I'm not sure right now, this is a brain dump and since you have a feature list for V2, I'd like to see if this could be added, however I do have some pesudo code

Right now, my token initialization for a user after they login looks like this.
```
	token := jwt.New()

	err = token.Set(jwt.AudienceKey, "pillbox")
	if err != nil {
		return "", fmt.Errorf("failed to set audience on jwt: %w", err)
	}

	err = token.Set(jwt.IssuerKey, "pillbox")
	if err != nil {
		return "", fmt.Errorf("failed to set issuer on jwt: %w", err)
	}

	err = token.Set(jwt.IssuedAtKey, time.Now().Unix())
	if err != nil {
		return "", fmt.Errorf("failed to set issued at on jwt: %w", err)
	}

	err = token.Set(jwt.ExpirationKey, time.Now().Add(time.Hour*6).Unix())
	if err != nil {
		return "", fmt.Errorf("failed to set expiration on jwt: %w", err)
	}

	err = token.Set("owner_id", owner.ID.String())
	if err != nil {
		return "", fmt.Errorf("failed to set owner_id on jwt: %w", err)
	}

	err = token.Set("email", owner.Email)
	if err != nil {
		return "", fmt.Errorf("failed to set email on jwt: %w", err)
	}

	keyBytes, err := jwt.Sign(token, jwa.RS256, s.privateJwk)
	if err != nil {
		return "", fmt.Errorf("failed to generate jwk set: %w", err)
	}
```

This could be simplify in two ways. One, by my lazy a** actually making the changes I said I would make in #498 and submit a PR, followed by the request in this issue

```
token, err := jwt.New(
	jwt.WithClaim(jwt.ClaimField, "claimValue"), 
	jwt.WithClaim(jwt.ClaimField, "claimValue"),
	jwt.WithClaim(jwt.ClaimField, "claimValue"),
		jwt.WithClaim(jwt.ClaimField, "claimValue"),
)

signed, err := jwt.Sign(....)
if err != nil {
	return err
}

return string(signed), err
```

This is purely a quality of life change. Under the hood, if the `len(options) > 0`, the lib could call `token.Set` like what I'm doing in the current version of the code above, except in a `for range`

**Comment by lestrrat** [comment]
Hi, thanks for the suggestion. I really don't like that `New()` would have to return an error. Maybe a introducing a different function could work?

**Comment by lestrrat** [comment]
Since this issue has been marked stale, I think I will use my judgement and go with introducing a Builder pattern as in #501. Hopefully it will solve your problems too.
