### ISSUE TITLE
[jws] Consider `Sign()` function or the like that allows using `jwk.Set` to generate multiple signatures in one go

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#508]
https://github.com/anatol/tang.go/commit/e76bee4fc768f88eefd3ac185a84ddc9b15317a7#r61455640

**Comment by lestrrat** [comment]
I think this is more of a API design issue rather than if we should/should not provide such API.

I think `jws.Sign()` would be confusing if it could accept a single key or multiple keys.
Similarly, I think I designed `jws.SignMulti()` to accept multiple `jwk.Key`s instead of `jwk.Set` to make the API simple.

I just need to come up with a good API that sounds uniform with other APIs and yet is easily distinguishable.

**Comment by lestrrat** [comment]
What does signing with a JWKS mean? Do you sign the payload using multiple keys, but otherwise using the same options (currently I can only think of headers), or can you specify separate headers for each key?

**Comment by lestrrat** [comment]
Also, I just realized that to sign using a key, we need `alg`. The jwk.Set does not (necessarily) contain this information. Hmmm, suddenly this is starting to look a bit hard.

**Comment by lestrrat** [comment]
@anatol so the only detail that I'm not sure about right now is how to specify the combination of the algorithm and key to use. keys in jwk.Set do not necessarily contain the `alg`  field, and thus it may not be automatically deducible, no?

**Comment by anatol** [comment]
Is `close tickets with 5 days inactivity` too aggressive?

**Comment by lestrrat** [comment]
maybe, if you think closing = rejection.
But since issues can be reopened anytime, I personally don't find it bad per se.

On the other hand I see open issues as something I need to be working on, and it really bugs me/makes me feel anxious when I do my daily checks and see dangling issues waiting for reactions.

Would it make it better if the message when closing contains something similar to this message?

**Comment by lestrrat** [comment]
@anatol BTW, I re-read the configuration, and the configuration said 14 days before labeling stale, and 7 days before closing, so it had been sitting for 21 days, or three weeks. The message was wrong.

**Comment by anatol** [comment]
would it be possible to open the ticket until a solution found?
