### ISSUE TITLE
Make it possible to remove a URL from jwk.AutoRefresh

### ISSUE THREAD

**Issue by imirkin** [lestrrat-go/jwx#521]
I recently went around trying to do the annual dependency update, and figured I'd integrate AutoRefresh. My use-case allows to dynamically switch the jwks URL. So right now the only way is to create a sub-context, keep it around and its cancel function so that I can shut the AutoRefresh down and create a fresh one.

It'd be nice to have an easy way to (a) shut down an AutoRefresh without messing with contexts, and (b) be able to remove a previously-configured URL.

**Comment by lestrrat** [comment]
Sounds like a plan. Let me think of an API

**Comment by lestrrat** [comment]
@imirkin Wrote up something basic in #524. PTAL?

**Comment by imirkin** [comment]
> @imirkin Wrote up something basic in #524. PTAL?

Without commenting on impl, API looks like it should do the trick. It might be nice to return an error if you remove a URL that wasn't configured, but otoh I wouldn't really care in my situation.

**Comment by lestrrat** [comment]
@imirkin it's an easy enough fix, so I added the ability to return an error when the url is non existent

**Comment by imirkin** [comment]
> @imirkin it's an easy enough fix, so I added the ability to return an error when the url is non existent

Looks great! Thanks for the quick turn-around!

**Comment by lestrrat** [comment]
@imirkin Thanks. I merged it, but as always, I intend to let it sit for a few days before making a release. Please let me know if you find anything
