### ISSUE TITLE
Regression: kid ignored when key set does not have alg in keys

### ISSUE THREAD

**Issue by imirkin** [lestrrat-go/jwx#522]
Prior to version v1.2.0 I believe this worked fine. When the functionality to use a keyset which does not have alg's baked in was re-added, it looks like it did so while ignoring kid's. For example, azure publishes these keys:

https://login.microsoftonline.com/common/discovery/v2.0/keys

Note that these do not have an alg in them. Then a JWT will be signed with one of these, identified by a kid. The current logic when `ctx.inferAlgorithm` is set just iterates over the keys in the key set. Seems like it should just use `key` directly as determined previously?

**Comment by imirkin** [comment]
*Technically* it does still work, since it does try all the keys. So it will end up validating, but potentially with the wrong key. I think that's pretty poor behavior. It should use the selected key. (Potentially a security issue that the kid is ignored?)

**Comment by lestrrat** [comment]
I'm still out with my family so haven't looked, but it sounds like a problen. it's probably a missing testcase. can you pls come up with a testcase?

**Comment by imirkin** [comment]
Yeah ... it's actually a bit tricky. Basically if there's a kid, there's a double-check that the kid matches in jws. So it will fail if headers.kid != key.kid. So in practice I don't think it can do anything too bad.

TBH I didn't actually hit a problem, I was just reviewing the code. Still seems off.

The tests are also slightly busted, I'm fixing them, but I can't come up with a convincing test that will cause a failure with the current code.

**Comment by lestrrat** [comment]
Thanks. I don't think I will be able to look at it today my time, so if you do find something, please let me know! I will hopefully have time to look into it tomorrow

**Comment by lestrrat** [comment]
Ah, and I just realized the PR. thanks!

**Comment by imirkin** [comment]
> Thanks. I don't think I will be able to look at it today my time, so if you do find something, please let me know! I will hopefully have time to look into it tomorrow

No rush! Please enjoy your vacation.
