### ISSUE TITLE
Rethink jwk.Set interface

### ISSUE THREAD

**Issue by anatol** [lestrrat-go/jwx#540]
I see that there is a special class for managing key sets - `jwk.Set`. I am using when parse keysets. The interface feels almost like an array of keys but API is a bit awkward. `Iterate()` is not a go-idiomatic interface for iteration.

I would be better if `jwk.Set` be just an alias for `[]jwk.Key` with a number of required functions on it (LookupKeyID/UnmarshalJSON).

**Comment by lestrrat** [comment]
@anatol I'm not saying jwk.Set can't be changed/improved, but as for your suggestion to make `jwk.Set` = `[]jwk.Key`, nope. 

This is allowed:

```json
{
   "random-private-key": "foo",
   "keys": [ list of keys ],
}
```

**Comment by anatol** [comment]
I see. If `privateParams` is needed then the alias does not work. And it seems impossible to make custom structs range-able.

Is there a chance to get access to the underlying slice? Currently my code just repacks `jwk.Set` by `iterate()` and appending to a slice. But I would prefer to avoid wasting CPU cycles and get access to slice for easier iteration.

**Comment by lestrrat** [comment]
As a matter of principle, I'm not allowing users direct access to underlying structures where I can control it.
So... some alternatives:

```go
var list []json.RawMessage
json.Unmarshal(rawJWKS, &list)
for _, rawKey := range rawJWKS {
  jwk.ParseKey(rawKey)
}
```

```go
for i := 0; i < set.Len(); i++ {
   set.Get(i)
}
```
