### ISSUE TITLE
jws.Sign() removes whitespace and newlines from JSON

### ISSUE THREAD

**Issue by repenno** [lestrrat-go/jwx#62]
I would like to use jws.Sign() to parse any JSON payloads such as https://tools.ietf.org/html/rfc7515 Example A.1, A.2, etc 

Unfortunately that is not possible because jws.Sign() strips whitespace, newlines and carriage return from the JWS Protected Header.  Basically, jws.Sign() removes all whitespace from the  JSON. So, instead of signing:

```
     {"typ":"JWT",
      "alg":"HS256"}

[123, 34, 116, 121, 112, 34, 58, 34, 74, 87, 84, 34, 44, 13, 10, 32,
   34, 97, 108, 103, 34, 58, 34, 72, 83, 50, 53, 54, 34, 125]
```

It is signing (no whitespace, no new lines):

```
{"typ":"JWT","alg":"HS256"}
```

jws.Sign() should be able to take the protected headers "as is", without trying to add to a structure and then serialize it. If it changes the JWS headers as presented, it will generate different signatures from other systems or that the original document holder expected.

**Comment by lestrrat** [comment]
Hi, thanks for the issue/PR. I think it looks good, but I just have one reservation, which is "Did the spec mention anything about this...?" Which I don't remember right now, as it has been a while since I read it. If you know the answer, please let me know the relevant sections. Otherwise I'll just refresh my memory and read the spec first to see why I was canonicalizing it, and if the difference should be mentioned in the docs

**Comment by repenno** [comment]
In all Appendix examples of https://tools.ietf.org/html/rfc7515 the protected headers are serialized as presented, i.e., no whitespace removal. I think you have not noticed this issue before because:

1 - Instead of using jws.Sign(), you use sign.Sign() in the test t.Run("HS256Compact", func(t *testing.T)
2 - In some examples only a single protected header is presented, so no whitespace to remove. This creates a false positive.

Finally, from https://tools.ietf.org/html/rfc7519#page-13

```"Note that whitespace is explicitly allowed in the
 representation and no canonicalization need be performed before
encoding."```

For a more recent discussion on the subject:

https://tools.ietf.org/html/draft-rundgren-json-canonicalization-scheme-05

thanks,

**Comment by lestrrat** [comment]
Thanks for the pointers! Will merge.
