### ISSUE TITLE
Curve bits do not need to be a multiple of Keysize

### ISSUE THREAD

**Issue by repenno** [lestrrat-go/jwx#63]
In sign/ecdsa.go there is a the following check:

		if curveBits != keysiz*8 {
			return nil, errors.New("key size does not match curve bit size")
		}

But this check is not ok. See for example https://tools.ietf.org/html/rfc7515 ECDSA P-521 SHA-512. The README says this algorithm is supported but it returns an error. 

The code needs to account for such curves. Example solution: https://github.com/kelseyhightower/app/blob/master/vendor/github.com/dgrijalva/jwt-go/ecdsa.go

gopkg.in/square/go-jose.v2/cryptosigner/cryptosigner.go

**Comment by lestrrat** [comment]
man, really? I think I took that bit after studying square's JOSE library... (reads the link) Oh, they have a v2 now... I see. :D
