### ISSUE TITLE
Migrating from Java to Go

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#669]
### Discussed in https://github.com/lestrrat-go/jwx/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **servlette** March 29, 2022</sup>
Hi,
I have a JWK key like the following:

```
json := `{
 "keys": [
   {
           "alg": "RS256",
           "d": "UjgqAa9D****",
           "e": "AQAB",
           "n": "lPZXYxEyZ***",
           "kty": "RSA",
           "kid": "myKey123"
   }
 ]
}
`
```
I am into migrating an app functionality from `Java` to `Golang` and I can't just go ahead and update the JWK JSON to include `p` in it or create a new JWK for `Golang` as the existing one has to work against both `Java` and `Golang`.

Even though the value `p` is missing in the JSON as shown above, it worked in Java as the 3rd party library Nimbus Jose returned an instance of `RSAPrivateKey` by using `d` and `n`.

Please refer to it here:

https://github.com/felx/nimbus-jose-jwt/blob/47d66f2775c392964788aa6389a46fac84f976cd/src/main/java/com/nimbusds/jose/jwk/RSAKey.java#L1790

When `p` is null, then it is using `n` and `d` to get the modulus and private exponent to initialize the `RSAPrivateKey` instance:

```
                BigInteger modulus = n.decodeToBigInteger();
		BigInteger privateExponent = d.decodeToBigInteger();		
		RSAPrivateKeySpec spec;
		if (p == null) {
			// Use 1st representation
			spec = new RSAPrivateKeySpec(modulus, privateExponent);

		}

              try {
			KeyFactory factory = KeyFactory.getInstance("RSA");

			return (RSAPrivateKey) factory.generatePrivate(spec);

		} catch (InvalidKeySpecException | NoSuchAlgorithmException e) {

			throw new JOSEException(e.getMessage(), e);
		}

```

Once it gets the RSA private key, then it is used to sign a `JWT` as shown below:

```
JWK key = getKeyById("myKey123"); //Custom code to get `JWK` from JSON.
		try {
			if (KeyType.RSA.equals(key.getKeyType())) {
				RSAPrivateKey privateKey = ((RSAKey) key).toRSAPrivateKey();
				RSASSASigner signer = new RSASSASigner(privateKey);
				JWSHeader.Builder headerBuilder = new JWSHeader.Builder(new JWSAlgorithm(key.getAlgorithm().getName()));
				headerBuilder.keyID(key.getKeyID());
				headerBuilder.build();
				JWSHeader header = headerBuilder.build();

				SignedJWT jwt = new SignedJWT(header, claims);

				jwt.sign(signer);
				return jwt.serialize();
			} 
		} catch (JOSEException e) {
			e.printStackTrace();
		}
```

As we are into migrating the existing functionality  to sign a JWT to `Golang`, we are stuck with the following issue.

```
import (
	"github.com/lestrrat-go/jwx/jwk"
)

func main() {

      json := `{
 "keys": [
   {
           "alg": "RS256",
           "d": "UjgqAa9D****",
           "e": "AQAB",
           "n": "lPZXYxEyZ***",
           "kty": "RSA",
           "kid": "myKey123"
   }
 ]
}`
    	_, err := jwk.ParseString(json)
	if err != nil {
		panic(err)
	}
}
```

It panics with the following error:

```
panic: failed to unmarshal JWK set: failed to decode key #0 in "keys": failed to unmarshal JSON into key (*jwk.rsaPrivateKey): required field p is missing
```

In Java, I see the comment `// Use 1st representation` when p is null. I am not sure what it means to use `1st representation` as it may be something to do with getting an RSA private key when the field `p` is not present.

Wondering if there is a way to get an RSA private key when `p` is missing using this go library.
</div>

**Comment by lestrrat** [comment]
@servlette can you please check the fix (don't have to check both, just use the one you are using)

* Proposed fix for v1 in [v1-fix-gh-664](https://github.com/lestrrat-go/jwx/tree/v1-fix-gh-664) branch
* Proposed fix for v2 in [v2-fix-gh-664](https://github.com/lestrrat-go/jwx/tree/v2-fix-gh-664) branch

**Comment by servlette** [comment]
@lestrrat Couldn't get the `v2` fix tested as I see the following error:

go.mod:

```
replace github.com/lestrrat-go/jwx => github.com/lestrrat-go/jwx v2-fix-gh-664
```

```
go mod tidy -compat=1.17
go: errors parsing go.mod:
replace github.com/lestrrat-go/jwx: version "v1.2.19-0.20220329095419-002256c1dd3b" invalid: go.mod has post-v1 module path "github.com/lestrrat-go/jwx/v2" at revision 002256c1dd3b
```

Whereas I got the v1 fix getting compiled:

go.mod:

```
replace github.com/lestrrat-go/jwx => github.com/lestrrat-go/jwx v1-fix-gh-664
```

After running `go mod tidy -compat=1.17` my go.mod file was updated to:

```
replace github.com/lestrrat-go/jwx => github.com/lestrrat-go/jwx v1.2.21-0.20220329095952-0e8a29aa83e3
```

**Comment by servlette** [comment]
Got V2 working:

Here is the sample JWT generated for it:

```eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZm9vIiwiYmFyIl0sImN1c3RvbUNsYWltIjoiY3VzdG9tVmFsdWUiLCJjdXN0b21DbGFpbTEiOiJjdXN0b21WYWx1ZTEiLCJleHAiOjE2NDg1NzU2OTYsImlhdCI6MTY0ODU3MjA5NiwiaXNzIjoiZ2l0aHViLmNvbS9mb28vYmFyIiwianRpIjoiY2Y3MDcyYWMtZDE3OC00ZTc2LWIyYWYtZjgzNmMwODlmY2JlIiwibmJmIjoxNjQ4NTcyMDk2fQ.Htrj16uymfEZiwP60Ffco9fK93lovdCbR_i9kDYS74gL_NZFB3XGkxczCumhonhccYuFeLL1uQDtmk2lpG9yqXFJnP2rb9EJcsDCrSaiJObvt-uFcDwVZgNItNGt1aZD3i8o1qwbDJIFIG1ksbJvkDQT0Iy_Vef56bGqnXwWBz8UQ6oRwX2_VNQy2GdzoMauF8pLWnyMY-fCEf4yrYIPdyxIYETF_EBNcdV-ZzaSPQBKXH2scKn1qRhFUWWBcJpK3LD6PLDzTpwLHx4DZSf0ZmOezlzm7oduBQkhKd9G6q0r9RnOxbXylE-Kk6a1UDcIOiSr-oPTHJEfHrF5EBsfvA
```

Thanks @lestrrat

**Comment by lestrrat** [comment]
This has been merged. v1 now has a new release 1.2.21. v2 has no public releases yet, so no release has been made.

**Comment by servlette** [comment]
Thanks @lestrrat When are you planning to make an official `v2` release?

**Comment by lestrrat** [comment]
No fixed date, but the plan is to do it in April: https://github.com/lestrrat-go/jwx/discussions/638

**Comment by servlette** [comment]
Thanks. One minor thing I would like to call out is when I pasted the JWT string in jwt.io, I did see a warning "Invalid signature" though I was able to generate the JWT and verify it with the public RSA key using your updated V2 SDK. Not sure if it is something to do with the RSA built off of my JWK or something else which I can ignore.

**Comment by lestrrat** [comment]
That's not nearly enough information for me, but one guess is maybe your time-related claims were wrong, and **JWT Validation** (not JWS verification) was failing?
At least the value for `exp` was nearly 7 hours since expired.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/49281/160727006-30b11e61-8548-4c36-9f24-e1387b884578.png">
