### ISSUE TITLE
Question on expected usage of optional build tags

### ISSUE THREAD

**Issue by decentralgabe** [lestrrat-go/jwx#670]
The docs [note that you need a build tag](https://github.com/lestrrat-go/jwx/blob/main/docs/20-global-settings.md#enabling-optional-signature-methods) to enable the `secp256k1` signing algorithm.

In my code that uses this library, I've added `//go:build jwx_es256k` to the file(s) that use this functionality. I've noticed that compilation will fail for any code that uses secp256k1 signing in its call path, unless it too adds the build tag. This has led to the build tag being added to many files in my project!

Also -- since my project is itself a library. When it is consumed by other services, and those services access the signing code, they also need the build tag. The tag is everywhere. 

Am I doing something wrong? Is there a simpler way to enable support of this signing algorithm?

**Comment by lestrrat** [comment]
You don't need to add build tags to your source code. You do, however, need to build or test using the tag: `go build -tags jwx_es256k` or `go test -tags jwx_es256k`.  Unfortunately there is no way in Go to enable this from within the source code, so you will need to hook it up in your Makefile or whatever, and also tell your library users to enable it themselves.

**Comment by decentralgabe** [comment]
Thank you @lestrrat, this is what I figured (and why I closed the issue early). I'd love to see some sort of dynamic enablement without a build tag, such as using the existing [options pattern](https://github.com/lestrrat-go/jwx/blob/main/jwt/options.go#L63).
