### ISSUE TITLE
Ability to use jwk.Cache as jwt.KeyProvider

### ISSUE THREAD

**Issue by sazzer** [lestrrat-go/jwx#687]
(NOTE - I apologize in advance if this functionality already exists. I did look and didn't find it but that doesn't mean it's not there!)

**Abstract**
The `jwk.Cache` mechanism provides a really easy way to get `jwk.Set` keys, with only requesting them as needed. And it's great.

The `jwt.Parse` mechanism allows for a `jws.KeyProvider` interface/function to be provided that will dynamically look up the JWK needed to parse a given token.

As best I can see - and if I'm just missing it then I apologize! - there's no standard way to use a `jwk.Cache` as a `jws.KeyProvider`. This means I've had to write an implementation myself that wraps the `jwk.Cache` and uses it as the `jws.KeyProvider`. Except that there's no domain logic involved. It could be entirely standard and make it easier to use.

**Describe the proposed solution/change**
```
	parsed, err := jwt.Parse([]byte(token),
		jwt.WithKeyProvider(jwkProvider), // There's no way to just pass a jwk.Cache in here
		jwt.WithContext(ctx),
		jwt.WithIssuer(issuer),
		jwt.WithAudience(audience),
		jwt.WithValidate(true),
		jwt.WithVerify(true),
	)
```

Solutions would include:
1. Have `jwk.Cache` implement `jws.KeyProvider` directly.
2. Have a `jwt.ParseOption` that does the wrapping. This would then allow users to write `jwt.Parse(token, jwt.WithKeyCache(cache))` and it just works.

**Analysis**
My current solution is basically this:
```
		jwkProvider := func(ctx context.Context, keySink jws.KeySink, sig *jws.Signature, m *jws.Message) error {
			jwks, err := jwkCache.Get(ctx, url)
			if err != nil {
				return fmt.Errorf("failed to get JWKS: %w", err)
			}

			jwk, found := jwks.LookupKeyID(sig.ProtectedHeaders().KeyID())
			if !found {
				return errors.New("requested key was not found")
			}

			keySink.Key(sig.ProtectedHeaders().Algorithm(), jwk)

			return nil
		},
```

Which works, but it's a bit of a shame to have to write this code myself.

**Comment by lestrrat** [comment]
hi, am reading this from my phone so I haven't looked at it too closely, but where does the key (url) come from?

**Comment by sazzer** [comment]
Apologies - it's from the application configuration pointing to the JWKS
URL. In this exact case it's Auth0 so it's https://<tenant>.
eu.auth0.com/.well-known/jwks.json, but realistically it's just the URL to
the auth providers keyset.

**Comment by lestrrat** [comment]
oh I get it.

hmmmmmmm. would it be possible to write an object that mimics being a jwk.Set, but internally uses jwk.Cache...? then you would be able ti just pass it to WithKeySet...?

**Comment by sazzer** [comment]
Probably. I've got one that is a jws.KeyProvider and that works well
enough. It's just a shame that it's not a core offering in the library was
all.

**Comment by lestrrat** [comment]
Well, what I meant was, "would it be possible to write (in the core library)...". And I think it works.

```go
type CachedSet struct {
  cache *Cache
  url string
}
```

and then just implement the rest of methods.

**Comment by sazzer** [comment]
Aha - whatever you think makes the most sense 🙂

Cheers

**Comment by lestrrat** [comment]
@sazzer I pushed a quick implementation (not tested) https://github.com/lestrrat-go/jwx/tree/gh-687

As it's  almost 11pm on a Friday night where I live now, I don't think I will be working on this too much but if you feel like giving it a whirl, please let me know what you think.

(Note to self:  I need to fix #688 before merging this)

**Comment by sazzer** [comment]
Oh wow. I mentioned this as a potential improvement, and didn't expect a
solution within an hour of raising it. Especially on Good Friday!

Another potential option that occurred to me would be to create the concept
of a `KeySetProvider`, which would then just provide a `jwk.Set` and let
the normal behaviour with that work. The same as `KeyProvider` but for the
whole set. Though what you've already done looks like it'll work just as
well and is likely less work :)

I'll give it a try later and let you know how it goes, though it might not
be today.

Cheers

**Comment by sazzer** [comment]
Just FYI - I've just tried it out and it works great :)

Thanks for the incredible turnaround!
