### ISSUE TITLE
Updated at type is wrong for auth0

### ISSUE THREAD

**Issue by miniscruff** [lestrrat-go/jwx#734]
**Describe the bug**
When using Auth0 as a provider there is an issue with parsing the OpenID token due to a type mismatch:
```
failed to parse payload: 
failed to parse token: 
failed to decode value for key updated_at: 
invalid value for NumericDate: 
failed to accept string "2022-05-06T04:57:24.367Z": 
failed to parse whole value "2022-05-06T04:57:24": 
strconv.ParseInt: 
parsing "2022-05-06T04:57:24": 
invalid syntax
```
This was reported here on the auth0 forums: https://community.auth0.com/t/oidc-id-token-claim-updated-at-violates-oidc-specification-breaks-rp-implementations/24098 and as such I don't really expect you to support it as it goes against spec.

Please attach the output of `go version`: 1.18.1 but I don't think this matters

**To Reproduce / Expected behavior**

To reproduce you will need an auth0 token of course but this is the parsing logic, pretty standard I think.
```go
authorization := req.Header.Get(authHeader)
if authorization == "" {
	return nil, errors.New("authorization header missing")
}

bearerAndToken := strings.Split(authorization, " ")
if len(bearerAndToken) < 2 {
	return nil, errors.New("malformed authorization header: " + authorization)
}

token, err := jwt.Parse(
	[]byte(bearerAndToken[1]),
	jwt.WithKeySet(s.tenantKeys),
	jwt.WithValidate(true),
	jwt.WithAudience(s.config.AuthAudience),
	jwt.WithToken(openid.New()),
)

if err != nil {
	return nil, err
}

return token, nil
```

The parsed token looks like this:
```json
{
  "nickname": "miniscruff",
  "name": "...",
  "picture": "...",
  "updated_at": "2022-05-06T04:57:24.367Z", 
  "email": "...",
  "email_verified": true,
  "iss": "...",
  "sub": "...",
  "aud": "...",
  "iat": "...",
  "exp": "...",
  "nonce": "..."
}
```

I am wondering if there is some way of either overriding the type or a custom parser to implement the parsing. Or even just a way to ignore this error since I don't actually need that value for now. Totally get if this is outside the scope of the project given that it is against the spec.

Small idea could be to try and parse a date string before/after numeric date. Probably better to change the numeric date to something else as it would go against the code gen data but like, this sort of idea.
```go
case UpdatedAtKey:
    layout := "2006-01-02T15:04:05.000Z" // maybe a config or something? not sure
    t, err := time.Parse(layout, value)
    if err == nil {
        t.updatedAt = t
        return nil
    }

    var acceptor types.NumericDate
    if err := acceptor.Accept(value); err != nil {
        return fmt.Errorf(`invalid value for %s key: %w`, UpdatedAtKey, err)
    }
    
    t.updatedAt = &acceptor
    return nil
```

**Comment by lestrrat** [comment]
This is just me responding without taking a deep look at it, but I think I can work around it. Give me a sec.

**Comment by lestrrat** [comment]
@miniscruff Care to try https://github.com/lestrrat-go/jwx/tree/gh-734

```go

// not needed explicitly, as default is `false`, which allows parsing RFC3339
jwt.Settings(jwt.WithNumericDateParsePedantic(false))

tok := openid.New()
_, err := jwt.Parse(
  src,
  jwt.WithToken(tok),
  jwt.WithVerify(false), // if you're using dummy JWTs
  jwt.WithValidate(false),  // ditto
)
```

**Comment by lestrrat** [comment]
I thought about allowing users to specify alternate types/parsers, but I figured this is a simple escape hatch for an unfortunate implementation, so I think something global like this should suffice. Also, nobody gets hurt even if a field representing a date can parse one extra format, I think.

**Comment by miniscruff** [comment]
I think that is working, I am getting `failed to parse payload: "aud" not satisfied` which is farther then I was getting before and sounds more like my own problem.

**Comment by lestrrat** [comment]
@miniscruff Great. I'm going to create a PR and merge the changes, but since this is something that I just whipped out in a few minutes, I don't want to rush to make a release. Meanwhile, please look at the commit SHA after the merge, and use that in your projects until a release is made. 

Oh, and please beware that the API may change before the release.
