### ISSUE TITLE
jwt Validation of iat, nbf and exp is randomly skewed by truncating the time variables under comparison by a second.

### ISSUE THREAD

**Issue by WingGithub** [lestrrat-go/jwx#763]
IsIssuedAtValid(), IsExpirationValid(), and IsNbfValid(), wraps functions that does time comparison in a baffling manner. The time values are truncated to the second before they are compared. This makes no sense because it introduces a random amount of skew (up to a second) to the comparison. It would be more correct to introduce an default acceptable amount to skew time to the comparison and compare on the exact time value instead of truncating the values if some slack was required for ease of use.

**Comment by lestrrat** [comment]
Thank you for your report, but [please provide test cases](https://github.com/lestrrat-go/jwx/blob/develop/v2/.github/CONTRIBUTING.md#please-include-pseudocode-for-any-technical-issues)

**Comment by ErikKalkoken** [comment]
I stumbled over this issue too. My token validations where occasionally failing with "iat not satisfied". I "fixed" this by adding a 1 second skew to the validation. 

But isn't the real issue how the algorithm for comparing time works? When the local time is just 1 nanosecond behind the server time the time comparison for iat can fail, because it is truncating the time to a full second. 

For example this will fail:

```go
iat := "2024-12-18T10:40:50Z"
local := "2024-12-18T10:40:49.999999999Z00:00"
```
Adding a different truncation value does not help, because the algorithm is still truncating, i.e. rounding down.

So I am wondering if it wouldn't be more correct to round the time instead of truncating it?

**Comment by WingGithub** [comment]
> Adding a different truncation value does not help, because the algorithm is still truncating, i.e. rounding down.
> 
> So I am wondering if it wouldn't be more correct to round the time instead of truncating it?

Possibly. Like you, I used the WithAcceptableSkew option of 2 seconds and called it a day. If you can provide a test case maybe the maintainers will look into the issue.

**Comment by ErikKalkoken** [comment]
> > Adding a different truncation value does not help, because the algorithm is still truncating, i.e. rounding down.
> > So I am wondering if it wouldn't be more correct to round the time instead of truncating it?
> 
> Possibly. Like you, I used the WithAcceptableSkew option of 2 seconds and called it a day. If you can provide a test case maybe the maintainers will look into the issue.

Thanks, I will look into providing a test case.

Could you please provide some context, why you chose 2 seconds? Wouldn't 1 second be sufficient?

**Comment by WingGithub** [comment]
I can't remember, it's been a while but my guess is the truncation is to the second so almost an entire second is the possible range of uncertainty, then add a second for the actual skew?

**Comment by lestrrat** [comment]
I think what you want to do is to use `WithTruncation(0)`

```go
func TestGH763(t *testing.T) {
	iat, err := time.Parse(time.RFC3339, "2024-12-18T10:40:50Z")
	require.NoError(t, err, `time.Parse should succeed`)

	local, err := time.Parse(time.RFC3339Nano, "2024-12-18T10:40:49.999999999Z")
	require.NoError(t, err, `time.Parse should succeed`)

	tok, err := jwt.NewBuilder().
		IssuedAt(iat).
		Build()
	require.NoError(t, err, `jwt.NewBuilder should succeed`)

	err = jwt.Validate(tok,
		jwt.WithTruncation(0),
		jwt.WithAcceptableSkew(time.Second),
		jwt.WithClock(jwt.ClockFunc(func() time.Time {
			return local
		})),
	)
	require.NoError(t, err, `jwt.Validate should succeed`)
}
```

**Comment by WingGithub** [comment]
Nice. Looks like the WithTruncation option was added on 7/18/2022.

**Comment by ErikKalkoken** [comment]
> I think what you want to do is to use `WithTruncation(0)`
> 
> ```go
> func TestGH763(t *testing.T) {
> 	iat, err := time.Parse(time.RFC3339, "2024-12-18T10:40:50Z")
> 	require.NoError(t, err, `time.Parse should succeed`)
> 
> 	local, err := time.Parse(time.RFC3339Nano, "2024-12-18T10:40:49.999999999Z")
> 	require.NoError(t, err, `time.Parse should succeed`)
> 
> 	tok, err := jwt.NewBuilder().
> 		IssuedAt(iat).
> 		Build()
> 	require.NoError(t, err, `jwt.NewBuilder should succeed`)
> 
> 	err = jwt.Validate(tok,
> 		jwt.WithTruncation(0),
> 		jwt.WithAcceptableSkew(time.Second),
> 		jwt.WithClock(jwt.ClockFunc(func() time.Time {
> 			return local
> 		})),
> 	)
> 	require.NoError(t, err, `jwt.Validate should succeed`)
> }
> ```

tyvm for this. But this is not what I meant. That test case only passes, because you allow 1 second of skew. The `jwt.WithTruncation(0)` option does not impact the outcome. The test will pass without it and will fail without the skew.

**Comment by ErikKalkoken** [comment]
The other popular JWT library for Go does not appear validate the iat claim by default and says it is not necessary according to the RFC: [here](https://github.com/golang-jwt/jwt/blob/main/validator.go#L52) .

But when I look at the validation code for jwx it seams that[this validation can not be disabled: [here](https://github.com/lestrrat-go/jwx/blob/19d4fae3f38edda58757b5f7da39d3875e296f26/jwt/validate.go#L254)

Maybe the best solution would be to allow people to disable this validation and maybe even change the default?

**Comment by lestrrat** [comment]
@ErikKalkoken 

> tyvm for this. But this is not what I meant. That test case only passes, because you allow 1 second of skew. The jwt.WithTruncation(0) option does not impact the outcome. The test will pass without it and will fail without the skew.

Oh, yeah, you're right. oops.

>But when I look at the validation code for jwx it seams that[this validation can not be disabled: [here](https://github.com/lestrrat-go/jwx/blob/19d4fae3f38edda58757b5f7da39d3875e296f26/jwt/validate.go#L254)

Yes you can

```go
func TestGH763_ResetValidators(t *testing.T) {
	iat, err := time.Parse(time.RFC3339, "2024-12-18T10:40:50Z")
	require.NoError(t, err, `time.Parse should succeed`)

	local, err := time.Parse(time.RFC3339Nano, "2024-12-18T10:40:49.999999999Z")
	require.NoError(t, err, `time.Parse should succeed`)

	tok, err := jwt.NewBuilder().
		IssuedAt(iat).
		Build()
	require.NoError(t, err, `jwt.NewBuilder should succeed`)

	err = jwt.Validate(tok,
		jwt.WithResetValidators(true),
		jwt.WithValidator(jwt.ValidatorFunc(func(ctx context.Context, token jwt.Token) jwt.ValidationError {
			if !token.IssuedAt().After(local) {
				return jwt.NewValidationError(errors.New("iat should be before local time"))
			}
			return nil
		})),
		jwt.WithClock(jwt.ClockFunc(func() time.Time {
			return local
		})),
	)
	require.NoError(t, err, `jwt.Validate should succeed`)
}
```

**Comment by ErikKalkoken** [comment]
> @ErikKalkoken
> 
> > tyvm for this. But this is not what I meant. That test case only passes, because you allow 1 second of skew. The jwt.WithTruncation(0) option does not impact the outcome. The test will pass without it and will fail without the skew.
> 
> Oh, yeah, you're right. oops.
> 
> > But when I look at the validation code for jwx it seams that[this validation can not be disabled: [here](https://github.com/lestrrat-go/jwx/blob/19d4fae3f38edda58757b5f7da39d3875e296f26/jwt/validate.go#L254)
> 
> Yes you can
> 
> ```go
> func TestGH763_ResetValidators(t *testing.T) {
> 	iat, err := time.Parse(time.RFC3339, "2024-12-18T10:40:50Z")
> 	require.NoError(t, err, `time.Parse should succeed`)
> 
> 	local, err := time.Parse(time.RFC3339Nano, "2024-12-18T10:40:49.999999999Z")
> 	require.NoError(t, err, `time.Parse should succeed`)
> 
> 	tok, err := jwt.NewBuilder().
> 		IssuedAt(iat).
> 		Build()
> 	require.NoError(t, err, `jwt.NewBuilder should succeed`)
> 
> 	err = jwt.Validate(tok,
> 		jwt.WithResetValidators(true),
> 		jwt.WithValidator(jwt.ValidatorFunc(func(ctx context.Context, token jwt.Token) jwt.ValidationError {
> 			if !token.IssuedAt().After(local) {
> 				return jwt.NewValidationError(errors.New("iat should be before local time"))
> 			}
> 			return nil
> 		})),
> 		jwt.WithClock(jwt.ClockFunc(func() time.Time {
> 			return local
> 		})),
> 	)
> 	require.NoError(t, err, `jwt.Validate should succeed`)
> }
> ```

Turns our the 1 second is not enough to get rid of the occasional iat failures. Instead of increasing the skew to two 2 seconds I am now planing to disable the iat check and have the same validations like the other JWT library.

I am a bit confused about the above test case / example on how to disable the iat check though. As I understand it there are 3 default validations: iat, exp and nbt. I would want to disable the iat check only, but keep the other two checks. However, the above example appears to disable all checks and just do a custom iat check.

Please correct me if I am wrong, but I would suggest the following to just disable the iat check, but keep the others:

```go
func TestDisableIatValidatorOnly(t *testing.T) {
	iat, err := time.Parse(time.RFC3339, "2024-12-18T10:40:50Z")
	require.NoError(t, err, `time.Parse should succeed`)

	local, err := time.Parse(time.RFC3339Nano, "2024-12-18T10:40:49.999999999Z")
	require.NoError(t, err, `time.Parse should succeed`)

	tok, err := jwt.NewBuilder().
		IssuedAt(iat).
		Build()
	require.NoError(t, err, `jwt.NewBuilder should succeed`)

	err = jwt.Validate(tok,
		jwt.WithResetValidators(true),
		jwt.WithValidator(jwt.IsExpirationValid()),
		jwt.WithValidator(jwt.IsNbfValid()),
		jwt.WithClock(jwt.ClockFunc(func() time.Time {
			return local
		})),
	)
	require.NoError(t, err, `jwt.Validate should succeed`)
}
```

**Comment by lestrrat** [comment]
> Please correct me if I am wrong, but I would suggest the following to just disable the iat check, but keep the others:

The code you provided is totally fine, my example was, as you correctly pointed out, to just quickly disable all checks.

**Comment by ErikKalkoken** [comment]
tyvm for your confirmation. I will use this code in my app.
