### ISSUE TITLE
Incorrect Parsing of Complete JWS JSON

### ISSUE THREAD

**Issue by repenno** [lestrrat-go/jwx#77]
Similar issues to #70 

https://tools.ietf.org/html/rfc7515#appendix-A.6

I was trying to get coverage for protected header and key lookup in LookupSignature(kid string) and noticed a few things.

- While running t.Run("CompleteJSON", func(t *testing.T)..) I noticed that after unmarshal:

- Protected header structure was empty
- Header structure contained both protected and unprotected headers. 
- Entries were not delete from map
- Not checking length of map before assignment.

**Comment by lestrrat** [comment]
Ooh ouch. If you have PRs, let me know. Otherwise failing tests would be much appreciated

**Comment by repenno** [comment]
Yes, I will submit a new PR shortly. I added a new test that covers these issues. BTW, what do you feel about files like option.go that have 0% percent coverage? Or functions like (k *SymmetricKey) UnmarshalJSON() that are not used and have 0% coverage?

In order to use this JWX library in the project I work I would need to remove them. I can remove in a copy of this repo or submit a PR here. Files and functions without coverage will not pass security audit...and leave me wake at night (;-)

**Comment by lestrrat** [comment]
Well, that's something which I can probably rectify. Please let me know what you need (coverage goal? something else) in a separate issue.
