### ISSUE TITLE
any plan for paseto ?

### ISSUE THREAD

**Issue by zzycn003** [lestrrat-go/jwx#801]
Thanks for the great library. Do you have any plan to support paseto ?

thanks

**Comment by lestrrat** [comment]
I don't know much about PASETO, but at a first glance it doesn't look like it's something that a JOSE standards library can just "support", as serialization formats seem pretty different

**Comment by zzycn003** [comment]
> I don't know much about PASETO, but at a first glance it doesn't look like it's something that a JOSE standards library can just "support", as serialization formats seem pretty different

thanks for your response.

quoted from paseto.io:  Paseto is everything you love about JOSE (JWT, JWE, JWS) without any of the [many design deficits that plague the JOSE standards](https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid).

**Comment by lestrrat** [comment]
Uh, yes, but have you actually read the specifications. They are different enough that if anything they would be a separate code base
