### ISSUE TITLE
Ability to get `err` status from CachedSet

### ISSUE THREAD

**Issue by jwhitaker-swiftnav** [lestrrat-go/jwx#827]
Hey,
Thanks for your work on this.
I want to use `CachedSet`, but it looks like all of the methods hide any errors from the underlying cache. My use case is just to make sure the keyset is valid as a sanity check at init time.

Having something like `CachedSet.Refresh() (err)` that returns the `err` from `cached()` would be enough for my needs: I could then call this and be confident that the remote keyset exists.

Thanks again!
Jarrad

**Comment by lestrrat** [comment]
The CachedSet is not responsible for the refreshing action, and therefore does not have access to the errors. The fetch is also asynchronous, so it wouldn't make sense for CachedSet to have it.

if you want to access the errors,  you will need to work with the `jwk.Cache` object (which the `CachedSet` requires, anyway), and pass the proper ErrSink and handle the errors elsewhere.

**Comment by jwhitaker-swiftnav** [comment]
I really just want an analogue to what you have in examples for using Cache directly:
```go

  // Refresh the JWKS once before getting into the main loop.
  // This allows you to check if the JWKS is available before we start
  // a long-running program
  _, err := c.Refresh(ctx, googleCerts)
  if err != nil {
    fmt.Printf("failed to refresh google JWKS: %s\n", err)
    return
  }
```

The fact that it refreshes the cache is a side effect, I'm just after a straightforward way to check that the CachedSet I have just created is valid.

I know I can do exactly the above with the same `Cache` and `url` that I use to build the CachedSet, but it feels a bit off - "if I happen to refresh a cache with the same url and cache I passed to CachedSet,  then I can just trust that the CachedSet will work as well". It also means, if I want this check to happen at a different point to initialization, that I have to persist the `url` and `Cache` alongside the `CachedSet` in my app, which feels a bit leaky.

If `CachedSet` had something like `CachedSet.Initialize()` or `.CheckMyConfigForMe()` (bikeshedding names that don't have Refresh in them) that just returned any underlying error if the URL was wrong, server down, etc, this would make it a much easier abstraction to use - at it is, it feels a bit funny using it if it can't tell me if it's set up correctly or not.

**Comment by lestrrat** [comment]
Ah, so it's not that you want the `err` per se... I see.

**Comment by lestrrat** [comment]
So I thought I'd give it a try wrote the code in about 5 minutes, then started the docs as to
how this method should be used, and I'm now confused as to the use case

The only use cases that I can come up with is either
1. Call `(jwk.CachedSet).Refresh` for every iteration
2. Call `(jwk.CachedSet).Refresh` periodically

And to me both of those don't make sense: 

```go
// Case 1: do it for every iteration. This is useless use of the `jwk.Cache`, because
// you're not caching anything. You might as well fetch it every iteration
for {
   if err := cached.Refresh(ctx); err != .... { }
   ...
}
```

```go
// Case 2: periodically refresh. Not sure why you need this, because you could just tweak the
// refresh window when you configured the cache (via `jwk.WithRefreshWindow`)
for {
   if time.Since(lastCheck) > threshold {
     if err := cached.Refresh(ctx); err != nil {  ... }
   }
   ...
}
```


So ATM this sounds like you're using an unreliable source for the JWKS, which means you probably don't want a generic caching mechanism -- you probably want to verify its validity every time?
The purpose of `jwk.Cache` is to avoid uselessly fetching stable JWKS sources like the ones from Google, AWS, Azure: they are mostly available anytime, and only occasionally get rotated. This means that we do not need to check for errors most of the time, but we do need to re-fetch them once in a while to refresh.

Anyways, I admit I maybe missing the point and am open for suggestions. As it is, I'm not sure this is a thing we should add to the API as I can't quite explain for what kind of real-life JWKS handling you want to use it for

**Comment by jwhitaker-swiftnav** [comment]
Use case here is our key urls are not quite static, they can change in different environments, and we want to early exit if we've fat-fingered a config option (or if a dev is running this with their network cable unplugging or something else dumb).
So something like the snippet you provide in `Cache` doco would be perfect.
I'm happy to PR this if you are receptive.

**Comment by lestrrat** [comment]
Yeah, but how are you going to call it / use it. Like, what's the frequency? What are the different environments?
The fact that you need this on the cached set itself means that you need to check this _while_ you are in your main JWKS-processing loop. So far the cases you described can perfectly be handled from a separate goroutine that controls the `jwk.Cache` object (i.e. NOT the `jwk.CachedSet`)

**Comment by jwhitaker-swiftnav** [comment]
1) We initialize the Cache with url, make a CachedSet from the Cache and persist it, then throw away the cache.

2) Then, later, when we want to start doing network checks, but still in app initialization, we (try to) verify that the CachedSet has a key in it or do an early abort.

We only have the CachedSet at 2), and indeed at any point in our app, because we throw away the Cache as an implementation detail of 1). Yes we could keep the Cache for the lifetime of our app and do ongoing checks like your examples, but then we may as well not be using CachedSet at all. If the CachedSet has no way to check its initial validity then I'd question if it is of real use at all.

**Comment by jwhitaker-swiftnav** [comment]
> Well, again, the `jwk.CachedSet` is for stable sources. You fail to explain why you are using `jwk.CachedSet` for such a source that you need to keep checking for validity.

The source is considered stable, the only validity check I want to run is on initialization. This is because the source can be affected by configuration and can therefore be subject to typos etc. If it works once I'm happy with the assumption that it will work forever, and to rely on the cache if it doesn't. Again, this is the same approach taken in the example you've provided in the doco for `Cache` itself.

(thanks for the detailed example of implementing ongoing validity checks though, that could come in handy in other scenarios!)

**Comment by lestrrat** [comment]
OK. If it's the initialization you are talking about, then you should be able to do with `cache.Refresh`, no? That's the one place that we explicitly set to check if a url is valid.

I'll edit my previous post's code to include a refresh after submitting this.

**Comment by lestrrat** [comment]
Also, I realized there was a bug in my code (I didn't create a jwk.CachedSet, sorry)

**Comment by lestrrat** [comment]
@jwhitaker-swiftnav Alright, hopefully the snippet makes more sense now. Sorry if that caused a confusion.
