### ISSUE TITLE
Problem when adding JWK in JWT Headers

### ISSUE THREAD

**Issue by xtrycatchx** [lestrrat-go/jwx#834]
Hi, 

My apologies in advance if my question is confusing.

Anyways, I am struggling on adding jwk field in the signed JWT token. Seems like if i add the field JWT in headers, it is being removed during signing.

I tried to add jwk in the token before signing like this:
```go
        headers := jws.NewHeaders()
	headers.Set("x-spec", kid)

	//  :(
	headers.Set("jwk", map[string]interface{}{
		"kty": "EC",
		"crv": "secp256k1",
		"x":   "YAXIamcY9mIhcTp3BzxBKRzDq7_NA6pJVemytQ2_f5s",
		"y":   "ZnLa0NRq3mHjgveYiKc-p4mdlBm-zx1snsIIfBGI-hg",
	})
```

and signed the token like this
```go
signedTok, err := jwt.Sign(tok, jwt.WithKey(jwa.ES256K, sigPrivateKey, jws.WithProtectedHeaders(headers)))
```

however, the output `signedTok` did not reflect the `jwk` in the header, but the custom field `x-spec` is there :( :

`eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJ4LXNwZWMiOiJkaWQ6ZWJzaTp6c1BORU5EMTNaZkhHYWVRb2tlMkNZNktwQ2RmWXpEa3hKOFdjenJneGs2dkUja2V5cy0xIn0.--REMOVED SENSITIVE BODY--.IFTMUYlTFJUsAZihgHSTMujEq0lYDayTt-n4ETUCQvQXnrDsalmKeBls00EwSq8WM8OJzBmA12wAkIAPaCCeAg`

the decoded value of the header shows only these properties ( where's `jwk` ?)
```json
{
  "alg": "ES256K",
  "typ": "JWT",
  "x-spec": "did:ebsi:zsPNEND13ZfHGaeQoke2CY6KpCdfYzDkxJ8Wczrgxk6vE#keys-1"
}
```

is there a way to add fields like `jwk` in the token header to result something like this?

`eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJkaWQ6ZWJzaTp6c0U5dGhhNDhueG5DUUgzVVlranZobzFjRDJ1NXFuNmJWc1ZZQlB3YWJ5VmkjNmtielNYMWIxN1VnSURCSWNQaENYdF9qMURmTGxGdnphR2tySjVFNGNBRSIsImp3ayI6eyJrdHkiOiJFQyIsImNydiI6InNlY3AyNTZrMSIsIngiOiJFZWpTbXBaZWpYbUpWZFFLRDdyZTlWaU41czV4N2x2RDlITUw3Q2Y3NlljIiwieSI6Ilo3T3V6clZLNld0NFdlWUo2ZmFUbERuV2szTGVqbVFOdm9JV0ExNWpDNDAifX0.--REMOVED SENSITIVE BODY--.-XtdoPZcW7b_pl3-tQ71_Mb5DWGbKK082TEEf74vSVVnC-s5KqCXZDTtsPBs2L1fiXVb3fdb7s5iioCJKjqJLw` 

wherein when decoded the header shows the public JWK:
```json
{
  "alg": "ES256K",
  "typ": "JWT",
  "kid": "did:ebsi:zsE9tha48nxnCQH3UYkjvho1cD2u5qn6bVsVYBPwabyVi#6kbzSX1b17UgIDBIcPhCXt_j1DfLlFvzaGkrJ5E4cAE",
  "jwk": {
    "kty": "EC",
    "crv": "secp256k1",
    "x": "EejSmpZejXmJVdQKD7re9ViN5s5x7lvD9HML7Cf76Yc",
    "y": "Z7OuzrVK6Wt4WeYJ6faTlDnWk3LejmQNvoIWA15jC40"
  }
}
``` 

Thanks a lot in advance.

**Comment by lestrrat** [comment]
I can't be sure without complete code, but I think what's happening is that you are passing a `map[string]interface{}` where a `jwk.Key` is required for `headers.Set`. You would have noticed this if you checked for the return value of `headers.Set`:

```go
err := headers.Set("jwk", map[string]interface{}{
  "kty": "EC",
  "crv": "secp256k1",
  "x":   "YAXIamcY9mIhcTp3BzxBKRzDq7_NA6pJVemytQ2_f5s",
  "y":   "ZnLa0NRq3mHjgveYiKc-p4mdlBm-zx1snsIIfBGI-hg",
})
if err != nil {
  fmt.Printf("%s\n", err)
}
// invalid value for jwk key: map[string]interface {}
```

**Comment by xtrycatchx** [comment]
Thanks a lot, it works! Tried with your suggestion:
```go
        jsonData := map[string]interface{}{
		"kty": "EC",
		"crv": "secp256k1",
		"x":   "YAXIamcY9mIhcTp3BzxBKRzDq7_NA6pJVemytQ2_f5s",
		"y":   "ZnLa0NRq3mHjgveYiKc-p4mdlBm-zx1snsIIfBGI-hg",
	}
	jsonKey, err := json.Marshal(jsonData)
	if err != nil {
		log.Println(err.Error())
		panic(err)
	}

	pubKey, err := jwk.ParseKey(jsonKey)

	headers.Set("jwk", pubKey)
```
again used here
```go
signedTok, err := jwt.Sign(tok, jwt.WithKey(jwa.ES256K, sigPrivateKey, jws.WithProtectedHeaders(headers)))
```

And got the expected output:
`eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiWUFYSWFtY1k5bUloY1RwM0J6eEJLUnpEcTdfTkE2cEpWZW15dFEyX2Y1cyIsInkiOiJabkxhME5ScTNtSGpndmVZaUtjLXA0bWRsQm0tengxc25zSUlmQkdJLWhnIn0sInR5cCI6IkpXVCIsIngtc3BlYyI6ImRpZDplYnNpOnpzUE5FTkQxM1pmSEdhZVFva2UyQ1k2S3BDZGZZekRreEo4V2N6cmd4azZ2RSNrZXlzLTEifQ.--REMOVED SENSITIVE BODY--.jKGC7GVXAWLOOhp82eQwaWDEg5Wr2i9Fxj8toaXaM_rrF1ltCheZrIYyxnJnNjjXGKJZFF-nvPkL0Gl31W0MIA`

**Comment by lestrrat** [comment]
FYI, it might just be better to create `ecdsa.PrivateKey`, and use `jwk.FromRaw(privateKey)`, because using `json,Marshal` and `jwk.ParseKey` could be inefficient. Haven't benchmarked it though.

**Comment by lestrrat** [comment]
@xtrycatchx JFYI, yes, using `ecdsa.PublicKey` with `secp256k1.S256()` as the curve algorithm is much faster. See #835

```
$ go test -tags jwx_es256k -run=none -bench . ./jwk/ -v
goos: linux
goarch: amd64
pkg: github.com/lestrrat-go/jwx/v2/jwk
cpu: AMD Ryzen 9 3900X 12-Core Processor
BenchmarkKeyInstantiation
BenchmarkKeyInstantiation/Use_json.Marshal/json.Unmarshal
BenchmarkKeyInstantiation/Use_json.Marshal/json.Unmarshal-24               72087             16496 ns/op
BenchmarkKeyInstantiation/Use_jwk.FromRaw
BenchmarkKeyInstantiation/Use_jwk.FromRaw-24                             1690078               713.3 ns/op
PASS
ok      github.com/lestrrat-go/jwx/v2/jwk       3.292s
```
