### ISSUE TITLE
Cannot parse key claim as jwk.Key

### ISSUE THREAD

**Issue by felixlinker** [lestrrat-go/jwx#864]
**Abstract**
I would like to parse a JWT that has a `key` claim which maps to a JWK in JSON encoding (not a JWK set). After the token has been parsed, `token.Get("key")` maps to a value of type `map[string]interface{}` (the unmarshalled JSON), and I find it "impossible" to parse this claim as a `jwk.Key`.

My workaround right now is to first marshal the map into a JSON again, and then use `jwk.ParseKey`.

**Describe the proposed solution/change**
```go
package main

import (
	"log"
	"reflect"

	"github.com/lestrrat-go/jwx/v2/jwt"
)

func main() {
	// Either I would like the following to work...
	// jwt.RegisterCustomField("key", jwk.Key{})
	t, err := jwt.Parse([]byte(`{
		"key": {
			"crv": "P-521",
			"kid": "zrnxO3eID8w12HAaxyvUiQ7hk9B8XPBTl3DA2jDCLf4=",
			"kty": "EC",
			"x": "AMFF_9SLn2K9aC9mN6hMPokQO2TWru57lKpznJtdIsJ5zNdRne5i4dKnBoc8g3QzOT4p8bfgUwTCpUfKWNVbzbgZ",
			"y": "AShfd_B-NGxwy9liWhtkleyhxnr3xF6uoWghIbH4m5xiGJs6vHxP24UO-SEcfyd8qjNoxDk8fF2iLA1x4Q0je4US"
		}
	}`), jwt.WithVerify(false))
	if err != nil {
		log.Fatal(err)
	}
	key, _ := t.Get("key")
	log.Print(reflect.TypeOf(key)) // -> map[string]interface{}
	// ... or I would like this to work
	// key, _ := jwk.ParseFromMap(t.Get("key").(map[string]interface{}))
}
```

**Analysis**
Alternatives are given in the code example. I presume the first option (using `RegisterCustomField`) is preferable, as the `encoding/json` API does not seem to support the use case of transforming a map into a struct.

The token that I want to parse is _not_ a JWK set (and cannot changed to become one). The token must include exactly one key, and will have other claims that I omitted here for brevity.

**Comment by lestrrat** [comment]
I'm guessing your question is
 * RegisterCustomField is what you think should work, but
 * since it requires a concrete type, it doesn't work on the interface type `jwk.Key`
 * So how should I go about parsing it?

This is sort of an escape hatch, but I think I would do (untested, but I think it should work):

```go
package myapp

type EmbeddedKey struct {
  Key jwk.Key
}

func (k *EmbeddedKey) UnmarshalJSON(data []byte) error {
  parsed, err := jwk.ParseKey(data)
  if err != nil { return err }
  
  k.Key = parsed
  return nil
}

// elsewhere...
jwt.RegisterCustomField(`key`, EmbeddedKey{})

tok, err := jwt.Parse(...)
k, _ := tok.Get(`key`)
// use k.Key
```

(this is mainly a note for my future self): For when/if there's v3, I think it would be prudent to allow `RegisterCustomField` to accept a constructor/parser, if that's possible.

**Comment by felixlinker** [comment]
`RegisterCustomField` accepting a parser would be great and solve my issue!

Also thanks for coming up with this workaround. Using the wrapper type for unmarshalling works great!
