### ISSUE TITLE
Support bazel

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#872]
I'm now interested in Bazel, so trying to see how it would work with this

**Comment by michaelboyd2** [comment]
This would be great! I'm trying to depend on this package and I get

```
ERROR: /private/var/tmp/_bazel_michaelboyd/434a1d89a09ded4ce4e377feb4b142e7/external/com_github_lestrrat_go_jwx/x25519/BUILD.bazel:3:11: GoCompilePkg external/com_github_lestrrat_go_jwx/x25519/x25519.a failed: (Exit 1): builder failed: error executing command (from target @com_github_lestrrat_go_jwx//x25519:x25519) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -src external/com_github_lestrrat_go_jwx/x25519/x25519.go ... (remaining 36 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/com_github_lestrrat_go_jwx/x25519/x25519.go:87:28: undefined: curve25519.X25519
external/com_github_lestrrat_go_jwx/x25519/x25519.go:87:52: undefined: curve25519.Basepoint
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/compile: exit status 2
```

Not 100% sure if it is a problem with this package though - might be something do do with golang/x/crypto.

**Comment by lestrrat** [comment]
@michaelboyd2 I know what that means. You (or me, somewhere in this package) are using an old version of Go. I forget which version exactly, but  it needs to be updated to a recent version to get those symbols

**Comment by michaelboyd2** [comment]
Thanks, I was intending to be using 1.19.5 but perhaps I am making some mistake. I will investigate.

**Comment by lestrrat** [comment]
@michaelboyd2 FYI there's a half-baked version of bazel-ized jwx in the [bazel branch](https://github.com/lestrrat-go/jwx/tree/bazel). Please take a look if you are interested.

**Comment by michaelboyd2** [comment]
@lestrrat thanks I fixed my problem, I just had some deps in the wrong order - your comment helped.

I had a look at the bazel branch it worked well for me: build, test, gazelle. Looks good to me.

Maybe consider adding a .bazelversion? There are also things like https://blog.aspect.dev/bazelrc-presets, https://github.com/keith/buildifier-prebuilt and https://github.com/aspect-build/bazel-super-formatter that probably you don't need to bother with.

**Comment by lestrrat** [comment]
@michaelboyd2 thank you! I suppose `.bazelversion` is a no-brainer. I'll look into the presets. The latter two I think I can wait until somebody who actually needs them comes along :)

**Comment by sfc-gh-mussakli** [comment]
> @lestrrat thanks I fixed my problem, I just had some deps in the wrong order - your comment helped.
> 
> I had a look at the bazel branch it worked well for me: build, test, gazelle. Looks good to me.
> 
> Maybe consider adding a .bazelversion? There are also things like https://blog.aspect.dev/bazelrc-presets, https://github.com/keith/buildifier-prebuilt and https://github.com/aspect-build/bazel-super-formatter that probably you don't need to bother with.

I hit this exact same issue with my Go/Bazel/Gazelle setup, but because the fix wasn't specified I still had to hunt down the fix myself.

It's related to the `rules_go` dependency issue highlighted here: https://github.com/bazelbuild/rules_go/issues/2595

If you have a `WORKSPACE.bazel` file that calls `go_repository` rule to take on this package (or any downstream package), make sure the `go_repository` rules are declared before `go_rules_dependencies()` and `go_register_toolchains` etc.
