### ISSUE TITLE
Missing `alg` in Key(Set)

### ISSUE THREAD

**Issue by vpavlin** [lestrrat-go/jwx#879]
I am trying to verify a JWT token produced by [web3auth](https://web3auth.io/docs/pnp/features/server-side-verification/social-login-users) which relies on JWKS from https://api.openlogin.com/jwks

For some reason this does not contain `alg` field, which results in 

```
failed to find matching key for verification: invalid signatre algorithm : invalid jwa.SignatureAlgorithm value
```

error.

I will try to reach out to them to see if they could ass the `alg` field, but wanted to ask for recommendation for approach in the meantime. 

If I simply download to key and set the algorithm explicitly, it works, but I would really like to use AutoRefresher.

**Comment by lestrrat** [comment]
This library tries to be strict by default, but gives you ways to workaround individual cases. For matching arbitrary keys without relying on the default selection algorithm, please read [this](https://github.com/lestrrat-go/jwx/blob/develop/v2/docs/01-jwt.md#parse-and-verify-a-jwt-using-arbitrary-keys). The important bit is the `KeyProvider`. This gives you a way to send any key to be tried for verification
