### ISSUE TITLE
Cannot remove typ header

### ISSUE THREAD

**Issue by decentralgabe** [lestrrat-go/jwx#889]
The code requires you to have a typ header, and no option exists to remove it. 

https://github.com/lestrrat-go/jwx/blob/develop/v2/jwt/serialize.go#L146

You can set alternate values, however, this is not sufficient for my use case.

Is there a way to remove `typ` header entirely?

**Comment by decentralgabe** [comment]
Sorry. I see this is correct and I can use a JWS if I wish there to be no typ header

**Comment by lestrrat** [comment]
@decentralgabe yep.

For the future readers, the serializer from `jwt` package above is specialized for the most common JWT usage, and if you need a more generic JWS approach, you can always use the `jws` package.
