### ISSUE TITLE
JWT is not verified by JWKS if `alg` field is not present

### ISSUE THREAD

**Issue by mehran75** [lestrrat-go/jwx#896]
**Describe the bug**

I'm using this library to verify a JWT using JWKS. The problem is that the provided key sets don't have the field `alg` in their JSON objects, so the library is not able to verify it because the algorithm is nil. Here is how I'm using it:

```go
data := []byte{`{
    "keys": [
        {
            "kty": "RSA",
            "kid": "KID_string",
            "n": "string",
            "e": "AQAB"
        }
    ]
}`}
keySet, err := jwk.Parse(data) 
_, err = jws.VerifySet([]byte(token), keySet)

```

go version go1.19.5 darwin/amd64

**To Reproduce / Expected behavior**
If I add the field `alg` to the key (`"alg": "RS256"`) the psudo code above (in `data`) then everything works normally. The library should be able to verify the key even without the provided `alg`. 

**Additional context**
the token gets verified in jwt.io without having `alg` in the key set

**Comment by lestrrat** [comment]
@mehran75 before anything, based on the presence of `jws.VerifySet`, I think you are using v1? Is it necessary? Can you use v2? v2 gives you way more options to match keys and data

**Comment by mehran75** [comment]
> @mehran75 before anything, based on the presence of `jws.VerifySet`, I think you are using v1? Is it necessary? Can you use v2? v2 gives you way more options to match keys and data

Nice catch on v1. 
I just tried v2 and I've seen the new changes. Good job on the new options!

In my case, the keys are supposed to be fetched from a URL that is mentioned in the issuer field `iss`. It is dynamic and may or may not contain `.well-known/jwks.json` in the end, so I don't think I can use the option `WithVerifyAuto()` on that. 

However, I was able to use the option `InferAlgorithmFromKey()` after I downloaded the keys separately, which worked nicely.
`_, err = jws.Verify([]byte(token), jws.WithKeySet(keySet, jws.WithInferAlgorithmFromKey(true)))`

It would be nice to have a feature for verifying the token from the issuer if there isn't one already. Anyways, I will consider this issue closed.

**Comment by lestrrat** [comment]
I'm not sure I follow this.

> It would be nice to have a feature for verifying the token from the issuer if there isn't one already

If you are up to it, please consider creating a new issue with (pseudo)code of what you expect to happen if you suggested feature existed.
