### ISSUE TITLE
[v3] Errors getting swallowed by JWK cache

### ISSUE THREAD

**Issue by JulianRushdown** [lestrrat-go/jwx#922]
Hello, and thank you for maintaining this great project.

I've prepared a playground illustrating the issue we are having here: 
https://goplay.tools/snippet/aT_YarNVebm 

We've been using the v2 JWK library to handle caching some JWK keys we fetch and refresh from an outside source. We have come across an interesting case when the JWK endpoint we query returns a 403.
When the keys are fetched, the endpoint returns a 403 and some default HTML-formatted access denied error message. The Parse on this expectedly bombs, and a nil interface is stored in the cache's data entry.
The next attempt to Get() from the cache will pull the nil entry and then attempt to coerce it to a Set which obviously fails.
```
set, ok := v.(Set)
if !ok {
  return nil, fmt.Errorf(`cached object is not a Set (was %T)`, v)
}
return set, nil
```
We are mainly concerned with the original HTTP error not being surfaced to the calling level. We can get around this by defining our own HTTP client that checks for it, but it seems that the default behavior should do some sort of check on the response status code before storing it. Alternatively, maybe any HTTP error received should be stored alongside  the data entry in the cache to surface to the end user. Curious to hear the maintainers perspective on this. Thank you!

**Comment by lestrrat** [comment]
I think my original intention was that you would at least call `c.Refresh()` -- possibly multiple times -- before using `c.Get()`.
That basically means that you would at least warm the cache once in order to avoid this situation.

IIRC the main reason for this was that I thought it was hard for users to distinguish initial fetch errors/refreshing errors/genuine parse errors if you used it directly in a loop without warming it first

```go
//pseudocode

// something _like_ this,
for {
   if !c.IsRegistered(url) {
      _ := c.Register(url)
      _, err := c.Refresh(url)
      if err != nil { c.Unregister(url) }
      // error case, halt or ignore this iteration
      continue
  } else {
     c.Get(url)
  }
}

// vs

for {
  _, err := c.Get(url)
}
```

Now, I'm fairly certain there are practical usecases that I missed, so please feel free to convince me otherwise if the above does not fit your needs.

**Comment by lestrrat** [comment]
@JulianRushdown I'm glad you were able to work your problem out, however I was a bit concerned with the fact that you were saying even warming the cache "swallows" the error, so I checked with a test:

```go
func TestGH922(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusForbidden)
	}))
	defer srv.Close()

	// Refresh should fail, but we should receive the error
	c := jwk.NewCache(ctx)
	c.Register(srv.URL)
	
	// Run these checks multiple times so that we can be sure that the cache is
	// NOT being used
	for i := 0; i < 5; i++ {
		// Refresh should fail, but we should receive the 403 error
		_, err := c.Refresh(ctx, srv.URL)
		require.Error(t, err, `c.Refresh should fail`)
		// t.Logf("%s", err)
	}
}
```

In the above test `c.Refresh` does return an error, so you should be able to warm the cache while catching errors.

Now, if I print out the error by uncommenting the `t.Logf` line, I get something like `jwk_test.go:2152: failed to fetch "http://127.0.0.1:35339": failed to transform HTTP response for "http://127.0.0.1:35339": failed to parse JWK set at "http://127.0.0.1:35339": failed to unmarshal JWK set: EOF` -- which now finally clicked in me: by being "swallowed", do you mean to say that the error _message_ is not indicative of the non-200 HTTP response? I always interpreted as "there's no way to obtain the error"

If the error message is the problem I can certainly change the above error to look like

```
jwk_test.go:2152: failed to fetch "http://127.0.0.1:42521": failed to transform HTTP response for "http://127.0.0.1:42521": failed to process response: non-200 response code "403 Forbidden"
```

Is this (at least part of) what you would like?
