### ISSUE TITLE
Problem setting key_ops key value

### ISSUE THREAD

**Issue by GreenMan-Network** [lestrrat-go/jwx#945]
**Bug description**
go version go1.20.4 linux/amd64

**The library is not setting the value of the key_ops key in a rsa jwk.**

Test code:
```
func TestKeyOpsValueSetting(t *testing.T) {
	t.Log("Testing setting a value to the key_ops field.")

	privateRawRsaKey, err := rsa.GenerateKey(rand.Reader, 4096)
	if err != nil {
		t.Error("Error generating encruption client private key: ", err)
		return
	}

	newJwk, err := jwk.New(privateRawRsaKey.PublicKey)
	if err != nil {
		t.Error("Error creating jwk: ", err)
		return
	}

	newJwk.Set(jwk.KeyIDKey, uuid.New().String())

	newJwk.Set(jwk.KeyUsageKey, jwk.ForSignature)
	newJwk.Set(jwk.KeyOpsKey, jwk.KeyOpSign)

	buf, err := json.MarshalIndent(newJwk, "", "  ")
	if err != nil {
		fmt.Printf("failed to marshal key into JSON: %s\n", err)
		return
	}
	t.Log("JWKs: ", string(buf))

	if newJwk.KeyOps() == nil {
		t.Error("KeyOps is nil.")
		return
	}
}
```

Output:
JWKs:  {
   "e": "AQAB",
   "kid": "3ec9b171-3e51-4d4c-9f1d-eda9703b353b",
   "kty": "RSA",
   "n": "xWomKluLlZyCYQOcicFFRqy2m5CIWyojSM8nDCa3kjfbbS7UKyw6YsbErCMQ0_JA1-42HCnbzB3_8EgpR484NMHu1bk75Ylu_iJMan-_nN1u0geA1IZEdG2FC9nY2p9EYuNmXLt1LhcQ7e39RAGyWMDDSXDDZxwhvPMxMjZ65mjNwV1G4viZN7GYrGhXAGp2hkJoDS9qjMK3iMofK7T7e0gOJ8mvxgu06UHaIGlP95CZRoWhoYF_qrXtccasiC-Gj18rmWkhvOF0XixBqTgTLTjfQmjPkrq41mZozHewr08vOlMjF4TKAsRqX6umnh5hoTpp5CS4-2myxPzKGAebxJvoUm8NA0_U7ckPmHpPJ9Tw810u1hGpHKX34-WIuflv51F2GqMV8r3FfNOEaOfdgsKrRs_-ZxSEz6r_MbZojpdLQ8pVsSox71siUve_sMTY6xCXI8eUOoyK7sD0jNbdrZ2JjI9zizYR-fgK7n2MoERNwHx78Yg5AHyzfvysR6tUNLcbATUVnxfb0LsxRhOmZpwtWmlrby14BbJynxr6NWCrA-ZYhBb18pM81jB0dUqVnCB-z2J4OhgoDrynGbWyUcoRCbIcEYcvAzoSGIDnopW3Wqu6jCjeqDnoiZrDsy8xzt4yYhKqJN-JKXvpjONASS9zzzQCR73YScgzJ4aKMTU",
   "use": "sig"
}
KeyOps is nil.

Capturing the error I get:
Error setting KeyOps:  invalid value for key_ops key: invalid value jwk.KeyOperation

**Additional context**
In the funciton: 
func (ops *KeyOperationList) Accept(v interface{}) error
The statement:
x := v.(type)
Dos not attribute the value "string" to x. It attributes the value "KeyOperation".
Take a look:

Code:
```
func TestString(t *testing.T) {
	testString := jwk.KeyOpSign

	var testInterface interface{}

	testInterface = testString

	switch x := testInterface.(type) {
	case string:
		t.Log("String: ", x)
	case jwk.KeyOperation:
		t.Log("KeyOperation: ", x)
	default:
		t.Error("Anything else: ", x)
	}
}
```

Output:
KeyOperation:  sign

**Comment by lestrrat** [comment]
Thanks, Is this on v1?

**Comment by lestrrat** [comment]
@GreenMan-Network I created #946. Please let me know if this fixes your problem. Also, if you are using this in a new project, with no other dependencies on v1, please consider using v2 instead.

**Comment by GreenMan-Network** [comment]
Ok. I have just updated for the v2, and in this version, the key_ops setting is working properly.
Thank you!

**Comment by GreenMan-Network** [comment]
Also the solution you did worked:

`func TestKeyOpsValueSetting(t *testing.T) {
	t.Log("Testing setting a value to the key_ops field.")

	privateRawRsaKey, err := rsa.GenerateKey(rand.Reader, 4096)
	if err != nil {
		t.Error("Error generating encruption client private key: ", err)
		return
	}

	newJwk, err := jwk.New(privateRawRsaKey.PublicKey)
	if err != nil {
		t.Error("Failed to create jwk.")
		return
	}

	newJwk.Set(jwk.KeyIDKey, uuid.New().String())
	newJwk.Set(jwk.KeyUsageKey, jwk.ForSignature)

	keyOpSignVet := []jwk.KeyOperation{
		jwk.KeyOpVerify,
		jwk.KeyOpEncrypt,
	}

	newJwk.Set(jwk.KeyOpsKey, keyOpSignVet)

	buf, err := json.MarshalIndent(newJwk, "", "  ")
	if err != nil {
		t.Error("failed to marshal key into JSON.")
		return
	}
	t.Log("JWKs: ", string(buf))

	if newJwk.KeyOps() == nil {
		t.Error("KeyOps is nil.")
		return
	}
}`

Output:
JWKs:  {
          "e": "AQAB",
          **"key_ops": [
            "verify",
            "encrypt"
          ],**
          "kid": "f48d93bc-08b5-4ac0-9a49-d65f59b6b840",
          "kty": "RSA",
          "n": "nanp-SB7If9_ZATd-1nXN20aQ_bBYHY-OyK5mgYMthLMmDeIjLBt3zJPePtVhAyii_vBkX720U8kTTZbAWyxjdXKdzLoQngNEfu3bnZdfHDJ52AkcNcvqUXnzOoXFukOy2hOdJDUaQYxx6iEEQ4emDqGgRjl0lCL26OFzE1MiWeQrTUPt8G8T8hpd0z1qDy22OP1H48Du-5vKYxVGnvSmCKGqmKWCbJadG8DDiszsbDbGCosthiixaSxXo25g1LOoqlqmAm3eGWSkv93ufIrNolFlYe-rof3UY8OigDdPzb3a2nDMrN3kx_QRYK9d5B8YRS9etu8HXuqYR-C9IjIqYzUjv4EQIAi-yJIUw7hrQkXLAq2rqeD9g4dx6nO2kDKRMIpvikfJI7KIBcv33RXu-OYvFlAnYTTlUlFPXMUsIUYJbGTkQTvRiGBdkD7giCiLk5m7_OYHRicWXk7dAGon-s-9Qe2CVMPHret_D_vhQH489Cgu8kfROlQ4pV8ZTCYW4b-PnRpNCSbE4JP9hLbV4iFNYQ-poebqnNo2xA6XvDzDQWND5ueWFP_WwsQjB-T4L_PA3DZ_reVv47-XnNSgRDhnX0Ewxz1PTl4hyKDJxNXb86W5qSTSqtfASnQHcUGSn-efTICvPpKw91naGbmU_Z0Lb_12wQZlokhzPC0bM8",
          "use": "sig"
        }
