### ISSUE TITLE
When generating encrypted JWTs, most `jwe.EncryptOption` are ineffective

### ISSUE THREAD

**Issue by ItalyPaleAle** [lestrrat-go/jwx#951]
When generating an encrypted JWT, it's possible to pass encryption options with the `jwe.WithEncryptOption`. However, it seems that the only option that's accepted is `jwe.WithContentEncryption` and other options (in my case, `jwe.WithCompress`) are ignored.

Repro:

```go
val, err := jwt.NewSerializer().
	Sign(
		jwt.WithKey(jwa.HS256, signingKey),
	).
	Encrypt(
		jwt.WithKey(jwa.A128KW, encryptionKey),
		jwt.WithEncryptOption(jwe.WithContentEncryption(jwa.A128GCM)),
		jwt.WithEncryptOption(jwe.WithCompress(jwa.Deflate)),
	).
	Serialize(token)
```

It seems to be due to the fact that the code only supports passing the option that passes the key. Other options are ignored.

**Comment by lestrrat** [comment]
Just as a note, changes were merged through #953
