### ISSUE TITLE
PR for JAdES Signatures

### ISSUE THREAD

**Issue by aodhan-domhnaill** [lestrrat-go/jwx#958]
Would you accept a PR for JAdES support?

JAdES is an extension of JWS https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf. This could be used for electronically signing documents.

Here is an implementation by the European Commission https://github.com/esig/dss/tree/master/dss-jades/src/main/java/eu/europa/esig/dss/jades

**Comment by lestrrat** [comment]
Quick googling didn't yield in many usecases so at the moment I'm reluctant to include it in the main repository.
You are welcome to prove me wrong, but meanwhile there's nothing stopping you from using `jws.RegisterSigner` and `jws.RegisterVerifier` to incorporate this algorithm if/when you created a separate package for it.

**Comment by aodhan-domhnaill** [comment]
Okay. Closing and I'll build it separately.
