### ISSUE TITLE
x509 can't support secp256k1 when calling jwk.Pem

### ISSUE THREAD

**Issue by shaneing** [lestrrat-go/jwx#961]
**Abstract**

```go
pem, err := jwk.Pem(public)
if err != nil {
  panic(err)
}
```

It will be got the following error message:

```
failed to marshal PKIX: x509: unsupported elliptic curve
```

**Describe the proposed solution/change**

I don't how to do it because the package crypto/x509 is a built-in package.

**Comment by lestrrat** [comment]
@shaneing what's in `public`?

**Comment by lestrrat** [comment]
Oh, nevermind, it's a secp256k1 key. It's not supported ATM. PRs welcome.
