### ISSUE TITLE
Outdated example for iterating through keyset in `v2/jwk` readme

### ISSUE THREAD

**Issue by jhiemstrawisc** [lestrrat-go/jwx#970]
I was working with the `/v2/jwks` package and following along the example under the header "Parse and use a JWK key:". It looks like the code in the example for iterating through a keyset might be leftover from v1, as it contains:
`for it := set.Iterate(context.Background()); it.Next(context.Background()); {`

This did not work for me, but using `set.Keys(context.Background())` does work to return a functioning iterator. I realized this after reading the [v1->v2 changelog](https://github.com/lestrrat-go/jwx/blob/develop/v2/Changes-v2.md). Am I correct in thinking this should be updated?

**Comment by lestrrat** [comment]
Yes, it should be updated!

**Comment by lestrrat** [comment]
I think #971 and #972 fixes this. Please reopen if this was not enough. Thanks for the headsup
